### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by HCcyrus** [ClanGenOfficial/clangen#1001]
Game crashes when opening tabs such as 'see relationships' and 'history.' 

Warnings:
Line 4 : INTERNAL ERROR when analyzing the code: Useless suppression of 'line-too-long'
Reported when a message is explicitly disabled for a line or a block of code, but never triggered.
Line 35 : Using open without explicitly specifying an encoding
It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/
Line 36 : Using open without explicitly specifying an encoding
It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/
Line 66 : Argument 1 to "__excepthook__" has incompatible type "Type[type]"; expected "Type[BaseException]"
Line 89 : INTERNAL ERROR when analyzing the code: Useless suppression of 'line-too-long'
Reported when a message is explicitly disabled for a line or a block of code, but never triggered.
Line 111 : INTERNAL ERROR when analyzing the code: Useless suppression of 'ungrouped-imports'

Could be a personal issue I could easily fix, I'm not well-versed in python or coding in general.

**Comment by ghost** [comment]
I am seeing some warning messages when I run the game. The first one says "INTERNAL ERROR when analyzing the code: Useless suppression of 'line-too-long'." I am not sure what this means, but it seems like a problem with the code itself.

The second warning message says "Using open without explicitly specifying an encoding." It seems like this is related to how the code is opening files. The warning suggests that it is better to specify an encoding when opening documents, as using the system default implicitly can create problems on other operating systems.

The third warning message says "Argument 1 to 'excepthook' has incompatible type 'Type[type]'; expected 'Type[BaseException]'." I am not sure what this means either, but it seems like another problem with the code.

The last two warning messages both say "INTERNAL ERROR when analyzing the code: Useless suppression of 'line-too-long'" and "INTERNAL ERROR when analyzing the code: Useless suppression of 'ungrouped-imports'." These also seem like problems with the code itself.

Overall, it seems like the problem may be related to the code, and I may need to make some changes to fix it. However, I am not well-versed in python or coding in general, so I may need some assistance in figuring out how to fix this issue.

**Comment by lillithrosepup** [comment]
Please [join the discord](https://discord.com/invite/clangen) to help report the bug, as we can get much more info there

**Comment by lillithrosepup** [comment]
This has been fixed and the issue can be closed!
