### ISSUE TITLE
Housekeeping file error

### ISSUE THREAD

**Issue by SnailB0x** [ClanGenOfficial/clangen#1110]
Whenever I try to launch the game, it says that it is missing a module called "scripts.housekeeping" and I haven't a clue how to fix this. I've checked file requirements and everything!
![Screenshot_2](https://user-images.githubusercontent.com/115950110/227725530-d1af823d-b787-44d0-9349-5b4ed04fcd6c.png)

**Comment by Ice1456** [comment]
Hi,
I had the same problem, to fix it if you use thonny you need to uninstall the app and install it again then it should be playable again :]

**Comment by Ice1456** [comment]
Hi, 
I had the same problem a couple of days ago.
You need to type %appdata% in the search bar at the bottom  of the homescreen,
Then delete the thonny and or python foulder.[ its important that you delete the python foulder becourse that's what causing the problem]
Then download thonny again [ do the same steps you did when you started playing the game, like download some modules] then it should be playable :]

**Comment by DasBlackfur** [comment]
Closing this issue for cleanup, please reopen if the issue persists.
