### ISSUE TITLE
Dev version not opening 

### ISSUE THREAD

**Issue by Echo-Love111** [ClanGenOfficial/clangen#1266]
Hello! I downloaded everything and now the game will not load. It’s just a blank black screen

**Comment by scribblecrumb** [comment]
Hey there, we can't find the root of the problem if you don't provide any information.

**Comment by DasBlackfur** [comment]
Please provide more details, especially console logs.

**Comment by MaryTheCrow** [comment]
Hello, I believe I am experiencing the same problem. When opening the game Thonny throws out an error _ModuleNotFoundError: No module named 'pgpy'_
I've attached an image of this.

![Ekrānuzņēmums (117)](https://user-images.githubusercontent.com/130838389/232213593-c433c8b5-bfe6-47e9-b999-183814efbdac.png)

**Comment by archanyhm** [comment]
> Hello, I believe I am experiencing the same problem. When opening the game Thonny throws out an error _ModuleNotFoundError: No module named 'pgpy'_ I've attached an image of this.
> 
> ![Ekrānuzņēmums (117)](https://user-images.githubusercontent.com/130838389/232213593-c433c8b5-bfe6-47e9-b999-183814efbdac.png)

This is not an issue with our codebase, you're missing some external dependencies. The error message you're receiving tells you exactly what module you're missing and a simple Google search tells you how to fix it.

**Comment by lillithrosepup** [comment]
This issue is complete and can be closed!
