### ISSUE TITLE
Issues with the code 

### ISSUE THREAD

**Issue by Machonk098** [ClanGenOfficial/clangen#1280]
It won’t allow me to open it, it says there is issues with several lines in the code, I’ve tried downloading all the modules/tools necessary on thonny and it’s still having the same issue (line 264 is the main problem I think)

**Comment by Machonk098** [comment]
Line 136- internal error 
Line 250- using open without explicitly specifying an encoding 
Line 323- unused variable “e” 
Line 328- unused argument cmd 
Line 499- unused argument cmd
Line 625- internal error 
![Uploading image.jpg…]()
Previously stated there was no module named pygpy

**Comment by goonbridge** [comment]
I got it working by installing the following modules with pip
platformdirs
pgpy
requests
strenum

**Comment by lillithrosepup** [comment]
https://cdn.discordapp.com/attachments/1054940165816209438/1095125859700064326/2023-04-10_19-16-22.mp4
