### ISSUE TITLE
multiple errors come up when i try to run the new update

### ISSUE THREAD

**Issue by lumberpickle** [ClanGenOfficial/clangen#1281]
when i run the code i get errors popping up in the bottom box, i cant figure out why they are there and what they mean. they all pop up as red text.

Errors: 
Git CLI invocation failed
Traceback (most recent call last):

return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

 with Popen(*popenargs, **kwargs) as process:

   self._execute_child(args, executable, preexec_fn, close_fds,

  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Traceback (most recent call last):

from scripts.game_structure.load_cat import load_cats, version_convert

 from .game_essentials import game

 import ujson
ImportError: DLL load failed while importing ujson: The specified module could not be found.

im not sure if all of these are actually errors, but they all come up as red text.

**Comment by lillithrosepup** [comment]
https://cdn.discordapp.com/attachments/1054940165816209438/1095125859700064326/2023-04-10_19-16-22.mp4
