### ISSUE TITLE
A cat with all of their legs are talking to the kits about their missing legs

### ISSUE THREAD

**Issue by Aprilx111** [ClanGenOfficial/clangen#1285]
![image](https://user-images.githubusercontent.com/96721032/231338597-9a651eb3-f9cf-4efe-9e28-8cce42e39dc5.png)

**Comment by lillithrosepup** [comment]
We are aware of the issue and a fix is on the way!

**Comment by lillithrosepup** [comment]
This has been fixed, and the issue can be closed!
