### ISSUE TITLE
Errors in thoughts

### ISSUE THREAD

**Issue by MaryTheCrow** [ClanGenOfficial/clangen#1318]
I've encountered multiple errors in thoughts in the newest dev version. I've attached examples and the error thonny shows during them.
![Ekrānuzņēmums (122)](https://user-images.githubusercontent.com/130838389/232287893-5ddf525f-d740-4dd3-abd2-a6ccd45d6573.png)
![Ekrānuzņēmums (123)](https://user-images.githubusercontent.com/130838389/232287897-9d435fa3-8665-4d09-b163-46c848a4f27c.png)
![Ekrānuzņēmums (124)](https://user-images.githubusercontent.com/130838389/232287904-be211d74-382b-4737-b4cc-2456192b9021.png)
![Ekrānuzņēmums (126)](https://user-images.githubusercontent.com/130838389/232287968-da158af3-9be7-450f-9bfb-c278aa436da2.png)

**Comment by Lixxis** [comment]
We are aware, that there are some bugs which are related to the new pronoun system.
We are working on a fix, if you have other bugs, please report them to your [google form](https://docs.google.com/forms/d/e/1FAIpQLSfl-H-HjSTfZ51DCtIHj8uGKtWF-3uysSaP8R6KMTLp7nzmMw/viewform).
