### ISSUE TITLE
Error in thoughts while dead

### ISSUE THREAD

**Issue by mistimystics772** [ClanGenOfficial/clangen#1348]
Wants to be the new deputy but is dead...? Unsure if this is an actual issue because the cat just recently died.

![Screenshot 2023-04-17 212528](https://user-images.githubusercontent.com/131110086/232654360-14bbeaa8-de7b-4f2d-bc65-948a0e58b775.jpg)

**Comment by keyraven** [comment]
This is for the web version, which is several versions behind the version hosted in this repository.  The web version is currently very buggy, and we don't currently recommend it.
