### ISSUE TITLE
Code is requesting "scripts.housekeeping" which doesn't exist

### ISSUE THREAD

**Issue by TuffCat** [ClanGenOfficial/clangen#1393]
I'm trying to run the newest version(downloaded just a couple minutes before posting this) in thonny, which is where it's usually run. However, whenever I try to click run, it gives me an error, saying "ModuleNotFoundError: No module named 'scripts.housekeeping'".

The thing is, scripts.housekeeping doesn't exist. It's not in the packages, it's not in the files of clangen, and I searched it on the internet with not a single result about code. Is there anybody on this github who knows coding better than I do and could help with this?

Thank you for reading this <3

**Comment by TuffCat** [comment]
So I found the scripts folder in the files. The housekeeping folder is inside it and a python file called log_cleanup is inside the housekeeping folder. I assume that python file is what the code is looking for. But, running the code in thonny still doesn't work- it still doesn't know where scripts.housekeeping is...

**Comment by archanyhm** [comment]
This is a Thonny-specific issue and unrelated to our codebase. However, you're correct in assuming that the log_cleanup.py file is what is being looked for.

Closing this issue.
