### ISSUE TITLE
Game not opening

### ISSUE THREAD

**Issue by RoyalMothness** [ClanGenOfficial/clangen#1426]
Might be just on my end but this message comes up when I try to play;
self.error_label = pygame_gui.elements.UITextBox(
TypeError: UITextBox.__init__() got an unexpected keyword argument 'starting_height'
>>>

**Comment by schweinsbergs** [comment]
I'm also having this issue  on the newest commits. I'm on Windows 10, using thonny with the latest updates to all the packages.

**Comment by RoyalMothness** [comment]
Yeah, I fixed it. You have to update your Py Gui library or something. Just
go on thonny, go to tools>manage packages>search for gui library something
or other>update.

Sorry for my vagueness. I have a shit memory. Hope this helps!
