### ISSUE TITLE
I can't play

### ISSUE THREAD

**Issue by Superplayer0** [ClanGenOfficial/clangen#1473]
Hi! I'm not good at programming, so I'm writing here. I ran into such a problem, and now I can't play saved clans
![jTxeEugn 1](https://github.com/Thlumyn/clangen/assets/134165573/09633a4a-59a4-41fe-bfcd-51b15099eab0)

**Comment by keyraven** [comment]
Sorry for the late response! It is likely your save was corrupted and can no longer be saved.  This issue has been solved in the latest development version, and the fix will be included in the next release.
