### ISSUE TITLE
issue with ujson 

### ISSUE THREAD

**Issue by inkaDoodle** [ClanGenOfficial/clangen#1476]
![issue](https://github.com/Thlumyn/clangen/assets/134235482/57fc9eb2-da86-45fb-bd7d-524fbb627c83)
After I downloaded all the content needed from the requirement page but this continues to appear even after Installed ujson to thonny what am I missing

**Comment by keyraven** [comment]
This is an issue with your installation of python, and not a bug with ClanGen
