### ISSUE TITLE
Game not auto updating properly

### ISSUE THREAD

**Issue by redgreenyellowyellow** [ClanGenOfficial/clangen#1477]
Today while booting up this version of Clangen, it told me there was an update available. For the past 30 minutes I have been stuck in a loop of the game going through the downloading and verifying process, telling me it will automatically restart, then closing, but never reopening itself. If I go to run it manually, like normal, it tells me it hasn't installed the update and needs to do that again. 

I'm still not sure if I'm *supposed* to see a command line window while I have the game running, but I do, and it does this before it closes itself
![what is going on in here](https://github.com/Thlumyn/clangen/assets/134298867/e2d2c02f-b7a1-41d8-816e-bf3717dfbd32)

I'm not tech savvy in the slightest so really I have no clue what's going on here. I just followed a reddit tutorial to get this version of the game. If there isn't much of a fix for it I'd at least like to be able to transfer saves from this version over to a stable version but the only tutorials I can find for anything similar are for transferring from the old August build to the new one.

**Comment by keyraven** [comment]
Hello! I'm assuming you downloaded the game from nightly.  In that case, the command line window is supposed to be there.  The version you downloaded is a test version of the game, and the console allows easy access to any debug information. 

The autoupdater usually works, but will occasionally fail. In that case, you will need to redownload from the original source. 

It is not possible to transfer saves from more a recent versions to an older version. Therefore, you won't be able to transfer saves from the dev builds to stable.
