### ISSUE TITLE
Game Crashing when Med. Cat added to Patrol

### ISSUE THREAD

**Issue by TheGarfungus** [ClanGenOfficial/clangen#1525]
Just downloaded the most recent update and discovered that whenever I try to add a certain cat to any patrol the game crashes. for some specifics the cat was a warrior that I just turned into a Med. Cat and there was already one Med. Cat. The game works fine as long as I never add the one cat to any patrol.

**Comment by keyraven** [comment]
Are you still experiencing this issue?

**Comment by Shadyfur-Shadowedheart** [comment]
The game must be confused with the cat, it has it registered as both med and warrior. That is the main reason why it is crashing

**Comment by archanyhm** [comment]
Hi. Since we haven't received a response since June 8th, I assume that this can be closed. If the issue persists, feel free to re-open it (optimally with more information included).
