### ISSUE TITLE
Please add a toggle for the LGBTQ Events.

### ISSUE THREAD

**Issue by NotCgeorge** [ClanGenOfficial/clangen#1540]
You don't have to get rid of them just put them as an option in the settings.

**Comment by keyraven** [comment]
no

**Comment by keyraven** [comment]
There is the change gender button on the cat's profile, but there will be no options beyond that. We have a hard stance on never allowing toggles for identity-based features: this means no toggles for same-sex relationships, cats with more than one mate, or trans/nonbinary cats

**Comment by NotCgeorge** [comment]
Why?
