### ISSUE TITLE
Rephrased question.

### ISSUE THREAD

**Issue by NotCgeorge** [ClanGenOfficial/clangen#1541]
From my original question: Please add a toggle for the LGBTQ Events.

I am not asking for the removal LGBTQ only the events, like. Ex: Ligmstar has decided that being tom just doesn't suit them anymore.    
It's not that hard to make this happen (it's a literally just a Boolean) and your "hard stance on never allowing toggles for identity-based features", is really hypocritical since you can LITERALLY CHANGED THEIR IDENTITIES, with the change gender button.  

+ the game wouldn't change without those events, it only gives the player more control over the character.

PS: keep working on the game its a really cool the way it works and good luck to all the team.

**Comment by NotCgeorge** [comment]
And accessories also.

**Comment by keyraven** [comment]
Hello. Your question was answered and the issue closed. There are some decisions regarding that game that have been made collectively by those working on the game.  This is one of them.
