### ISSUE TITLE
game wont open.

### ISSUE THREAD

**Issue by Just-a-dumRat** [ClanGenOfficial/clangen#1634]
I just downloaded the newest version of clangen, but it wont open. I have extracted the file and downloaded the right version for my computer. (windows 32bit in case you need to know) And when I open it, it opens for a split second and then closes. I have tried redownloading it, and it still wont work, and I don't have any anti virus protection either.

**Comment by Summerange** [comment]
yesterday, I went on GitHub the game was working, and when I made a new clan to see if the two clans would still work, the game stopped loading and no matter how many times I refreshed the page it still wouldn't work.

**Comment by archanyhm** [comment]
Hi. If this issue still persists, please re-open it with more information attached.
