### ISSUE TITLE
[BUG] I interrupted an update when it was still at 0% and it went through with it

### ISSUE THREAD

**Issue by herlocksholmes1888** [ClanGenOfficial/clangen#1636]
Hi! So, I interrupted an update when it was still starting (because I wanted to take a screenshot of the clan I had in case anything went wrong) and then the game gave me a warn, closed on its own, and said it was going to open again. Well, it didn't open again. I went to do it manually, but it didn't want to open either. I reinstalled the game, and it's quite alright again, just wanted to warn you guys that the interruption clearly isn't working as it's supposed to :'3 
(I did manage to screenshot the clan before I reinstalled from scratch, though, so that's quite alright!)

**Comment by archanyhm** [comment]
Hi @herlocksholmes1888,

the behaviour you observed is indeed not intended and the cancel button is currently non-functional. This is definitely a big problem and I'll fix it within the next few days. Feel free to poke me or bump this issue in case it gets lost again.

Thanks for the report and for your patience!
