### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by Verieco** [ClanGenOfficial/clangen#1664]
I'm not really sure if others are having the same problem but every time I try to open the game, even with excellent wifi all it does is do the loading screen and after that I'm met with a black screen, I've tried waiting for a few minutes but nothing changed. Also I played the game earlier today and it was completely fine so I'm pretty sure this is a bug.

**Comment by keyraven** [comment]
Are you still having this issue?

**Comment by archanyhm** [comment]
Hi. Due to the lack of an answer, this issue is considered stale and will be closed for now. If the issue(s) you experience(d) persists, feel free to re-open this issue with more information attached. @Verieco
