### ISSUE TITLE
Loners can be put in StarClan

### ISSUE THREAD

**Issue by voidcxster** [ClanGenOfficial/clangen#1704]
Not sure if this is a bug or not, but when loners, exiled cats, kittypets, etc. die and are sent to the "Unknown Residence", you can click on the "Dangerous" option, exile them to the Dark Forest, then finally guide them to StarClan. 
![](https://cdn.discordapp.com/attachments/717526673658085539/1136523536702390322/image.png)

**Comment by keyraven** [comment]
This is not a bug! One day, we will probably add a button to send them directly to StarClan, if you wish.

**Comment by voidcxster** [comment]
Thanks for the reply keyraven! A button to add them to StarClan would be great. Do you intend for there to be a button to send them back to the "Unknown Residence?" And if so, will there be a way to send Clan cats to the "Unknown Residence" as well?
