### ISSUE TITLE
Game crashes on start?

### ISSUE THREAD

**Issue by y0miel** [ClanGenOfficial/clangen#1714]
Just downloaded the latest version but every time I try to open the game, it gets stuck on the loading screen. I'm a bit tech illiterate but i keep getting the same error and I dont know what it means or how to fix it. Any help? 

self.error_label = pygame_gui.elements.UITextBox(
TypeError: UITextBox.__init__() got an unexpected keyword argument 'starting_height'

**Comment by archanyhm** [comment]
This is a dependency issue, not an issue with ClanGen. You should reinstall your dependencies.
