### ISSUE TITLE
Game stops responding upon open (+ python38?)

### ISSUE THREAD

**Issue by 6xolotl** [ClanGenOfficial/clangen#1723]
exactly what it says on the tin. i have to run it as administrator otherwise my antivirus just automatically deletes the exe file upon opening it (fuck off kapersky i know what i’m doing), but even when it opens, it stops responding on the first click and then just stays frozen forever. i’ve tried the windows 10, the 64bit, the 32bit (just in case), and all of them do the same thing. what the hell is going on??? am i the problem????????

i also tried running it within the zip file just to see if that would work, but it just kept telling me i was missing python38.dll, even after i downloaded it and put it where the error message was telling me to. so there’s that.

**Comment by keyraven** [comment]
This is likely an antivirus issue, and not an ClanGen itself.  I would suggest whitelisting ClanGen with your antivirus.
