### ISSUE TITLE
Blank after loading

### ISSUE THREAD

**Issue by CharizardNai** [ClanGenOfficial/clangen#1775]
Two days ago everything was running perfectly (aside from the occasional freezing after skipping a moon), but now every time I open it, the screen turns sky blue, waits till I move my cursor, shows the downloading bar on the top of the screen, waits a little, changes to the loading bar in the center of the screen, and then the whole website screen turns black, and this issue occurs no matter what internet browser I use. I am not the only victim of this, a few weeks ago my sister came to me complaining that her computer stopped working. Please fix this! I really enjoy https://clangen-web.github.io/ and I get bored easily without it.

**Comment by keyraven** [comment]
This repository hold the desktop version, and not the web version. 
The web version is currently suffering from a handful of issues which are not simple to resolve. If you experience the black screen, you can try to clear your browser's cache.  This is likely to fix your issue, but will delete any save-info. Unfortunately, there are no other known fixes.
