### ISSUE TITLE
Some Patrols have Stat-Cat Outcomes without any Included Stats

### ISSUE THREAD

**Issue by keyraven** [ClanGenOfficial/clangen#1780]
Some patrols have outcomes that are written like stat-cat outcomes, but are don't list any stats. Therefore, those outcomes are treated like normal outcomes.  However, since no s_c is chosen, the text replacement will not work correctly. 

Each of these patrols needs to be manually reviewed and fixed. Either the incorrect stat outcome needs to be removed, or appropriate stats need to be listed. 

It wasn't too difficult to write a script to identify all the patrols with this issue. The complete list is below. The first entry is the file, the second is the patrol_id. 

> ('forest\\hunting\\leaf-fall.json', 'fst_hunt_redvixen7')
> ('forest\\hunting\\leaf-fall.json', 'fst_hunt_redvixen8')
> ('forest\\hunting\\leaf-fall.json', 'fst_hunt_redvixen9')
> ('plains\\hunting\\leaf-fall.json', 'pln_hunt_leaf-fall_redvixen7')
> ('plains\\hunting\\leaf-fall.json', 'pln_hunt_leaf-fall_redvixen8')
> ('plains\\hunting\\leaf-fall.json', 'pln_hunt_leaf-fall_redvixen9')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringblackberry_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringcatmint_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringdaisy_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringdandelion_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringdandelion_newleaf3')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringmarigold_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringmullein_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringplantain_newleaf2')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringragwort_newleaf1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringtansy_newleaf1')
> ('forest\\hunting\\leaf-bare.json', 'fst_hunt_leaf-bare_ratking1')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen1')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen2')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen12')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen13')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen14')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen6')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen7')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen8')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen9')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen10')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen11')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen3')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen4')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen5')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen15')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen16')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen17')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen18')
> ('desert\\hunting\\hunting.json', 'dst_hunt_vision2')
> ('desert\\hunting\\hunting.json', 'dst_hunt_sneakprey3')
> ('plains\\hunting\\newleaf.json', 'pln_hunt_newleaf_redvixen1')
> ('plains\\hunting\\newleaf.json', 'pln_hunt_newleaf_redvixen2')
> ('plains\\hunting\\newleaf.json', 'pln_hunt_newleaf_redvixen3')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_redvixen1')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_redvixen2')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_redvixen3')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_grayvixen1')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_grayvixen2')
> ('beach\\hunting\\newleaf.json', 'bch_hunt_grayvixen3')
> ('desert\\hunting\\hunting_desert.json', 'dst_hunt_heat2')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringcatmint_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringdaisy_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringdandelion_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringdandelion_greenleaf3')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringelder_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringelder_greenleaf3')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringjuniper_greenleaf3')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringmarigold_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringmarigold_greenleaf3')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringmullein_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringoakleaves_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringtansy_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringthyme_greenleaf1')
> ('beach\\med\\greenleaf.json', 'bch_med_gatheringthyme_greenleaf3')
> ('beach\\hunting\\any.json', 'bch_hunt_octopus4')
> ('beach\\hunting\\any.json', 'bch_hunt_octopus4')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_redvixen7')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_redvixen8')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_redvixen9')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_grayvixen7')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_grayvixen8')
> ('beach\\hunting\\leaf-fall.json', 'bch_hunt_grayvixen9')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_greenleaf_ratking1')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_redvixen4')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_redvixen5')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_redvixen6')
> ('beach\\border\\any.json', 'bch_bord_trackrogue2')
> ('wetlands\\border\\border_wetlands.json', 'wtlnd_bord_solohostile4')
> ('wetlands\\border\\border_wetlands.json', 'wtlnd_bord_solohostile5')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringburdock_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringcatmint_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringdaisy_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringdandelion_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringdandelion_leaf-fall3')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringjuniper_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringjuniper_leaf-fall3')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringmarigold_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringmarigold_leaf-fall2')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringmarigold_leaf-fall3')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringmullein_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringtansy_leaf-fall1')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringthyme_leaf-fall2')
> ('beach\\med\\leaf-fall.json', 'bch_med_gatheringthyme_leaf-fall3')

**Comment by ZtheCorgi** [comment]
fixed in PR: 
('desert\hunting\hunting_desert.json', 'dst_hunt_heat2')
('beach\med\greenleaf.json', 'bch_med_gatheringcatmint_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringdaisy_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringdandelion_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringdandelion_greenleaf3')
('beach\med\greenleaf.json', 'bch_med_gatheringelder_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringelder_greenleaf3')
('beach\med\greenleaf.json', 'bch_med_gatheringjuniper_greenleaf3')
('beach\med\greenleaf.json', 'bch_med_gatheringmarigold_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringmarigold_greenleaf3')
('beach\med\greenleaf.json', 'bch_med_gatheringmullein_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringoakleaves_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringtansy_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringthyme_greenleaf1')
('beach\med\greenleaf.json', 'bch_med_gatheringthyme_greenleaf3')

**Comment by ZtheCorgi** [comment]
additionally just fixed bch_hunt_octopus4, added to PR

**Comment by ZtheCorgi** [comment]
why was this marked complete already? i have another PR in the works to fix the rest of the stat_cat issues.

**Comment by ZtheCorgi** [comment]
ok, this PR should fix the last few s_c errors in beach hunting leaf-fall and forest hunting greenleaf

https://github.com/Thlumyn/clangen/pull/1795

**Comment by keyraven** [comment]
Here are the last patrols with this issue: 

> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen1')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen2')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen12')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen13')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen14')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen6')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen7')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen8')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen9')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen10')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen11')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen3')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen4')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen5')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen15')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen16')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen17')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen18')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_redvixen4')
> ('forest\\hunting\\greenleaf.json', 'fst_hunt_random_greenleafsolowarrior1')
> ('beach\\med\\newleaf.json', 'bch_med_gatheringdandelion_newleaf3')
> ('beach\\border\\any.json', 'bch_bord_trackrogue2')
> ('desert\\hunting\\hunting.json', 'dst_hunt_vision2')
> ('desert\\hunting\\hunting.json', 'dst_hunt_sneakprey3')

**Comment by ZtheCorgi** [comment]
i will fix these when i can. particularly the fox patrols, as i already fixed those in beach and would like to make sure the fixes are consistent.

**Comment by keyraven** [comment]
> ('desert\\hunting\\hunting.json', 'dst_hunt_vision2')
> ('desert\\hunting\\hunting.json', 'dst_hunt_sneakprey3')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen1')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen2')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen12')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen13')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen14')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen6')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen7')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen8')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen9')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen10')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen11')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen3')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen4')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen5')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen15')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen16')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen17')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_redvixen18')

These is the up-to-date list of patrols with this issue. At the moment, it is only patrols in the non-playable wetlands and desert biomes.
