### ISSUE TITLE
Missing failed outcomes on patrols

### ISSUE THREAD

**Issue by Lixxis** [ClanGenOfficial/clangen#1787]
There are some patrols which have a missing "failed_outcomes": 
> pln_hunt_leaf-bare_mice_appshowoff1

**Low Priority**
> wtlnd_bord_flashflood4
> wtlnd_hunt_leafbaresnowstorm2
> wtlnd_hunt_leafbaresnowstorm3

**Comment by Clumxy** [comment]
I can help with this if you like!

**Comment by keyraven** [comment]
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_leafbaresnowstorm2')
> ('wetlands\\hunting\\hunting_wetlands.json', 'wtlnd_hunt_leafbaresnowstorm3')
> ('wetlands\\border\\border_wetlands.json', 'wtlnd_bord_flashflood4')
> ('plains\\hunting\\leaf-bare.json', 'pln_hunt_leaf-bare_mice_appshowoff1')

Full list of patrols with this issue
