### ISSUE TITLE
Cat lost since kithood returned with no experience at all

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#1799]
A cat was lost at 4 moons and came back at 20 with 0 experience.

![image](https://github.com/Thlumyn/clangen/assets/77426212/933a8a09-4076-49d1-ab93-aa8f1f7a2b7d)

![image](https://github.com/Thlumyn/clangen/assets/77426212/667088e2-7812-4353-a76a-b250dfde48af)

**Comment by keyraven** [comment]
This is currently intended behavior. Cats do not gain experience while outside the clan.  One day, that may be changed, but at the moment, this is not a bug.

**Comment by ZrainydayXXX** [comment]
Ah. Okay :)
