### ISSUE TITLE
Inconsistent capitalization of Mothman

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1800]
![IMG_3387](https://github.com/Thlumyn/clangen/assets/126827015/ca2d218c-5f01-4a1f-aa7c-644b9d652781)
![IMG_3386](https://github.com/Thlumyn/clangen/assets/126827015/fcf4f6a2-4fb4-4a08-91c1-10f833520fb9)

the first screenshot comes from proceeding on mtn_bord_mothman1 when sending a single cat on a mountainous border patrol who is then eaten by the Mothman.

the second screenshot comes from proceeding on mtn_hunt_mothman1 when sending a single cat on a mountainous hunting patrol who is then eaten by the Mothman.

The spelling of Mothman is inconsistent as shown above

**Comment by keyraven** [comment]
Updated Title for Accuracy. Thanks for reporting!

**Comment by keyraven** [comment]
Moved to master spelling and grammar post.
