### ISSUE TITLE
Poly cule kit listing a bio parent as adoptive

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#1801]
![image](https://github.com/Thlumyn/clangen/assets/77426212/f336ef1c-a115-4054-b5d2-f3511721ba4e)

![image](https://github.com/Thlumyn/clangen/assets/77426212/d5cc6e52-20bf-4839-9cb3-30619e174800)

![image](https://github.com/Thlumyn/clangen/assets/77426212/ff33f2a3-def7-4777-8ecc-e82336ddf65f)

Antstar is his biological parent and Batflight is the adoptive figure. The same does not happen with Oceanpetal, the other bio cat.

**Comment by keyraven** [comment]
I am unsure where the issue is here. I don't see any place where Antstar is listed as adoptive.

**Comment by ZrainydayXXX** [comment]
Did I misinterpret it? The top screenshot to me says it lists Volepaw as adopted to Antstar. Maybe I misinterpreted it but it says "Volepaw, adoptive child of Antstar, Oceanpetal and Batflight"
I read that as it saying Volepaw was adoptive to Antstar cause the same text doesn't show on Oceanpetal and in Volepaw's tree Ocean and Ant are both bio

Edit: On Ocean's side
![image](https://github.com/Thlumyn/clangen/assets/77426212/f9b10928-6db1-46cf-9296-6e5ca9b82551)

**Comment by keyraven** [comment]
Oh, I see the issue now. The fact that it's not the same as the other parent does indicate some issue here. I will revise the label.

**Comment by Lixxis** [comment]
I tried to recreate the bug, new polyamory kids don't have that problem. I also tried to adapt the files to get this error, but this also didn't work.

**Comment by ZrainydayXXX** [comment]
Oh. That's weird then. I'm unsure of how I got it either. Maybe it was just chance or maybe I did something wrong, idk.
