### ISSUE TITLE
Two typos in gathering patrol text

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1802]
![image](https://github.com/Thlumyn/clangen/assets/126827015/85904fb6-9cfb-486e-9666-e265cb7b6453)
send a single-cat gathering patrol out till you get PATROL ID: gen_med_scary_ghost1 | SUCCESS: True, and then proceed.
"seems to flicker in an out of few" should be "seems to flicker in and out of view"

**Comment by selkirks** [comment]
![image](https://github.com/Thlumyn/clangen/assets/126827015/326820b3-94bc-4b64-ad03-d0a26714016c)
also occurs on PATROL ID: gen_hunt_scary_ghost1 | SUCCESS: True

**Comment by keyraven** [comment]
Moved to master spelling/grammar issue
