### ISSUE TITLE
Typo in gathering patrol text

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1803]
![image](https://github.com/Thlumyn/clangen/assets/126827015/d9eb45b6-1c01-4e66-bab5-aeb4ae379e4d)
Send out a single-cat gathering patrol till you get PATROL ID: gen_med_scary_ghost1 | SUCCESS: False. proceed

"makes they fur stand on end" should be "makes their fur stand on end"

**Comment by keyraven** [comment]
Moved to master thread
