### ISSUE TITLE
Were/was grammar issue in history

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1804]
![image](https://github.com/Thlumyn/clangen/assets/126827015/352e1cc7-dca0-4786-a782-67bfc3c881a1)
Send out a lone cat on a hunting patrol in the mountains till you get PATROL ID: mtn_hunt_mothman1 | SUCCESS: False. proceed. if your cat dies from the mothman eating them, check the cat's history.

It should be "name was taken" instead of "name were taken"

**Comment by selkirks** [comment]
![image](https://github.com/Thlumyn/clangen/assets/126827015/dad06d88-101f-4c4f-9d5e-099ba07a8f34)
also happens when a cat dies of poison upon the failure of bch_hunt_bishopfish1

**Comment by ZtheCorgi** [comment]
ah. i also fixed this in my PR along with a bunch of other issues
https://github.com/Thlumyn/clangen/pull/1827
