### ISSUE TITLE
A period after a question mark in patrol text

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1805]
![image](https://github.com/Thlumyn/clangen/assets/126827015/794cd63a-5f9e-4470-b094-0e49e4b533c4)
send out a single apprentice patrol in the plains. if you get the one about exploring a tunnel, click do not proceed.
i wasnt able to get the patrol id since i clicked do not proceed
![image](https://github.com/Thlumyn/clangen/assets/126827015/a04a05f1-37bb-4b40-8955-005f5ae34d8f)

**Comment by keyraven** [comment]
Moved to master thread
