### ISSUE TITLE
sc and error2 in patrol

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1811]
![image](https://github.com/Thlumyn/clangen/assets/126827015/3da9214a-2160-4bca-a032-15a94aabed48)

send out 2 cats on a border patrol. proceed once you get PATROL ID: gen_border_pumpkineyes | SUCCESS: True

scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/subject
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/subject
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: VERB/s_c/scratch/scratches
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: VERB/s_c/scratch/scratches

**Comment by keyraven** [comment]
Marking this as duplicate. This is the same patrol_id, with mostly the same issue, as reported here: https://github.com/Thlumyn/clangen/issues/1809
