### ISSUE TITLE
sc and error2 in patrol outcome

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1812]
![image](https://github.com/Thlumyn/clangen/assets/126827015/99b0acc7-d6f6-410e-a731-5acb3e211fb6)
send out a 2 cat border patrol with one cat having a skill of either kittypet or loner knowledge and proceed on PATROL ID: gen_border_pumpkineyes | SUCCESS: True
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/subject/CAP
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/subject/CAP
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: VERB/s_c/explain/explains
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: VERB/s_c/explain/explains

**Comment by keyraven** [comment]
Marking as duplicate. This is the same patrol_id, and mostly the same issue, as reported here: https://github.com/Thlumyn/clangen/issues/1809
