### ISSUE TITLE
inconsistent capitalization of jersey devil

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1813]
![image](https://github.com/Thlumyn/clangen/assets/126827015/71ceffa4-0ba7-4c14-adf4-62268ee9957d)

send out a single cat border patrol in the mountains and proceed on PATROL ID: mtn_bord_jerseydevil1 | SUCCESS: False

in one instance, as shown above, it is spelt Jersey Devil, but then spelt Jersey devil two other times

**Comment by keyraven** [comment]
Moved to master thread
