### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ghost** [ClanGenOfficial/clangen#1814]
![image](https://github.com/Thlumyn/clangen/assets/112568601/064d91df-3345-4b4d-98c3-bc2a3a93d593)

I think it should be "with black wings and a huge backdrop of hypnotic, glowing red eyes..." 

 -----------------------------------------------------
PATROL START ---------------------------------------------------
Patrol Leader: Ghostsight
Random Cat: Ghostsight
Total Number of Possible Patrols | normal: 9, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Ghostsight']
No Stat Cat Found
---
starting chance: 25 | EX_updated chance: 63
Ghostsight updated chance to 63 | 
PATROL ID: mtn_bord_mothman1 | SUCCESS: False
PATROL END -----------------------------------------------------

**Comment by keyraven** [comment]
Moved to master thread
