### ISSUE TITLE
This life is the first life despite it saying the ceremony is nearly over

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#1819]
![image](https://github.com/Thlumyn/clangen/assets/77426212/db054dfb-33e3-4e73-857a-06f0bd2c8342)

This life says the leadership ceremony is nearly done despite being the first life Thundergale received.

**Comment by keyraven** [comment]
Live-text events are not limited by their order in the ceremony, so this is intended behavior.

**Comment by ZrainydayXXX** [comment]
Oh okay ^^
