### ISSUE TITLE
Medicine patrols give no herbs

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#1824]
**Type:** code
**Summary:** some medicine patrols are tagged with many_herbs but do not have a tag specifying what type of herbs to give. so far i have found that gen_med_group_randomherb2 and mtn_med_rainygathering1 have this error, but there may be more.
**Occurrence:** permanent
**Reproduce:** go on medicine patrols until you get an outcome that seems like a success with a print that says ['many_herbs'] - gave no herbs to give
**Commit #:** 94fe5d27adb4df4b7b826ed60f60c448deff7973

Patrol Leader: Guppy
Random Cat: Lupinebreeze
Total Number of Possible Patrols | normal: 6, romantic: 1 
attempted romance between: Guppy Lupinebreeze
final romance chance: 23

Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Wisteriaspeck']
Found stat cat: Wisteriaspeck

starting chance: 30 | EX_updated chance: 90
Guppy updated chance to 90 | Lupinebreeze updated chance to 100 | Wisteriaspeck updated chance to 110 |
PATROL ID: gen_med_group_randomherb2 | SUCCESS: True
['many_herbs'] - gave no herbs to give

Patrol Leader: Wisteriaspeck
Random Cat: Guppy
Total Number of Possible Patrols | normal: 6, romantic: 1 
not a potential mate or current mate

Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Lupinebreeze']
Found stat cat: Lupinebreeze

starting chance: 30 | EX_updated chance: 90
Wisteriaspeck updated chance to 100 | Lupinebreeze updated chance to 110 | Guppy updated chance to 110 |
PATROL ID: mtn_med_rainygathering1 | SUCCESS: True
['many_herbs'] - gave no herbs to give

**Comment by ZtheCorgi** [comment]
tiri thinks it's also possible the tag is just broken, so that could be it too i suppose

**Comment by ZtheCorgi** [comment]
ok, i managed to get a different outcome on mtn_med_rainygathering1 that gave herbs, it seems to be the stat_cat outcome that's affected. also adding the outcome texts into my poast because i forgor

**Comment by keyraven** [comment]
The tag is working correctly. It won't give herbs on it's own, since it only affects the quantity.  We need to check through and add herb-type tags to all these patrols. I will generate a list of patrol_ids with this issue, and post it here later.

**Comment by ZtheCorgi** [comment]
that's what i thought it was! thanks for the confirmation key, the ID list will be super helpful

**Comment by keyraven** [comment]
Here are the patrols with this issue: 

> ('forest\\med\\any.json', 'fst_med_rainygathering1')
> ('wetlands\\med\\any.json', 'wtlnd_med_lungwort3')
> ('wetlands\\med\\any.json', 'wtlnd_med_lungwort6')
> ('wetlands\\med\\any.json', 'wtlnd_med_lungwort9')
> ('wetlands\\med\\any.json', 'wtlnd_med_lungwort12')
> ('plains\\med\\any.json', 'pln_med_rainygathering1')
> ('mountainous\\med\\any.json', 'mtn_med_rainygathering1')
> ('wetlands\\med\\medcat_wetlands.json', 'wtlnd_med_lungwort3')
> ('wetlands\\med\\medcat_wetlands.json', 'wtlnd_med_lungwort6')
> ('wetlands\\med\\medcat_wetlands.json', 'wtlnd_med_lungwort9')
> ('wetlands\\med\\medcat_wetlands.json', 'wtlnd_med_lungwort12')
> ('desert\\med\\any.json', 'dst_med_lungwort3')
> ('desert\\med\\any.json', 'dst_med_lungwort6')
> ('desert\\med\\any.json', 'dst_med_lungwort9')
> ('general\\medcat.json', 'gen_med_group_randomherb1')
> ('general\\medcat.json', 'gen_med_group_randomherb2')
> ('general\\medcat.json', 'gen_med_appgroup_randomherb1')
> ('general\\medcat.json', 'gen_med_appgroup_randomherb2')
> ('general\\medcat.json', 'gen_med_appgroup_randomherb3')
> ('general\\medcat.json', 'gen_med_appgroup_randomherb4')
> ('general\\medcat.json', 'gen_med_warappmedapp_herbcontest1')
> ('general\\medcat.json', 'gen_med_warappmedapp_herbcontest2')
> ('general\\medcat.json', 'gen_med_friendly_ghost')
> ('general\\medcat.json', 'gen_med_witch_cat')
> ('beach\\med\\any.json', 'bch_med_rainygathering1')

**Comment by ZtheCorgi** [comment]
ty! will get these fixed up in the next few hours

**Comment by ZtheCorgi** [comment]
fixed!
https://github.com/Thlumyn/clangen/pull/1832
