### ISSUE TITLE
says two apprentices come back with plenty of herbs but no such herbs appear

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#1826]
<img width="682" alt="Screenshot 2023-10-25 at 11 58 14 PM" src="https://github.com/Thlumyn/clangen/assets/73655037/80055afc-4fcb-43c3-9fd2-abb346bac24d">

type: code
summary: title says it all. these two are the only two cats in the clan, should that mean anything (challenge runs get you to weird places lol)
grade: non-vital
occurence: unknown (I assume permanent for this patrol?)
I don't have patrol id thanks to playing on nightly, but it's a two apprentice herb patrol (one med apprentice, one warrior apprentice) in the beach biome. Starting prompt was something along the lines of "Darkpaw challenges Mousepaw to an herb gathering contest"
commit: c6f02c5e

**Comment by keyraven** [comment]
This is the same issue as https://github.com/Thlumyn/clangen/issues/1824
