### ISSUE TITLE
No herbs gathered on this medicine patrol's success outcome

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#1831]
![image](https://github.com/Thlumyn/clangen/assets/77426212/55e9fd66-3db7-4347-82df-9498615288b4)
Summary: This patrol outcome should give herbs but doesn't
Type: Code
Grade: Non-vital
Occurrence: Permanent for this outcome
Reproduce: Send your medicine cat out on solo patrols until you get this
Patrol ID plus prints:
PATROL START ---------------------------------------------------
Patrol Leader: Dovetalon
Random Cat: Dovetalon
Total Number of Possible Patrols | normal: 15, romantic: 0 
starting chance: 50 | EX_updated chance: 84
Dovetalon updated chance to 84 | 
PATROL ID: gen_med_friendly_ghost | SUCCESS: True
['many_herbs'] - gave no herbs to give
PATROL END -----------------------------------------------------
Commit #: 98346f89f8cda052b3d2109a14e1886acbcfd583

**Comment by keyraven** [comment]
Same issue as here: https://github.com/Thlumyn/clangen/issues/1824 
If you wish, you can add this issue as a comment in that thread.
