### ISSUE TITLE
Rossette on sprite_senior 12 (grey bengal) is colored in as black, instead of dark blue-gray

### ISSUE THREAD

**Issue by yippeecore** [ClanGenOfficial/clangen#1837]
**Type:** visual/sprite
**Summary:** there is a rosette that is filled in as black on the ``sprite_senior: 12`` pose, when this isn't present in the rest of the "GREY"/"Bengal" sprites
**Grade:** non-vital/unimportant
**Occurrence:** permanent
**Reproduce:** have an elder with the following colors ↴
"pelt_name": "Bengal",
        "pelt_color": "GREY",
        "pelt_length": "short",
        "sprite_senior": 12,
**Commit #:** first reported on bd34b4fad0e493c40a4a963862c1daf44ba1ebec , still present in 26ab17cfec51a4932ca4146ef0c61cd95146c6bc (most recent)
![image](https://github.com/Thlumyn/clangen/assets/126303170/37b6afad-b649-413c-8b6b-9baff7def48f)
![image](https://github.com/Thlumyn/clangen/assets/126303170/7e031437-f05b-4b1a-b364-0ccad6b46646)

**Comment by LaurelWillow** [comment]
fixed in PR- #1891 
apologies if I've done something wrong with this- I'm not used to this. I think it should be fine though.
