### ISSUE TITLE
Adding an adoptive parent will sometimes add that adoptive parent to the cat's siblings

### ISSUE THREAD

**Issue by keyraven** [ClanGenOfficial/clangen#1839]
Sometimes, but not always, adding an adoptive parent to a cat will also set the adoptive parent of their siblings.  It seems to occur when the new adoptive parent is also a mate of one or both parents. However, even with those conditions, the bug is not guaranteed to occur.  

Although I can replicate this bug, it's not always reliable.

**Comment by ZtheCorgi** [comment]
maybe related? i often will un-set adoptive parents of affair litters that are supposed to be secret, and un-setting the adoptive parent for one cat always un-sets it for their littermates as well

**Comment by ZtheCorgi** [comment]
ie cat1 and cat2 are mates, and cat1 impregnates cat3 who secretly bears their litter. then i will un-set cat2 as the adoptive parent of one kit, which also un-sets them as the adoptive parent of any littermates

**Comment by Thlumyn** [comment]
Closing as unable to replicate.
