### ISSUE TITLE
some halloween patrol outcomes are missing art

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#1845]
notably, the lion kittypet and the hostile ghost med cat patrol seem to be missing outcome art (and the hostile ghost med is probably missing art altogether?). i don't have exact IDs as i discovered these in the screenshots channel. 
![Screenshot_20231028_165913_Discord](https://github.com/Thlumyn/clangen/assets/117624277/007fba12-ab1b-42b1-8948-228c2a80ea9d)
![Screenshot_20231027_183404_Discord](https://github.com/Thlumyn/clangen/assets/117624277/e39efb72-00cd-4e35-bf5c-d0570d5c4ba9)

**Comment by archanyhm** [comment]
What's the status here? Has this been done yet and if not, is this still a priority?

**Comment by ghost** [comment]
There is no art assigned, but I think it was meant to have Scaryghost_intro as the assigned art. If someone else can confirm if this is the art meant for it?

**Comment by scribblecrumb** [comment]
Closing as stale
