### ISSUE TITLE
Game crashes after pairing a medicine cat with another cat (apprentice).

### ISSUE THREAD

**Issue by AndreaCZe** [ClanGenOfficial/clangen#1846]
**Type**: Code
**Summary**:  expanded mode - making the medicine cat mates with another cat (apprentice) broke the game.
**Grade**: Game-breaking
**Occurrence**: Rare
**Reproduce**: have a medicine cat become mates with an apprentice.
**Commit #**: 2dc59448

![image](https://github.com/Thlumyn/clangen/assets/124001097/caa1464b-2995-4962-bff7-7c4bcad84e8d)
![image](https://github.com/Thlumyn/clangen/assets/124001097/ee1cd468-b36a-4d7f-9888-ee59343dcffa)

**Comment by Lixxis** [comment]
Do you still have the clan as it was? If not, it's not a problem, but it would help.
The both cats might not be the reason for the game-break, it might be related to other cats.

**Comment by AndreaCZe** [comment]
Not anymore sorry. Tho, the apprentice did have a sibling who died on that moon and the game did glitch only with her (forgot completely about that little one 😅).
