### ISSUE TITLE
Known murderer is titled as unknown in the history tab

### ISSUE THREAD

**Issue by TABEE002** [ClanGenOfficial/clangen#1851]
![image](https://github.com/Thlumyn/clangen/assets/110104891/9de656b9-045a-42c0-8b82-bf91492d1044)
![image](https://github.com/Thlumyn/clangen/assets/110104891/3b48bbd2-1e4d-4382-b405-44cc6699874a)

Type: Code
Summary: Expanded mode - a cat murdered another cat, while the event tab revealed the murder to be Fallowlamb, the histoy tab named it an unknown killer
Grade: Minor
Occurrence: rare
Reproduce: have a cat murder a clanmate and get the message above. then check the history tab

**Comment by Lixxis** [comment]
I looked into it. The history text is saying this because the murder didn't confess to anyone in the clan. Therefore, the murderer in the text is unknown. This happens also in other events, where the murderer is mentioned by name.
