### ISSUE TITLE
Cat gets multiple conditions from patrol failure, only one is listed upon proceed

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#1856]
**Type:** code
**Summary:** my medicine cat got shivering and frostbite from a patrol failure, but the text that said what conditions they got after pressing proceed only said they got shivering. i don't think this is a tagging issue as it did give them both conditions, it's probably to do with the code that displays conditions cats got on failing a patrol. basically, yellowflash got: shivering showed up, but it didnt say yellowflash got: frostbite. didnt get a screenshot unfortunately as i didn't realize it was a bug until i saw yellowflash was out of commission the next moon
**Grade:** non-vital
**Occurrence:** permanent
**Reproduce:** uh - check cats that get conditions from patrols to see whether they got anything else that wasn't mentioned?
**Commit:** f63486426da8d4286fa2e0ca5c6fef7b5062dbb5
**Patrol ID and outcome print:**

Patrol Leader: Yellowflash
Random Cat: Yellowflash
Total Number of Possible Patrols | normal: 13, romantic: 0 

Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Yellowflash']
Found stat cat: Yellowflash

starting chance: 40 | EX_updated chance: 81
Yellowflash updated chance to 91 |
PATROL ID: fst_med_gatheringdandelion_leaf-bare1 | SUCCESS: False

**Comment by ZtheCorgi** [comment]
![image](https://github.com/Thlumyn/clangen/assets/117624277/66f70e3f-0f6e-4636-b0f9-e540b5cb8112)
yellowflash's conditions btw, to show theyve had both shivering and frostbite for the same amount of time

**Comment by Lixxis** [comment]
It was an issue with the "also got" condition in get_injury function in cat class. Not sure why that function has the possibility to add more conditions to the cat than expected when calling that function.
