### ISSUE TITLE
"Pair has already been mediated" but they were not mediated this moon

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#1858]
**Type:** code
**Summary:** i sabotaged cats with the IDs 76 and 75. i went to mediate one of them with a cat with the ID 7, and now the game claims that she has already been mediated with 76, 75, and 5. i can't test with cat 6 as she is deceased, but i imagine the same issue would happen there.
**Grade:** regular
**Occurrence:** permanent (when conditions are met)
**Reproduce:** i imagine by having cats with multiple digit IDs mediate with each other, then try to mediate them with a cat with a single digit ID that shares numbers of their IDs?
**Commit:** f63486426da8d4286fa2e0ca5c6fef7b5062dbb5

**Comment by keyraven** [comment]
I am having issue replicating this issue. @ZtheCorgi , do you have the save where this issue occured?

**Comment by ZtheCorgi** [comment]
@keyraven yep, i do. it's still happening too, i just updated my game and checked. if you mediate woodstar with anyone other than chanterelle and then try to mediate chanterelle with him, it should claim that they have already been mediated.
[Forest.zip](https://github.com/ClanGenOfficial/clangen/files/13246932/Forest.zip)
[Forestclan.json](https://github.com/ClanGenOfficial/clangen/files/13246934/Forestclan.json)

**Comment by keyraven** [comment]
@ZtheCorgi , Thanks for the save information! I am still having trouble replicating the issue. I mediated Woodstar with Chanterelle, but everything seems to be behaving as expected. From inspecting the code, and I can't immediately identify any issue.  Could someone else give this a try?

**Comment by ZtheCorgi** [comment]
to be clear, order of operations is: mediate woodstar with anyone. i usually use chivefur because idk
then try to mediate woodstar with chanterelle

**Comment by TABEE002** [comment]
I got it to work by sabotaging woodstar and chivefur and then switching to chanterelle
https://youtu.be/dmTu8PLMsE8 (Here is video footage of it

**Comment by keyraven** [comment]
> I got it to work by sabotaging woodstar and chivefur and then switching to chanterelle https://youtu.be/dmTu8PLMsE8 (Here is video footage of it

Ah! Thanks so much, that helped me come to realization that this was an issue just related to sabotage, not mediate!

**Comment by TABEE002** [comment]
glad I could help!
