### ISSUE TITLE
Cat does not gain grief condition or have grief thought despite high relationship

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#1862]
Type: Code
 Summary:  Fiercewhisker and Flutterlaurel are mates. Fierce had a kit with Flutter, and the same moon, Flutter died, but Fierce didn't get the grief stricken condition or have any grief thought, despite having full platonic and romantic love bars with him. I don't know if this is really a bug, but it definitely seems wrong. Only one cat had a grief thought about Flutter- his grown daughter Heathershell, with about four bars of platonic like- and that one seems to have worked as normal. 
Grade:  Regular
Occurrence: Rare
Reproduce: Make cats mates, get them to full platonic/romantic like, and then have one die? I really don't know what's going on
Commit: 32d10fd9

<img width="382" alt="Screenshot 2023-11-02 at 10 56 13 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/ea3e0929-361e-4e9a-9fa4-b890c94227fb">

<img width="487" alt="Screenshot 2023-11-02 at 10 57 16 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/99dc4325-f84a-49d4-aee2-d2d7f9a43333">

<img width="690" alt="Screenshot 2023-11-02 at 10 58 43 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/1b65cc43-4552-42fe-ab8b-da1375a24b07">

**Comment by keyraven** [comment]
Grief is not deterministic, and there is some level of chance with both grief-thought and grief-condition. Even cats with maxxed out relationship bars are not guaranteed to get the grief condition or be assigned a grief thought.   The only exception is direct family, who will always get the grief-condition or grief-thought if they meet relationship requirements.
