### ISSUE TITLE
Other Clan border patrol ends with no patrol outcome result attached, when it should've said that relations stayed neutral

### ISSUE THREAD

**Issue by yippeecore** [ClanGenOfficial/clangen#1886]
**Type:** code, text
**Summary:** just what the title says on the tin, there is no patrol outcome text on this patrol
**Grade:** non-vital/unimportant
**Occurrence:** permanent for this outcome
**Reproduce:** proceed on the following border patrol
**Patrol ID + Outcome Print (if applicable):**
PATROL START ---------------------------------------------------
PATROL ID: gen_bord_otherclan3 | SUCCESS: True
PATROL END -----------------------------------------------------
**Commit #:** c2ff45a6fd11c1d19acbd9397c069ea5a027c0d2
![image](https://github.com/ClanGenOfficial/clangen/assets/126303170/2bbe1a20-bdd8-4766-bd63-976569621c9c)

**Comment by yippeecore** [comment]
also noticed the same issue occur on another other clan border patrol !

**Patrol ID + Outcome Print (if applicable):** gen_bord_otherclan_allies3 | SUCCESS: True
**Commit #:** c2ff45a6fd11c1d19acbd9397c069ea5a027c0d2
![image](https://github.com/ClanGenOfficial/clangen/assets/126303170/3cd9bae7-7af8-44bd-a021-a6706661da8d)

**Comment by yippeecore** [comment]
and yet another empty result other clan border patrol

**Patrol ID + Outcome Print (if applicable):** gen_bord_otherclan_allies3 | SUCCESS: True
Commit #: c2ff45a6fd11c1d19acbd9397c069ea5a027c0d2
![image](https://github.com/ClanGenOfficial/clangen/assets/126303170/e5948987-6d05-4334-8771-32c428a68e8c)

**Comment by Thlumyn** [comment]
Closing as we don't have plans to add that text to these right now
