### ISSUE TITLE
Occasional crash when pressing the patrol add buttons

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#1887]
Type: Code
Summary: When pressing the add random cat buttons, there is a small chance for it to crash. This can occur both with and without the ability to add medicine cats randomly turned on.
Grade: Game-breaking
Occurrence: Almost-never (Has happened to me twice seemingly quite randomly)
Reproduce: Outside of pressing the + cats buttons, I'm not too sure. It seems to only happen when there's only the final cats left to select, however. But other than that it's quite random.
Commit #: The two I managed to record were in Tiri's testing branch but they told me to report it as a dev issue as it's unrelated to the added content
Prints:
Traceback (most recent call last):
  File "C:\Users\stati\Downloads\clangen-nonsense-10_things_I_hate_about_you33\clangen-nonsense-10_things_I_hate_about_you\main.py", line 318, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\stati\Downloads\clangen-nonsense-10_things_I_hate_about_you33\clangen-nonsense-10_things_I_hate_about_you\scripts\screens\PatrolScreen.py", line 58, in handle_event
    self.handle_choose_cats_events(event)
  File "C:\Users\stati\Downloads\clangen-nonsense-10_things_I_hate_about_you33\clangen-nonsense-10_things_I_hate_about_you\scripts\screens\PatrolScreen.py", line 96, in handle_choose_cats_events
    self.selected_cat = choice(able_no_med)
  File "C:\Users\stati\Downloads\Thonny\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]

**Comment by Lixxis** [comment]
Do you still have the Clan?
I tried for 30 minutes to recreate that bug, but I couldn't. I also see no possible reason why it is happening. 

The error is that the able cats to patrol are 0, but then the button to click is disabled. There has to be at least one cat in the able cats list to press it. I also tried different combinations of button clicks / thought of different ways to be able to click that button, even there are no able cats left. 

I can fix that bug by checking, but we then don't know what the reason was

**Comment by ZrainydayXXX** [comment]
I believe I still have the clan somewhere. If it helps, my computer's touch pad is very sensitive with clicking and sometimes double clicks when I only mean to click once. Maybe that happened before it could become disabled? I'm not really sure. Do you want me to send the clan file?

**Comment by Lixxis** [comment]
Yeah, double click might have triggered that; otherwise I can't see why. With this information, I think I don't need your Clan anymore, but thanks anyway.
