### ISSUE TITLE
Bio-father listed as "not blood related" when the bio-mother is mates with bio-fathers (older) child

### ISSUE THREAD

**Issue by MathKangaroo** [ClanGenOfficial/clangen#1900]
this happened on lifegen but it's not related to the features of the mod:

My mc(cherryheart) has 2 mates(dayscreech and roachstone)
One of those mates just had kits with my mc's bio father(nightberry)
In the family tree, it says nightberry is not bloodrelated to the kits. However, Roachstone is labled as both adoptive and blood related to the kits.

**Comment by keyraven** [comment]
Please attempt to replicate any LifeGen bugs in base ClanGen before reporting them as ClanGen bugs, especially those that affect the "main character".  We don't have any way to confirm that LifeGen's modifications aren't causing a particular issue.  

For this particular issue, I was able to replicate the bug, so I will keep this issue open.
