### ISSUE TITLE
Leader loses special suffix when getting lost on patrol

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#1904]
Type:  Code/text
Summary: Oddstar is referred to as Oddlight (her warrior name) on patrol when she becomes lost
 Grade:  Non-vital
Occurrence: Unsure
Reproduce: Send your leader on patrols where they can get lost until they get lost- I think. I'm still trying to reproduce this and I'll edit it if I come across something new to add. 
Patrol ID/ Outcome Print: I'm still on a packaged version so I don't have it. All the info I have is the screenshot. But I wouldn't be surprised if this happened every time a leader got lost on patrol. 
Commit: 5b1a3019

<img width="705" alt="Screenshot 2023-11-17 at 10 40 49 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/97c1a8bd-2dda-4a75-9d44-0be0000541fc">

**Comment by Lixxis** [comment]
The patrol text has to be generated before the patrol events are handled (function in line 196) - but I won't do this for now, because it might lead to bigger breaks. Just to be sure, I will leave it as it is.
