### ISSUE TITLE
Retire button does not line up with others

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#1908]
pretty much reposting issue #1889 
This is still occurring despite having been fixed. 

<img width="274" alt="Screenshot 2023-11-19 at 10 47 27 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/8343484a-1f01-4abe-9b24-1744d71c2135">

**Comment by larkgz** [comment]
Because the bug also affects the release, the fix was merged to the release branch first. It should be fixed on dev once #1901 is merged.
