### ISSUE TITLE
Permanent conditions not retained in afterlife?

### ISSUE THREAD

**Issue by VixonyAn** [ClanGenOfficial/clangen#1916]
**Type:** Code
**Summary:** A deaf cat in life, has no conditions on their starclan profile. 
**Grade:** Unimportant
**Occurrence:** Had a deaf cat, who died to a clanmate murdering them, and they no longer have any conditions when I check their profile in starclan. Not sure if this is a bug or an oversight. It would be nice if status conditions remained intact in the afterlife.
Was playing on the previous version that ends in 5

**Comment by Lixxis** [comment]
I couldn't reproduce that error + didn't find a code which removes permanent conditions in the whole code.
If a cat gets a permanent condition, the cat should have that condition also in the afterlife.
