### ISSUE TITLE
Lost apprentice returns as a warrior

### ISSUE THREAD

**Issue by TABEE002** [ClanGenOfficial/clangen#1923]
<img width="569" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/110104891/7c383515-e9a7-474e-9dbc-ea019c43474f">
<img width="397" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/110104891/a398ec36-995b-4054-9cc0-49221cbde10c">
<img width="338" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/110104891/c8abacff-89da-41b4-a4eb-428ceaef8cf4">

type: code
Summary: My apprentice (murkpaw) went missing with 46 xp, when he finally returned, moons later. He was a warrior, despite not having enough xp
grade: unimportant
Reproduce: have an apprentice with high xp get lost, then check their name upon return

**Comment by keyraven** [comment]
This is intended behavior. Becoming a warrior upon returning has slightly different requirements, to account for lack of EX gained while lost. Even under regular conditions, warriors apprentices are automatically made warriors when they turn 25 moons old, no matter their current exp status.

**Comment by TABEE002** [comment]
thank you for telling me, I didn't know
