### ISSUE TITLE
Got this silly little bug!

### ISSUE THREAD

**Issue by pupcake114** [ClanGenOfficial/clangen#1924]
![Screenshot (1275)](https://github.com/ClanGenOfficial/clangen/assets/152097220/02dc7b70-78d4-4305-bead-d1f78b74eb27)

It says to report it so i am:3

**Comment by keyraven** [comment]
Did you edit the save files in any way? This cat has a status of `war`, which should not typically be possible.

**Comment by keyraven** [comment]
Closed - this is likely caused by save-file editing.
