### ISSUE TITLE
'Loner' marked as a 'kittypet'

### ISSUE THREAD

**Issue by pearlwalker** [ClanGenOfficial/clangen#1926]
A loner left their kits in the Clan, but the cat the kittens are shown to be related to (Hornet) is a kittypet. You could interpret this as one parent being a kittypet, the other being a loner, but I'm pretty sure the dead cat is supposed to be the one to have given their kits away.

![bug_'abandoned-kitten'_screenshot1](https://github.com/ClanGenOfficial/clangen/assets/152219481/44298db4-20ad-45ec-8861-ffce79c98ead)
![bug_'abandoned-kitten'_screenshot2](https://github.com/ClanGenOfficial/clangen/assets/152219481/77bead32-0d0a-480a-9cdc-bd0f413ba25f)
![bug_'abandoned-kitten'_screenshot3](https://github.com/ClanGenOfficial/clangen/assets/152219481/22b10a68-54c2-49a0-8669-0c09435d2db1)
![bug_'abandoned-kitten'_screenshot4](https://github.com/ClanGenOfficial/clangen/assets/152219481/e92137df-01bc-4595-8fdb-043f2302a344)

**Comment by keyraven** [comment]
At the moment, this is intended behavior.  If a litter is left to the clan during a moon event, a bio parent is generated randomly to ensure that they are properly tracked as blood related.  Currently, the bio parent generation is unrelated to the event text itself.
