### ISSUE TITLE
Sprite switches between which leg a cat is missing

### ISSUE THREAD

**Issue by pearlwalker** [ClanGenOfficial/clangen#1927]
![bug_'missing-limb-sprite'_screenshot1](https://github.com/ClanGenOfficial/clangen/assets/152219481/c48b864b-6f65-43a1-b78f-52a156db4fc9)
![bug_'missing-limb-sprite'_screenshot2](https://github.com/ClanGenOfficial/clangen/assets/152219481/c0442c34-bf0b-4f7c-92a9-58cc2a1cdd17)
![bug_'missing-limb-sprite'_screenshot3](https://github.com/ClanGenOfficial/clangen/assets/152219481/fe98f889-1b76-4c55-944b-c9c08f63fa9c)

**Comment by Lixxis** [comment]
Depending on the sprite the leg **has to** be removed on different parts. Otherwise, it wouldn't look good, or it is not possible.

**Comment by Thlumyn** [comment]
Closing as not planned
