### ISSUE TITLE
Apprentice returns to camp with warrior-level skills

### ISSUE THREAD

**Issue by pearlwalker** [ClanGenOfficial/clangen#1928]
![bug_'apprentice-skill-upgrade'_screenshot1](https://github.com/ClanGenOfficial/clangen/assets/152219481/68f94505-5eb6-46ba-b44d-c59ed0656bac)
![bug_'apprentice-skill-upgrade'_screenshot2](https://github.com/ClanGenOfficial/clangen/assets/152219481/89f43c8f-cba6-4f9c-bd9d-730c06731b25)

**Comment by Lixxis** [comment]
@keyraven I think this is intended behavoir, but I'm not sure

**Comment by Thlumyn** [comment]
If I remember right, these skills are not necessarily tied to warrior status, so this wouldn't be a bug.
