### ISSUE TITLE
BUG in medicine cat patrol

### ISSUE THREAD

**Issue by Mercury984** [ClanGenOfficial/clangen#1929]
![wha](https://github.com/ClanGenOfficial/clangen/assets/152252889/942c2d89-90f4-4185-bf94-006c7b38f18a)

**Comment by Lixxis** [comment]
**Patrol ID:** gen_med_medwar_natureofstarclan
The outcome also has to be formatted to fit the Pronoun tags

**Comment by Lixxis** [comment]
Was fixed in PR #1933
