### ISSUE TITLE
cats can mate with grandchildren

### ISSUE THREAD

**Issue by DeadByte13** [ClanGenOfficial/clangen#1935]
unsure if it's actually a bug, but figured i'd mention it anyways. If first cousins can be mates is on, grandparents can mate with their grandchildren, regardless of blood relation. if it's intentional, feel free to disregard.

**Comment by DeadByte13** [comment]
Update on this: it seems to switch said grandchildren to no longer be blood related if you do make them mates. Also, only accessible to choose as a mate from the grandparent.

**Comment by keyraven** [comment]
Can you clarify your second comment? In addition, cats should be able to become mates with their great-grandparents and above, since relation tracking only checks for grandparents. Are you referring to great-grandparents (parents of parents of parents) or grandparents (parents of parents)?

**Comment by DeadByte13** [comment]
i'm refering to just grandparents (parents of parents). my above comment is saying that if you make a grandparent and grandchild mates, it seems label them as not blood related when you do that.

**Comment by Lixxis** [comment]
I can't even find the grandparents of a cat to mate them with (not in the list of possible mates).

Did you file, edit the clan?

**Comment by keyraven** [comment]
I am also unable to replicate this issue.  If possible, could you also send the save-file where you experienced this issue, alongside detailed instructions on how to replicate?

**Comment by DeadByte13** [comment]
uh sure, I can try to. sorry, never saw this. you have to make them mates from the grandparent, not the grandchild btw, that's the only way i've gotten it to happen. i'll get the files when i can

**Comment by DeadByte13** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/efe611fe-990b-4d78-aa56-8d5690816760) Grandparent/grandchild as mates, from grandparent's profile
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/7767988f-b217-4817-a0b0-81e724e47edc)
parent of the grandchild, blood related to grandparent
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/bd2c1ca8-3bff-489e-b3ad-728505deb6fb)
proof of being parent
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/926aa55e-ca76-48e4-bea1-38287c3c68f4)
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/21843eae-84e1-470d-adfb-6bcda7b3df2d)
What it looks like from the grandchild's family tree
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/d5ef4af9-4d28-4813-9c37-0533aa5b5191)
![image](https://github.com/ClanGenOfficial/clangen/assets/130618331/fe621538-f3fc-433a-b45c-e0ffb34bf416)
and from the grandparents

Trying to figure out how to attach the save file atm

**Comment by DeadByte13** [comment]
[clan_cats.json](https://github.com/ClanGenOfficial/clangen/files/13600078/clan_cats.json)
[clan_settings.json](https://github.com/ClanGenOfficial/clangen/files/13600079/clan_settings.json)
[events.json](https://github.com/ClanGenOfficial/clangen/files/13600080/events.json)
[herbs.json](https://github.com/ClanGenOfficial/clangen/files/13600081/herbs.json)
[pregnancy.json](https://github.com/ClanGenOfficial/clangen/files/13600082/pregnancy.json)
idk if htis is right or hwat you wanted but here

**Comment by ashii101** [comment]
https://www.wellnessliving.com/knowledge-sharing/article-categories/troubleshooting/
