### ISSUE TITLE
Dead, adult cat stolen as kit still marked as kitten

### ISSUE THREAD

**Issue by SolarSylvilagus** [ClanGenOfficial/clangen#1936]
![83f77003d467a061403a9bfe80cbf65b](https://github.com/ClanGenOfficial/clangen/assets/152554551/4b8bb28d-d5bb-4efe-998e-6ce5003cf21e)
![d381e24b6f2bf868c2fefe9da1f97349](https://github.com/ClanGenOfficial/clangen/assets/152554551/8339a836-d0a4-4d57-8bc9-d9858da826fc)
Immediately upon his death he had a kitten thought, "Doesn't really understand what being in StarClan means" but i was unable to capture that. He's only had thoughts from the general category since then.

**Comment by keyraven** [comment]
This is intended behavior. Cat can not become apprentices when they are lost, and so remain "kits".
