### ISSUE TITLE
Leader lost a life from curiosity; a random kit is part of the event for some reason

### ISSUE THREAD

**Issue by GoldBerryJuice** [ClanGenOfficial/clangen#1939]
The Clan's leader got the "curiosity killed the cat" event. The event gives shortcuts to the profile of the leader and a random kit (it's not the leader's kit, nor is it a kit with unknown origins). Everything else about the event seems to have functioned normally: the leader is alive with one less life, and nothing appears to have changed about the kit.

![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/c59be01d-7a52-4470-8e8b-c34b9b1eb854)
![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/4801794f-9dff-490d-a2fe-28c38d2d1256)
![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/a56b9bfb-72bf-4d8e-ad76-9c46c0f1b992)

[stdout_20231129_235453.log](https://github.com/ClanGenOfficial/clangen/files/13521308/stdout_20231129_235453.log)
[stdout_20231130_145232.log](https://github.com/ClanGenOfficial/clangen/files/13521309/stdout_20231130_145232.log)
[stdout_20231130_212517.log](https://github.com/ClanGenOfficial/clangen/files/13521310/stdout_20231130_212517.log)
[clangen_20231130_212517.log](https://github.com/ClanGenOfficial/clangen/files/13521311/clangen_20231130_212517.log)

**Comment by GoldBerryJuice** [comment]
The same thing almost immediately happened again (I guess Cloudstar didn't learn her lesson), this time with a random warrior who also has no obvious connection to the leader and is also Clanborn (so would not be eligible for the event). 

![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/53e53d85-e195-4ef2-a4ca-930de7df997e)
![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/b7b1b336-e04b-4955-ba0a-8cd8e37bc9e8)
![image](https://github.com/ClanGenOfficial/clangen/assets/152587751/d0a0adb8-3501-4a8d-90f9-de71ad144b47)

[clangen_20231130_212517.log](https://github.com/ClanGenOfficial/clangen/files/13521382/clangen_20231130_212517.log)
[stdout_20231129_235453.log](https://github.com/ClanGenOfficial/clangen/files/13521384/stdout_20231129_235453.log)
[stdout_20231130_145232.log](https://github.com/ClanGenOfficial/clangen/files/13521385/stdout_20231130_145232.log)
[stdout_20231130_212517.log](https://github.com/ClanGenOfficial/clangen/files/13521386/stdout_20231130_212517.log)

**Comment by Thlumyn** [comment]
Looks like the json for this is here:
https://github.com/ClanGenOfficial/clangen/blob/f5c49657307cae438227672e14ab31ee5d32f4bf/resources/dicts/events/death/general/leader.json#L1122

Not sure if it is meant to NOT have the other_cat tag, or when it says somebody found the cooling body that is meant to be the other cat.
