### ISSUE TITLE
Any leader injury in "births and deaths"

### ISSUE THREAD

**Issue by RabidChomp** [ClanGenOfficial/clangen#1944]
Type: UI? im not too sure sorry
Summary:  whenever  the leader gets any injury or illness, it shows up In the births and deaths tab, and the health tab, this also happens when the leader recovers
Grade: Regular
Reproduce: time skip until the leader has a non fatal illness or injury, and timeskip to when the leader recovers without dying.
Commit: 4ef5c692c8179ebf34550b53d51b8bbbe9f76364 
![Screenshot 2023-12-04 201806](https://github.com/ClanGenOfficial/clangen/assets/148391659/6ff52db5-862c-4c31-9e34-497c763c2616)

**Comment by TABEE002** [comment]
I believe issue #1888 also mentions the same issue

**Comment by Lixxis** [comment]
It should be fixed with merge #1943
