### ISSUE TITLE
Clan gen online

### ISSUE THREAD

**Issue by SagesForgiveness** [ClanGenOfficial/clangen#1947]
Whenever I go to play clan gen online, it only shows a black screen. I played for so long and had so much fun until I switched clans and the game crashed. For a day, haven’t been able to play. I’ve tried everything from restarting my phone to getting a software update. Nothing is working. I need tips on how to get it to work again.

**Comment by LaurelWillow** [comment]
hey- this isn't really the best place for tech support issues. I'd recommend joining the discord if you can- 
we have a handful of dedicated tech support channels, and guides to tackling this sort of thing. 

If you can't, I can try my best to help you here.

**Comment by Lixxis** [comment]
The web version is currently on hold because of multiple issues, and it won't change anytime soon.
As @LaurelWillow said, if you want to get help / some tips or tricks to resolve issues, try to go to the tech support channel of our discord server: [Discord Server](https://discord.gg/rnFQqyPZ7K)
