### ISSUE TITLE
Typo in "disaster"

### ISSUE THREAD

**Issue by GloomFernn** [ClanGenOfficial/clangen#1950]
![image](https://github.com/ClanGenOfficial/clangen/assets/153208238/aa24f444-9b91-49d1-a0ac-bb16c2bfd19d)

**Comment by Lixxis** [comment]
For typo issues we have a own "master issue" found [HERE](https://github.com/ClanGenOfficial/clangen/issues/1818)

Next time, it would also help if you provide further information about that cat. E.g. is it a leader, a warrior, how many moons is that cat old, has the cat a condition or is the cat dead. 
This would help to track down the issue faster, if there are more thoughts which are similar, for this I was able to track it down fast.
