### ISSUE TITLE
Medicine cat apprentice caught a mouse in thought

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#1956]
Type:  Text
Summary: Marigoldpaw "caught the biggest mouse ever!" despite being a medicine cat apprentice so not going hunting. She's also sick with whitecough and as such probably shouldn't be going out of camp. Marigoldpaw please calm down. 
She's also the only medcat in the clan right now. I don't think that's what's causing this but I thought I'd mention it. 
 Grade:  Unimportant
Occurrence: Rare
Reproduce: Check a medicine cat apprentice's thoughts until you see this one
Commit: 7a10bb4e

<img width="542" alt="Screenshot 2023-12-09 at 12 57 36 AM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/0596c61a-c21e-43b6-b815-b949994b12b5">

**Comment by Lixxis** [comment]
There is a way bigger issue behind it. 

Currently, thought's can't be differentiated between "cat is healthy" and "cat is ill or injured". A tag is needed, therefore the filtering is not as simple as I assumed before.
