### ISSUE TITLE
Contributions not being shown

### ISSUE THREAD

**Issue by lynxnlog** [ClanGenOfficial/clangen#1958]
**Type:** UI
**Summary:** Irony-Dragon's and Kittenvy's contributions are not shown when hovering over their names.
**Grade:** Unimportant
**Occurrence:** Permanent
**Reproduce:** Check the info menu and hover over Irony-Dragon or Kittenvy
**Patrol ID + Outcome Print (if applicable):** [n/a]
**Commit #:** 7a10bb4ef6ac7fd7feb6cd8dbb9292561838b906

**Comment by keyraven** [comment]
Not a bug. Contribution lists are created by the individual contributors.  If no list was provided, none is shown.
