### ISSUE TITLE
pronoun tagging issue in scar issue

### ISSUE THREAD

**Issue by yippeecore** [ClanGenOfficial/clangen#1959]
**Type:** text & code
**Summary:** found on classic mode, but more than likely to exist on expanded. but when a cat gets scarred on the small dog patrol, the pronouns show up as "error2".
**Grade:** regular, non-vital
**Occurrence:** permanent
**Reproduce:** (play on classic mode for an easier chance of developing scars) - encounter and proceed on the following border patrol with one cat.
**Patrol ID + Outcome Print (if applicable):**

> PATROL START
> Patrol Leader: Gracklemist
> Random Cat: Gracklemist
> Total Number of Possible Patrols | normal: 11, romantic: 0 
> 
> Finding stat cat. Outcome Type: Success = True, Antag = False
> Can Have Stat: []
> POSSIBLE STAT CATS ['Gracklemist']
> No Stat Cat Found
> 
> starting chance: 40 | EX_updated chance: 67
> Gracklemist updated chance to 67 | 
> PATROL ID: gen_bord_smalldog1 | SUCCESS: False
> PATROL END

> scripts.utility - ERROR - utility.py / pronoun_repl / 737 - Failed to find pronoun: PRONOUN/Gracklemist/subject
> Traceback (most recent call last):
>   File "C:\Users\dei\Documents\GitHub\clangen\scripts\utility.py", line 718, in pronoun_repl
>     d = cat_pronouns_dict[inner_details[1]][1]
> KeyError: 'Gracklemist'
> Failed to find pronoun: PRONOUN/Gracklemist/subject
> scripts.utility - ERROR - utility.py / pronoun_repl / 737 - Failed to find pronoun: VERB/Gracklemist/say/says
> Traceback (most recent call last):
>   File "C:\Users\dei\Documents\GitHub\clangen\scripts\utility.py", line 718, in pronoun_repl
>     d = cat_pronouns_dict[inner_details[1]][1]
> KeyError: 'Gracklemist'
> Failed to find pronoun: VERB/Gracklemist/say/says

**Commit #:** e8f7a6439a4f4bfebecc6f764147d0da199c7085

![image](https://github.com/ClanGenOfficial/clangen/assets/126303170/6d794b6c-02e9-4194-8588-f88ab7baa5cf)

**Comment by Lixxis** [comment]
I used the development feature to trigger that specific patrol also to get the outcome, there was no error message when the injury was given (as shown in the issue above)
