### ISSUE TITLE
Moon Event not lining up with Family Tree

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#1966]
I had this litter that I got from a moon event stating that a ChiveClan queen gave my clan their kits and one of my warriors adopted them. When I checked on the family tree though, they had three parents- skycatcher and their mate which was expected, but also Frond who is dead and in the residence place. I believe that is supposed to be the ChiveClan queen, but she has a loner backstory. I am unsure if this is a bug or not.
![2023-12-18 (2)](https://github.com/ClanGenOfficial/clangen/assets/149605071/4dff525e-3689-4c71-91d5-6f822a724617)
![2023-12-18 (3)](https://github.com/ClanGenOfficial/clangen/assets/149605071/313ed6b8-1f38-46ee-9884-681c4da5616e)
![2023-12-18 (4)](https://github.com/ClanGenOfficial/clangen/assets/149605071/9aa032f4-9f03-46cc-b0bb-82e57d3820e8)

**Comment by Lixxis** [comment]
There is no status for other clan cats currently. Therefore, the loner status is used. 
And that all parents are listed is intended, the parents are biological + adopted ones.
