### ISSUE TITLE
able to look into a dead cats relations

### ISSUE THREAD

**Issue by dunno-what-to-name** [ClanGenOfficial/clangen#1971]
when clicking the button that is beside the switch focus and view and clicking on the x button, the switch focus is turned on for the dead cat. is this normal?

![Screenshot (635)](https://github.com/ClanGenOfficial/clangen/assets/154953204/5da12ddd-841c-4293-8060-de278467de11)
switch focus turned off usually

![Screenshot (636)](https://github.com/ClanGenOfficial/clangen/assets/154953204/021e1c9a-2e5b-4216-b219-f2476385638b)
looking into the relation log list (is that what its called?)

![Screenshot (637)](https://github.com/ClanGenOfficial/clangen/assets/154953204/17384bb3-2f97-45ea-b5f2-4cc60635f91f)
switch focus suddenly able to click on

![Screenshot (638)](https://github.com/ClanGenOfficial/clangen/assets/154953204/92c4ba19-f1e3-4a2d-a4e2-072cb7adc705)
no relations inside the dead cat when clicked on

**Comment by Lixxis** [comment]
It shouldn't be possible to switch focus for dead cats in the relationship screen. The relationship information of dead cats are deleted. 
How to fix: if the button "switch focus" is deactivated, the log button should also be deactivated.
