### ISSUE TITLE
apprentice focusing on another apprentice

### ISSUE THREAD

**Issue by loved1ve** [ClanGenOfficial/clangen#1980]
hunting patrol prompt that when you press proceed, there was nothing :3

**Comment by Lixxis** [comment]
Do you have any more information? Patrol ID would be the best, otherwise patrol text or screenshot (season + biome might also help).
We have (roughly estimated) over 800 hunting patrols, therefore it is hard to find one specific one without any information.

**Comment by loved1ve** [comment]
so sorry I didn't think of that at all! if i come across it again i will make sure to check

**Comment by Lixxis** [comment]
Alright, don't worry.
