### ISSUE TITLE
cat sprite bugged

### ISSUE THREAD

**Issue by horuslayer** [ClanGenOfficial/clangen#1983]
scripts.utility - ERROR - utility.py / generate_sprite / 1361 - Failed to load sprite
Traceback (most recent call last):
  File "scripts\utility.py", line 1266, in generate_sprite
KeyError: 'whiteBLAZEMASK6'

i have not edited files at all

**Comment by Lixxis** [comment]
I'm also unable to reproduce that Bug, added a cat with the white mark "BLAZEMASK" which also hat (i assume) the posision 6 which lead to the key 'whiteBLAZEMASK6' but got no KeyError.
