### ISSUE TITLE
Prey System not functioning

### ISSUE THREAD

**Issue by ShardXIIV** [ClanGenOfficial/clangen#1984]
Clearing on the camp view does not function as a button, disabling all the functions that comes with. On top of that hunting patrols do not seem to provide any prey and there is no prey amount owned vs needed displayed on the patrol page. The conditions about prey like malnourished and such do not appear either.

**Comment by Thlumyn** [comment]
Is this happening on classic or expanded mode?

**Comment by ShardXIIV** [comment]
Expanded

**Comment by Lixxis** [comment]
Is the game in the development version? (You can check in the bottom right corner)
![image](https://github.com/ClanGenOfficial/clangen/assets/110975120/4ecbe5f0-2166-4666-b5ce-1d9d27b4069f)

Do you still have that problem? If so, can you send the same screenshot as I have? Then we can check on what commit you are playing and if it is currently an issue.
