### ISSUE TITLE
Crash when proceeding on hunting patrol

### ISSUE THREAD

**Issue by millydamouse** [ClanGenOfficial/clangen#1994]
Type: Crash
Summary: Every time a hunting patrol is sent out, the game crashes. 
Grade: Game-breaking
Occurrence: Permanent
Reproduce: Make a new Clan on the latest development build and attempt to set out a hunting patrol.
Commit #: 558de2b9f865d43325bfa25f0e59ef84a2a73d18
![bug report](https://github.com/ClanGenOfficial/clangen/assets/123026980/bcefa8ff-20f7-46d3-b1ad-2fa5cd982b36)

**Comment by Tiritirimatangi** [comment]
I'm going to say I'm pretty sure this crash is cause by the weights of the balancing hunting patrols being 1, which confuses the hunting filtering code (now that weights actually work). I've pushed the weights up to 20 to fix the crash, but that won't fix the actual code

**Comment by TheGoatCarnival** [comment]
I've run into this issue as well, and it only seems to occur when you send out a patrol of three or more randomly selected cats or send out four or more. If you only send out two cats or manually select up to three, it will proceed as normal.
