### ISSUE TITLE
queen status causing error

### ISSUE THREAD

**Issue by loved1ve** [ClanGenOfficial/clangen#1996]
i was messing around in my save file and changed a cats status from warrior to queen just to experiment. The flavor text for the cat's thoughts said to report as a bug.

**Comment by Lixxis** [comment]
There is no status "queen" in the game, it will only be listed as a queen (e.g. in allegiances) depending on if the cat has kits, which are not apprentices yet.

Bugs should also not be reported when save file editing is involved. There can be multiple issues with file editing, making mistakes (e.g. misspelling or try to add things which aren't available) \info \gen
