### ISSUE TITLE
Leader thinks they are deputy

### ISSUE THREAD

**Issue by Autumnfox96** [ClanGenOfficial/clangen#2001]
**Type:** Code
**Summary:** The bug implies that the leader worries that they are not a good deputy. 
**Grade:** Non-vital
**Occurrence:** Frequent (?)
**Reproduce:** Training Patrol (gen_train_deputydoubt1) with leader in your patrol 

**Patrol ID + Outcome Print (if applicable):**
PATROL START ---------------------------------------------------
Patrol Leader: Cottonstar
Random Cat: Sharprump
Total Number of Possible Patrols | normal: 12, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Shinepaw', 'Blackstripe', 'Scratchstep']
Found stat cat: Shinepaw
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Shinepaw', 'Blackstripe', 'Scratchstep']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Shinepaw', 'Blackstripe', 'Scratchstep']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Shinepaw', 'Blackstripe', 'Scratchstep']
No Stat Cat Found
---
starting chance: 50 | EX_updated chance: 90
Shinepaw updated chance to 100 | Blackstripe updated chance to 100 | Scratchstep updated chance to 100 | Cottonstar updated chance to 100 | Sharprump updated chance to 110 | 
PATROL ID: gen_train_deputydoubt1 | SUCCESS: True
PATROL END -----------------------------------------------------

**Commit #:** df4ffc75f218c9bf95871ef525c333ef05c13709

![1](https://github.com/ClanGenOfficial/clangen/assets/156215439/af7f8010-5bd1-47c4-820b-22866af7d5fc)
![(1)](https://github.com/ClanGenOfficial/clangen/assets/156215439/1993fe08-3f7d-48e0-9493-dffb960011ce)

**Comment by Thlumyn** [comment]
Looks like it's having this issue because it automatically picks the patrol leader as the cat in the text, probably assuming thatll be the deputy but if the leaders there, its not. Maybe making the patrol so that leaders cant be on it might fix this
