### ISSUE TITLE
Apprentice Ceremony Typo (Moon Event Typo) 

### ISSUE THREAD

**Issue by Paradise-song** [ClanGenOfficial/clangen#2044]
![image](https://github.com/ClanGenOfficial/clangen/assets/126375611/452e74da-c184-48d5-a8ef-a77e9eb2edf0)

**Type:** Typo(s)
**Summary:** In the second sentence the first "their" should be capitalised and in the last sentence I would assume "them" is supposed to be "they." 
**Grade:** Minor
**Occurrence:** Permanent
**Reproduce:** Continue skipping moons till you have an apprentice honoured for their faithfulness.  
**Commit:** https://github.com/ClanGenOfficial/clangen/commit/272eac575c0c16cc1f253476183b71d2fef24197

(I assume I report typos here, haven't done this in a while! Sorry if I made a mistake.)

**Comment by TABEE002** [comment]
I believe that this is fine, but they have a master thread: #1818 where most of the typos get reported
