### ISSUE TITLE
condition text cut off

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2055]
**Type: ** text
**Summary:** when a cat's 'recovering from birth' injury gets the 'is infected' line, the text is cut off
**Grade:** Unimportant
**Occurrence:** Permanent
**Reproduce:** have a cat have kits and moon skip till it gets infected
**Commit #:** 14dd5bb1ca77cccb166148c8762814180c740bfc
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/35277571-3297-4f66-90ec-9828e0410736)

**Comment by j-gynn** [comment]
Seems to be fixed in the latest development branch, see below image.
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/5b5434e0-4e1a-40be-8ae7-62ec86961aeb)
Recommend closing issue.
