### ISSUE TITLE
Making Poetry mandatory

### ISSUE THREAD

**Issue by archanyhm** [ClanGenOfficial/clangen#2061]
Hi folks,

ever since I introduced the compatibility fix for macOS 10.13 back when I first joined the team, we've started to rely on external package/environment managers for Python — which eventually ended up including Poetry for virtual environment management.

As of now, we have both a `requirements.txt` and a `pyproject.toml` which _should_  in theory contain the same dependencies, but in practice they go out of sync if one developer forgets about this "constraint". To match our development and testing environments with our build environment, I'm phasing out the `requirements.txt` file and make using Poetry mandatory.

Also see: #2057

**Comment by Thlumyn** [comment]
I like this idea - though you'd probably want to change the readme as well, where it references using requirements.txt to install dependencies, and replace it with information regarding Poetry

**Comment by archanyhm** [comment]
> I like this idea - though you'd probably want to change the readme as well, where it references using requirements.txt to install dependencies, and replace it with information regarding Poetry

@Thlumyn 
Definitely. I wanted to replace that section of the README with more comprehensive and extensive setup instructions anyways, so I think we'd be benefitting off of this either way. Do you have any other thoughts about it?
