### ISSUE TITLE
Cat Listing: Filtering not working properly

### ISSUE THREAD

**Issue by happy413** [ClanGenOfficial/clangen#2066]
Type: Code
Summary: 
- When filtering cats, for example by death, entering a cat's profile, then clicking next or previous cat, the order of the cats is not correct. 
- When clicking the back button in the afterlife, you can be booted back to the living cats screen instead. 
- Living cats can be filtered by death. 

Grade: Regular
Occurrence: Permanent/Frequent. I didn't manage to capture the last two bugs, but they've happened to me a few times.
Reproduce: Filter a group of cats by something other than rank, click a cat's profile, then click previous or next cat. Cats will still be filtered by rank.
Commit: 082ea237d5dd42b2c647ce558b91ad5b7e262c63/ 304d32bae9df8860b8f3465a3ed1a14c46035dde

https://github.com/ClanGenOfficial/clangen/assets/127009701/75f23349-b06e-48f6-8cbc-2a5785808f3f

**Comment by KiraDragoness** [comment]
Looks like after a couple of moonskips the order when clicking next or previous cat corrects itself? Wasn't working properly for me after opening the game and it fixed itself on moonskips.

**Comment by happy413** [comment]
Nope, it's still broken for me after several updates and 100+ moonskips.

**Comment by Lixxis** [comment]
Could not reproduce following mentioned errors:
* When clicking the back button in the afterlife, you can be booted back to the living cats screen instead.
* Living cats can be filtered by death.
