### ISSUE TITLE
gen_train_amentorswisdom missing outcome

### ISSUE THREAD

**Issue by ReigningMonarch** [ClanGenOfficial/clangen#2075]
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/9e24df76-7295-4ef2-8c73-738c80b7b623)
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/14816fb6-1f4e-491a-a93a-2a1ed6ff1305)
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/207848e2-c380-412a-885a-33b7b68b025f)

Patrolling on Lifegen fork when this happened.

**Comment by sedgestripe** [comment]
this is a result of lifegen having more traits than base clangen
patrolling on base clangen shouldn't give this issue since all traits for stat-cats are accounted for i believe
