### ISSUE TITLE
New warrior wishes a cat they didn't know was there for their ceremony

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2088]
Type: Code
Summary: A cat becomes a warrior and during their ceremony, they wish that a dead cat they didn't have any relationship with was there. Their mother died very recently and their father has been dead for a long time, so I guess any of them should be named in the ceremony instead.
Grade: Non-vital
Occurrence: Rare
Reproduce: Have an apprentice with one or both of their parents dead become a warrior and see if this ceremony pops up.
Commit#: 419e74039

![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/0bc8c555-dd49-4064-bc59-951f8d82d46e)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/87f139aa-1fc9-4cc6-93ea-3aca7076930b)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/e463763c-963b-4ad1-a6fb-a569c5773f75)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/818cefc5-8ff9-4563-92f9-910eb1ab8539)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/1e64687f-ac91-472f-98e1-b8a12969ae26)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/018a3713-8fde-4db0-af3e-a12a62c2d938)

**Comment by ZtheCorgi** [comment]
are you sure chamoisspeckle wasn't their mentor at any point? that flavor text is about the cat's dead mentor

**Comment by KiraDragoness** [comment]
Huh, I just checked and looks like the game did something very weird. Whisperdusk's first mentor was Halfshade, who died at the exact same time as Chamoisspeckle (during a border patrol). The game did register Chamoisspeckle as Whisperdusk's mentor but I guess it was immediately changed to the next one.
Looks like a bug still? Just not the one I thought at first.

![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/c63bceb3-20aa-49fd-af22-78f450e2ccec)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/e4d22681-8ce3-44ba-a25a-3e05186369bb)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/b6cb40ec-5e83-4687-a51b-04c1be0c85e9)

**Comment by Lixxis** [comment]
I think this would be more of an enhancement to check which cat should be used to remember while in the warrior ceremony. It is not a real bug, more of a bad coincidence.

**Comment by keyraven** [comment]
Fixing this issue would involve changing the method in which mentors are re-assigned. A cat is assigned a new mentor when their own once is marked as dead. This could be changed, but is likely to break unrelated code.  I don't thing such a re-haul is justified to fix this edge-case.
