### ISSUE TITLE
Injury text is saved in relationship log

### ISSUE THREAD

**Issue by AVeryMuddySparrow** [ClanGenOfficial/clangen#2095]
![Screenshot 2024-02-15 141347](https://github.com/ClanGenOfficial/clangen/assets/160181319/1ddaf1e1-e49f-4ede-ac4e-f75ef5e7572e)
![Screenshot 2024-02-15 141258](https://github.com/ClanGenOfficial/clangen/assets/160181319/f9657cb7-7632-4646-ade2-d301e95ce565)

**Comment by Lixxis** [comment]
To find a possible bug we need more information.

What version are you playing, stable versions clangen (like 10.x, 9.x) or is it the development version (if so what on what commit or a time frame)?
Did it show up in the Event log in the clan screen?
Did you notice anything special between the two involved cats? (were they on a patrol together?)

**Comment by AVeryMuddySparrow** [comment]
Playing latest dev release [0.9.0], the two cats weren't on patrol and the notification for the injury appeared in the health section. I've gotten it to happen multiple times on this save.

**Comment by selkirks** [comment]
replicated this, but with a different injury
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/1a9a7f11-9cf9-41bd-bbed-39e88c1788e3)
commit: 6ecea108392926a7199b437101452bf8aef2e3ff (dev version)
mudbramble got romantic like for briar after succeeding on PATROL ID: bch_med_romance_leaf-fall2 | SUCCESS: True where briar saved mudbramble. i checked mudbramble's relationship log with briar and saw it

**Comment by Lixxis** [comment]
So the text is not from the Patrol, it is from the events/injury/general.json with the injury "torn ear". Going to look deeper into it again.

Edit:
The only reason I currently can find is in "scripts/events_module/condition_events.py" line 237. But I can't see a "other_cat" tag on the events which would trigger the relationship logging.

**Comment by Lixxis** [comment]
> replicated this, but with a different injury ![image](https://private-user-images.githubusercontent.com/126827015/318215427-1a9a7f11-9cf9-41bd-bbed-39e88c1788e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzI2NzUsIm5iZiI6MTcxMzQ3MjM3NSwicGF0aCI6Ii8xMjY4MjcwMTUvMzE4MjE1NDI3LTFhOWE3ZjExLTljZjktNDFiZC1iYmVkLTM5ZTg4YzE3ODhlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQyMDMyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTYzZWMwMWM1ZGJmNmM1NjUyYzc4ZDU2ZTU3ZjExY2NhMmM2YTJjNWNlMGQyMzMwYjI5OTE5NjI3ZGU4MWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wr8P6ccoVfJQFpklFCuOCv-H3m-CFCL3_gWZsqUUfT8) commit: [6ecea10](https://github.com/ClanGenOfficial/clangen/commit/6ecea108392926a7199b437101452bf8aef2e3ff) (dev version) mudbramble got romantic like for briar after succeeding on PATROL ID: bch_med_romance_leaf-fall2 | SUCCESS: True where briar saved mudbramble. i checked mudbramble's relationship log with briar and saw it

Can you look up in our "resources/dicts/events/injury/general/general.json" if there is an event with following text: "m_c accidentally crossed the border on patrol and got {PRONOUN/m_c/poss} ear torn by an enemy warrior."

@selkirks 
and tell me what tags are there? is there a "other_cat" tag?

**Comment by selkirks** [comment]
> > replicated this, but with a different injury ![image](https://private-user-images.githubusercontent.com/126827015/318215427-1a9a7f11-9cf9-41bd-bbed-39e88c1788e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzI2NzUsIm5iZiI6MTcxMzQ3MjM3NSwicGF0aCI6Ii8xMjY4MjcwMTUvMzE4MjE1NDI3LTFhOWE3ZjExLTljZjktNDFiZC1iYmVkLTM5ZTg4YzE3ODhlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQyMDMyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTYzZWMwMWM1ZGJmNmM1NjUyYzc4ZDU2ZTU3ZjExY2NhMmM2YTJjNWNlMGQyMzMwYjI5OTE5NjI3ZGU4MWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wr8P6ccoVfJQFpklFCuOCv-H3m-CFCL3_gWZsqUUfT8) commit: [6ecea10](https://github.com/ClanGenOfficial/clangen/commit/6ecea108392926a7199b437101452bf8aef2e3ff) (dev version) mudbramble got romantic like for briar after succeeding on PATROL ID: bch_med_romance_leaf-fall2 | SUCCESS: True where briar saved mudbramble. i checked mudbramble's relationship log with briar and saw it
> 
> Can you look up in our "resources/dicts/events/injury/general/general.json" if there is an event with following text: "m_c accidentally crossed the border on patrol and got {PRONOUN/m_c/poss} ear torn by an enemy warrior."
> 
> @selkirks and tell me what tags are there? is there a "other_cat" tag?

there is an event! tags are as following:
"Newleaf",
            "Greenleaf",
            "Leaf-fall",
            "Leaf-bare",
            "scar",
            "LEFTEAR"
