### ISSUE TITLE
mediation screen doesn't respect age gap

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2096]
**type:** code
**summary:** despite checking is_potential_mate, which should use the age gap specified in game_config, mediation still allows cats who are too far apart in age to gain romantic like under some circumstances
**occurrence:** rare
**grade:** non-vital
**reproduce:** i've been attempting to do so without much success, so this may be difficult without some modification to the mediation code to add prints and/or make it guaranteed for the cats to gain romantic interest if able. i have the age gap set to 36 moons and noticed that cats with a 37 moon age gap were allowed to gain romantic like--but it was close enough that i kinda brushed it off. then i had 2 cats with a 40-moon age gap gain romantic like through mediation, and a 45-moon age gap...
the 37 moon and 40 moon age gaps were with cat1 being an adult and cat2 being a senior adult, i believe. the 45 moon age gap was between 2 seniors, but i dont remember whether the younger or older was cat1 ;; i will comment with more information if/when it happens again
**commit #:** b663040697830a01d2ac8539e8510a4bb3a40492

**Comment by Lixxis** [comment]
Sidenote: The moon gap should only trigger when the cats are in a different age groups (eg. young adult + adult, adult + senior adult, ....) If in the same age categories the age doesn't matter

**Comment by ZtheCorgi** [comment]
apparently this is intentional for now and just what having override_same_age_gap set to false does? i thought it was the exact opposite and setting it to true would override the age gap, to be quite honest.

 i would like to talk about either changing override_same_age_gap to be true by default (could potentially be done now?), or adding an official toggle to the game to let players actually turn off the same age group override on romantic like (would need to be done after feature freeze).

it may be best for me to make a separate issue about this since it's now a question of making a change rather than fixing a bug, though.
