### ISSUE TITLE
Border file inside of forest border patrols

### ISSUE THREAD

**Issue by DeadGirlRisen** [ClanGenOfficial/clangen#2097]
dicts\patrols\forest\border

When checking inside of the forest border patrols, there is an extra border file where their shouldn't be.

![image](https://github.com/ClanGenOfficial/clangen/assets/82120509/e2739e68-5740-46cb-9482-a3c8bf391ba6)

**Comment by DeadGirlRisen** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/82120509/62f6ef76-6460-48cc-b05f-7089a2e23808)
Another messed up version is the wetlands medicine file, it has a medcat_wetlands file inside of it.

**Comment by Lixxis** [comment]
Gonna fix this after the next release, because new patrols might lead to bugs.
