### ISSUE TITLE
Deleting the facets & reopening the game does not create a new facets line 

### ISSUE THREAD

**Issue by AVeryMuddySparrow** [ClanGenOfficial/clangen#2099]
![image](https://github.com/ClanGenOfficial/clangen/assets/160181319/4759909f-476f-402a-a1e3-2a6bd039f44c)
![image](https://github.com/ClanGenOfficial/clangen/assets/160181319/3115109f-25e8-4764-b8d9-0bff2aebc3ce)
![image](https://github.com/ClanGenOfficial/clangen/assets/160181319/8c21a546-04b0-49f1-8c48-3b3f938d8754)

**Comment by ZtheCorgi** [comment]
this should have been fixed as schema was removed, please make sure your game is up to date

**Comment by Lixxis** [comment]
As zabe said, this error should no longer occur.
