### ISSUE TITLE
Inconsistent reason of death

### ISSUE THREAD

**Issue by JaytheRat** [ClanGenOfficial/clangen#2109]
I had an Apprentice die for a broken bone, it was infected last moon (it states so on the events tab)

But on the history section (the one that fills itself in with important dates and events) It says they died on patrol.

Probably just a tiny fix.

I'm using v0.10.6
Attached are the conflicting messages.

![20240222_164543](https://github.com/ClanGenOfficial/clangen/assets/160901193/faf0ba90-4129-4dc4-a7ae-f8a5ed240b6e)

![20240222_164601](https://github.com/ClanGenOfficial/clangen/assets/160901193/7c28875d-b524-4faf-bf76-01ab39f7bcff)

**Comment by Lixxis** [comment]
Do you remember how the apprentice got the broken bone? This death text is a default one, if none was pre-decided when the cat gets the injury.

**Comment by keyraven** [comment]
This issue is stale, and will be closed. This is likely to be intended behavior.
