### ISSUE TITLE
Sick Sprites in Starclan

### ISSUE THREAD

**Issue by izzyphobic** [ClanGenOfficial/clangen#2111]
A majority of my dead cats (Starclan and the Dark Forest) had an issue where they presented as sick with the injuries/illnesses they died with. For example, Lightfawn died in childbirth and had the pregnant condition when I opened her tab. There was a variety of ailments, including redcough, torn pelts, claw wounds, ect. The ones without sick sprites still had minor injuries present. 

It would not fix itself upon moonskip, but everything returned to normal once I closed and reopened the game. Unsure what triggered it because I don't know how long it was present before I checked the dead.

![image](https://github.com/ClanGenOfficial/clangen/assets/123095928/bd34101f-1009-461a-bd57-b3f6c29a4a08)

**Comment by keyraven** [comment]
This issue is stale, and marked "unable to replicate", so it will be closed.
