### ISSUE TITLE
Cause of death not appearing properly

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2119]
Type: Code?
Summary: A cat died on this patrol, but instead of explaining what happened, it just showed "Tinypaw died on patrol." when viewing history.
Grade: Non-vital
Occurrence: Rare, I believe?
Reproduce: Herb patrol in the winter. I was on the beach with two cats, one adult medicine cat and one apprentice. I don't know which parts are necessary beyond herb patrol and winter.

Patrol ID + Outcome Print (if applicable):
PATROL START ---------------------------------------------------
Patrol Leader: Blossombat
Random Cat: Tinypaw
Total Number of Possible Patrols | normal: 18, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: ['adult']
POSSIBLE STAT CATS ['Blossombat']
No Stat Cat Found
---
starting chance: 30 | EX_updated chance: 63
Tinypaw updated chance to 63 | Blossombat updated chance to 63 | 
PATROL ID: bch_med_gatheringdaisy_leaf-bare2 | SUCCESS: False
PATROL END -----------------------------------------------------

Commit #: 1d264a1b14908ceeb9db64e6d766aa4385488870

**Comment by keyraven** [comment]
This occurs when a patrol does not have a special death message.  It's not a bug, but it might be good to add a special death message here.
