### ISSUE TITLE
Different patrol gave backstory that doesn't fit

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2122]
Type: Code?
Summary: Patrol gave out a backstory that doesn't make sense to new cat. The backstory is "kittypet1" but it should've given "kittypet4"
Grade: Regular
Occurrence: Permanent (as in it gave me the same wrong backstory both times)
Reproduce: Border patrols until you rescue the cat who tries to chase their twolegs' car. Then check their backstory.

Patrol ID + Outcome Print (if applicable):
PATROL START ---------------------------------------------------
Patrol Leader: Fawnneedle
Random Cat: Booker
Total Number of Possible Patrols | normal: 27, romantic: 0 
starting chance: 30 | EX_updated chance: 71
Fawnneedle updated chance to 71 | Booker updated chance to 71 | Whisperrip updated chance to 71 | Pelicanpaw updated chance to 71 | 
PATROL ID: gen_bord_abandonedkittypet1_kittypet4 | SUCCESS: True
Pelicanpaw ('94', 'aggression', -1)
Pelicanpaw ('94', <SkillPath.KIT: ('active imagination', 'good kitsitter', 'great kitsitter', 'beloved kitsitter')>, 2)
PATROL END -----------------------------------------------------

Commit #: 1d264a1b14908ceeb9db64e6d766aa4385488870

**Comment by Lixxis** [comment]
Have to try to replicate but looking at that patrol id in patrols/general/border.json the cat should be generated with the kittypet4 (abandoning) backstory.

**Comment by scribblecrumb** [comment]
closing as stale
