### ISSUE TITLE
Update requirements instructions in terminal

### ISSUE THREAD

**Issue by larkgz** [ClanGenOfficial/clangen#2126]
If the game detects certain missing dependencies, it exits with error code 1 and prints a message about installing using `requirements.txt` or Thonny’s packaging system:

https://github.com/ClanGenOfficial/clangen/blob/378bc0c56b7f0bbeb3a8302d336024036f5bf142/main.py#L26-L59

Since we have fully switched to Poetry, this should either be updated to more accurately reflect how to install requirements or be removed.

**Comment by archanyhm** [comment]
I think we can simply remove this "feature" from the game. People aren't supposed to run via source and if they do, they're expected to be aware of the process of installing dependencies; handholding them via the terminal isn't really what I feel like is sensible for us to do and only makes the impression that we encourage folks to run from source. Thoughts on this?

**Comment by archanyhm** [comment]
Pretty much closed by #2127
