### ISSUE TITLE
Improve Page Navigation for cat list screen

### ISSUE THREAD

**Issue by larkgz** [ClanGenOfficial/clangen#2137]
It would be useful if pressing left on the first page of the cat list cycled you to the last page (and pressing right on the last page took you to the first), especially for large clans.

It actually already sets to go to the last page if the page number somehow gets below 0 as a fallback, but it would be nice if it were a real feature.

https://github.com/ClanGenOfficial/clangen/blob/44699b314005049f2c09e60cc315e4115e8b0b22/scripts/screens/ListScreen.py#L576-L579

**Comment by archanyhm** [comment]
I'm personally opposed to a "wrap around" logic for the regular buttons. I'd rather have a "jump to last page" and "jump to first page" button left and right of the previous page/next page button with a double arrow on them.

**Comment by ZtheCorgi** [comment]
i agree with arch on this one, plus it would be great to be able to input a specific page number and go there directly

**Comment by larkgz** [comment]
Yeah, that’s probably more intuitive, I agree.
