### ISSUE TITLE
Kits dying of hunger when they should have priority

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2140]
**Type:** Code
**Grade:** Important
**Commit #:** 44699b314
**Summary:**
I have the feeding tactic set to "Hunters first", which in theory should give priority to cats with hunter skill first, and then to kittens (according to status). Current prey amount (before timeskip) is 29, needed amount is 32. My Clan has 3 cats with the hunter skill (one of them is the medicine cat) and 10 kits (whose current nutrition status is "hungry"). Upon timeskip, all 10 of the kits die of hunger, consistently (I tried a few times with the same result). My impression is that, under this tactic, kits are not being fed at all.

**Comment by KiraDragoness** [comment]
Tested this a bit more, seems like with that very same setup, the tactics "by status", "younger first" and "less nutrition first" save the kits, if "hunters first", "sick/injured first" or "high exp first" are active, ALL 10 of the kits die.

**Comment by Lixxis** [comment]
I changed the way of "hunters first", "sick/injured first" tactic in the fresh-kill pile. "high exp first" will stay the same, since it is mentioned it will only look on the EXP of a cat and nothing else.
