### ISSUE TITLE
relationship logs can no longer be viewed between dead and living cats

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2141]
when viewing a living cat's relationships screen, previously it was possible to view the relationship log between them and dead cats. this was especially useful for determining what events may have led to a cat murdering another. now it seems as though the relationship log button is grayed out for all deceased cats viewed from living cats' relationship screens. i don't know if this was a bug or intentional, but either way, can it be changed back please?

attached picture to show the grayed-out relationship log button on a dead cat (as viewed from living cat's relationships page)

![Capture](https://github.com/ClanGenOfficial/clangen/assets/117624277/2d3eb8d2-03d4-4282-9146-2fbca3af77b8)

**Comment by Lixxis** [comment]
It was changed because of the issue #1971, this was the simplest solution, but it should be possible to activate it again. So whoever is going to activate the logs again, check that it is not possible to look into the relationship page of the dead cat.

**Comment by ZtheCorgi** [comment]
thanks for the clarification lixxis ^^

**Comment by scribblecrumb** [comment]
Addressed in #2256
