### ISSUE TITLE
Retired young cat gets senior injury event

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2146]
This cat retired due to being deaf, he's only 30 moons old yet he had an event stating his joints were hurting because of his age.

Commit: #44699b314

![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/32e430c5-d0ba-4b22-a4d5-cc81e1364fea)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/389df571-fa12-4f82-8ad5-5c6fdf6cb3ce)

**Comment by keyraven** [comment]
This isn't a bug, since the thoughts are only marked with the elder status.   However, these thoughts should probably be tagged with the "senior" age.

**Comment by scribblecrumb** [comment]
> This isn't a bug, since the thoughts are only marked with the elder status. However, these thoughts should probably be tagged with the "senior" age.

I think this was more relating to the injury event than to the thought text.  Regardless this will be addressed with #2256
