### ISSUE TITLE
change poetry instructions 

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2147]
according to the instructions on poetrys website, it isn't recommended to install via pip. therefore, the instructions on how to install poetry inside of README.md and CONTRIBUTING.md are not correct and will lead to issues

it would probably be best to put a direct link to poetry's documentation, here: https://python-poetry.org/docs/

**Comment by larkgz** [comment]
I’m a little confused; CONTRIBUTING.md and README.md both link directly to Poetry’s documentation.

**Comment by ZtheCorgi** [comment]
in that case, it's just the instructions to install via pip that need removed then.

**Comment by ZtheCorgi** [comment]
like, the command i used to install via pip, i got from the documentation for clangen, so it needs changed, right?

**Comment by larkgz** [comment]
I cannot find any instructions about installing Poetry using pip in the Clangen documentation.

**Comment by ZtheCorgi** [comment]
huh, okay. i must have misunderstood something then? ugh, i need to go look when i get home then, sorry.
