### ISSUE TITLE
cat "thinks about their time in the nursery with" a much older, unrelated cat

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2150]
not sure the exact cause of this. a 7 moon old warrior apprentice got the thought "is thinking about their time in the nursery with nutdrift"

the problem is...nutdrift is 42 moons old and completely unrelated to the apprentice who had the thought. i checked

![image](https://github.com/ClanGenOfficial/clangen/assets/117624277/bdeee488-806e-4b7b-8e3f-b5531d0480b5)

**Comment by DeadGirlRisen** [comment]
I can't find this text inside of the thought files.

**Comment by ZtheCorgi** [comment]
it has been almost 2 months and there have been hundreds of commits since... ill take a look myself in vscode

**Comment by ZtheCorgi** [comment]
forgot about this, but i found it. it's in resources > dicts > thoughts > alive > apprentice.json 
![image](https://github.com/ClanGenOfficial/clangen/assets/117624277/9e08ceed-61f7-4c11-a2f2-582ffdc82779)

**Comment by DeadGirlRisen** [comment]
> forgot about this, but i found it. it's in resources > dicts > thoughts > alive > apprentice.json ![image](https://private-user-images.githubusercontent.com/117624277/328778778-9e08ceed-61f7-4c11-a2f2-582ffdc82779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzkzMDgsIm5iZiI6MTcxNTE3OTAwOCwicGF0aCI6Ii8xMTc2MjQyNzcvMzI4Nzc4Nzc4LTllMDhjZWVkLTYxZjctNGMxMS1hMmYyLTU4MmZmZGM4Mjc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNDM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDRiYTg0OWJlNDc5MzUyMDRhZWQwMmIxMjgwODExODFhMDRmYTQ3OWI4YzdkMWFjMjVhZThiZTVkOWZhNDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d-Ac2fUimcm8ls2Ngrax-5we61Iw1RNYTtZ6XXfkM8g)

What version is this? because in the version I have I don't have that, I also don't have the "apprentice_parent" in my file for apprentice.json. 

I also just checked the dev files on github, and they aren't in it. Is this the stable source code? Cause if so that would explain why I can't find it. /gen

**Comment by ZtheCorgi** [comment]
what in the.... okay, i must've been looking at the wrong version then, sorry, i will remove
