### ISSUE TITLE
12 moon old cat adopts 5 moon old litter

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2152]
what it says in the title. got the moonskip event "a loner leaves their litter to the clan. [cat] decides to adopt them as their own." the kits in question are 5 moons old, while the cat who adopted them is only 12 moons old. cats are only meant to be able to adopt cats who are at least 14 moons younger than they are, so this should not be possible, though it is more likely to be an oversight with moon event adoptions than it is a glitch.

**Comment by keyraven** [comment]
This isn't a glitch, but may be a something to look at, regarding the consistency.  The 14-moon limit was put in place to prevent weird edge-case manual adoption situations, but it could easily be 12 moons instead.

**Comment by ZtheCorgi** [comment]
either way, i believe it should be made consistent with the limits that have been imposed on the player, just because, well...if they ever accidentally unset the adoptive parent, they wouldn't be able to fix it unless they either exit the game without saving or edit the save file.

**Comment by ZtheCorgi** [comment]
i do think that the minimum age limit for cats to be eligible for automatic adoptions should be at least 5 moons older than the limitations that are imposed on the player, however, unless there's a way to ensure the kits that are generated are a specific age relative to the cat that's adopting them. since again, these kits were adopted at 5 moons old
