### ISSUE TITLE
invalid traits in patrol jsons

### ISSUE THREAD

**Issue by Tiritirimatangi** [ClanGenOfficial/clangen#2155]
There are some invalid traits being specified in the patrols jsons. I've found "empathetic" and "patient" in the general training json. In the past I've also found kitten traits in the patrol jsons. We made need a general cleanup effort

**Comment by DeadGirlRisen** [comment]
I just had fixed that! It was recently merged Tiri XD, I think Bouncy was left in as something to come back to after the current release.

Edit: Actually I realize you specified patrols just now, but I meant thoughts. I read to fast, however we do have the patrol project we are working on, so they can be cleaned up during that.

**Comment by ZtheCorgi** [comment]
yes, bouncy was accidentally removed during the personality overhaul and will most likely either be added back or have a similar trait added in its place after feature freeze

however, if bouncy is appearing in patrol tags, it should be removed anyway as it's exclusively a kit trait
