### ISSUE TITLE
eyes.png had inconsistent colored pixels

### ISSUE THREAD

**Issue by Honeycase** [ClanGenOfficial/clangen#2158]
Hi!! So while looking through the eyes.png, I noticed some inconsistencies with colors! I ended up fixing all the ones I noticed in the .png below. For example, half of the bronze eyes had a darker pupil than the other half, which were purple-ish. 

![eyes_fix](https://github.com/ClanGenOfficial/clangen/assets/157860472/2a7d5378-1b97-45c6-b6fc-7a6ecea3cc36)

**Comment by keyraven** [comment]
Hello, thank you so much for making fixed versions of the eyes. Would you be willing to make a pull request, and include some side-by-side examples of changes made? I would be happy to review the changes and discuss merging these fixes.

**Comment by Honeycase** [comment]
Yes, of course! I'm happy to help!

**Comment by keyraven** [comment]
Thanks for making that PR! Now that #2160 has been merged, I will close this issue.
