### ISSUE TITLE
Pregnant Tom?

### ISSUE THREAD

**Issue by Athenabird97** [ClanGenOfficial/clangen#2162]
![Untitled](https://github.com/ClanGenOfficial/clangen/assets/165253106/61cbb9a2-bee8-44be-a6a2-86d42588875c)
He's been a tom since I started the clan. 

Also his mate, Flickerlily, had a somewhat related glitch happen: He was female as a kit, then when he earned his full name, his sex randomly changed to male. Not trans, just male. I manually changed gender to be trans, cuz cool, whatever, but Flickerlily is definitely bio female, cuz he's a tortie.

**Comment by ZtheCorgi** [comment]
1. are you playing on stable release, or development version?
2. are you sure you don't have the same-sex biological kits/ignore biology setting enabled?
3. do you have any proof that flickerlily was definitely a female as a kit? it's not that i think you're lying, but it's easy to misremember things like that.

**Comment by keyraven** [comment]
This is excepted behavior when certain settings are enabled.  The questions haven't been answered in a few days, so I will close this for inactivity.
