### ISSUE TITLE
patrol.py not processing injury code correctly

### ISSUE THREAD

**Issue by Tiritirimatangi** [ClanGenOfficial/clangen#2169]
Currently the code seems unable to give multiple injuries to the same cat in a single patrol. For example:

                "injury": [
                    {
                        "cats": ["s_c"],
                        "injuries": ["claw-wound", "torn ear", "scrapes", "shock"],
                        "scars": ["THREE"]
                    }
                ],

Will result in s_c gaining a claw-wound. It always seems to be the first injury that is given, in my experience playtesting

**Comment by keyraven** [comment]
As documented, the "injuries" section is a list of possible injuries, from which one will be chosen.  The intended method to give a cat multiple injuries is to create a separate injury entry. For example, to give a cat both "torn ear" and "scrapes", you would write 

 ```
"injury": [
                {
                    "cats": ["s_c"],
                    "injuries": ["torn ear"],
                    "scars": ["THREE"]
                },
                {
                    "cats": ["s_c"],
                    "injuries": ["scrapes"],
                    "scars": ["THREE"]
                }
            ],

```

The choice of injury should be random, and I can't replicate your error regarding the first element always being chosen. Random selection appears to be working as intended.

**Comment by Tiritirimatangi** [comment]
> As documented, the "injuries" section is a list of possible injuries, from which one will be chosen. The intended method to give a cat multiple injuries is to create a separate injury entry. For example, to give a cat both "torn ear" and "scrapes", you would write
> 
> ```
> "injury": [
>                {
>                    "cats": ["s_c"],
>                    "injuries": ["torn ear"],
>                    "scars": ["THREE"]
>                },
>                {
>                    "cats": ["s_c"],
>                    "injuries": ["scrapes"],
>                    "scars": ["THREE"]
>                }
>            ],
> ```
> 
> The choice of injury should be random, and I can't replicate your error regarding the first element always being chosen. Random selection appears to be working as intended.

Cool beans, my bad! I'll go through and check how I've been tagging injuries and fix it
