### ISSUE TITLE
possible scar overflow issue

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2170]
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/da673c07-f252-4cb5-ba9d-4c752565c9a4)

on pose 2 with the "BEAKCHEEK" scar, it appears to overlap the kit's eye. unsure if this is intentional or not

https://github.com/ClanGenOfficial/clangen/assets/126827015/cad33359-8001-4467-8d8f-f1663a70975b

**Comment by CL0WNTH0UGHTS** [comment]
fixed in https://github.com/ClanGenOfficial/clangen/pull/2179 (The scar was just bumped to the right and should no longer overlap with eye)
