### ISSUE TITLE
pixel overflow

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2174]
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/c5b4133f-3319-4a55-9b4c-c6ff2d1f5ba6)
on senior sprite 14, the BULLSEYE white patch bleeds out of the sprite

**Comment by CL0WNTH0UGHTS** [comment]
fixed in https://github.com/ClanGenOfficial/clangen/pull/2179 (aswell as an addition pixel bleed on a different sprite for BULLSEYE)
