### ISSUE TITLE
patrol event error

### ISSUE THREAD

**Issue by tieflingz** [ClanGenOfficial/clangen#2181]
![image](https://github.com/ClanGenOfficial/clangen/assets/128858184/bd21d6a1-4d18-4fe1-917b-20b540dc2315)

patrol prompt for coming across a vole plays out normally, proceeded. names are turned into errors after proceeding.

**Comment by keyraven** [comment]
Note: This issue is caused there being an outcome that should be stat-related, but no stat skill or stat trait was specified.

**Comment by sedgestripe** [comment]
Fixed in https://github.com/ClanGenOfficial/clangen/pull/2199
