### ISSUE TITLE
New Kitten Thinks of Guide

### ISSUE THREAD

**Issue by mermaidkoi** [ClanGenOfficial/clangen#2182]
**Type:** Code [?]
**Summary:** Spawned a new Clan, changed names. Noticed a kitten of 1 month is asking the Guide if they daydream as a thought. The guide has been dead for 138 moons, therefore no way are they speaking to the guide. I noticed that there was an Issue that was labeled as not a bug regarding the affection levels being randomized- so I looked into it. It would seem that they are not randomized for this particular duo- although, I cannot check the relationships of the guide. Either way, I think it is odd- great for storytelling purposes- but, still odd for a random moon zero thought on a kitten to include a cat deceased for a long time.
**Grade:** Unimportant
**Occurrence:** I have no idea.
**Reproduce:** It's... a though, so I'm sure that it'd appear eventually, though I do not know if I'd recommend spamming new clans. 
**Patrol ID + Outcome Print (if applicable):** n/a
**Commit #:** 4bbbb676cb9308ea4a62da1054773f90fb26bb1d
![python_RbKnn8y6H7](https://github.com/ClanGenOfficial/clangen/assets/120436538/efabf778-1498-4d96-b34c-c9b9c7b8fb9c)
![python_QpaypcJHaY](https://github.com/ClanGenOfficial/clangen/assets/120436538/50c39920-eff0-44f1-85cd-29641f771e50)
![python_iMiVOkIM29](https://github.com/ClanGenOfficial/clangen/assets/120436538/a88964bf-6af1-4d82-a807-c81273abc7fa)

**Comment by scribblecrumb** [comment]
Likely fixed, we've had a lot of updates to thought constraints
