### ISSUE TITLE
Moon Event - YOU CHEATED ON ME

### ISSUE THREAD

**Issue by mermaidkoi** [ClanGenOfficial/clangen#2184]
**Type:** Other
**Summary:** Buzzardstar is upset that Squirrelstripe was flirting with someone else. But, Squirrelstripe and Buzzardstar have *never* flirted with one another. They have no relationship bar- in fact, Buzzardstar likes some other cat romantically. So, really somethings wrong there. Uhm, I am not sure what relationship this event is supposed to change, because they didn't have relationship before this event either?
**Grade:** Unimportant
**Occurrence:** Permanent
**Reproduce:** I'm not sure how to reproduce this. Get lucky with a moon event I guess?
**Patrol ID + Outcome Print (if applicable):** n/a
**Commit #:** 4bbbb676cb9308ea4a62da1054773f90fb26bb1d
![python_TUgZioAooy](https://github.com/ClanGenOfficial/clangen/assets/120436538/dd26db7e-bcaa-4826-b8f8-3d5603e615c9)
![python_hqKqfTgKKJ](https://github.com/ClanGenOfficial/clangen/assets/120436538/b184c1f8-c717-4434-967d-2a228631be49)
![python_1QVlEfv6f2](https://github.com/ClanGenOfficial/clangen/assets/120436538/eb4e047d-7e76-419f-8679-0c537c74945e)

**Comment by ZtheCorgi** [comment]
it's possible that buzzardstar had a tiny crush on squirrelstripe, and that event reduced their romantic like and therefore made it seem like they weren't crushing on them to begin with? 

if you view buzzardstar's relationships and click on squirrelstripe, then click the page icon near the switch focus button, you can see if there have been any relationship events recorded between them.

**Comment by mermaidkoi** [comment]
Nope. As mentioned, there were no prior relationships between the duo. And, I previously checked all the relationship values a prior moon. So, I do believe it might be a bug.
![python_t549c9bMAx](https://github.com/ClanGenOfficial/clangen/assets/120436538/8f1d4e4b-a6e2-48a6-87df-aa7001489e9f)
![python_IKh3lqUQiu](https://github.com/ClanGenOfficial/clangen/assets/120436538/1e167a91-1e52-4847-b168-508379e7b92a)

**Comment by ZtheCorgi** [comment]
ok, thanks for giving more information! it definitely helps to be able to see the whole relationship log ^^

**Comment by mermaidkoi** [comment]
Yeah, no problem. If there's anything else needed for this bug issue, please let me know. I will try to gather the necessary information [even though I continued my testing in the save.]
