### ISSUE TITLE
Problem with freshkill pile conversion when there is an exiled cat in clan?

### ISSUE THREAD

**Issue by Spirit-of-the-Hollow** [ClanGenOfficial/clangen#2189]
Sent this to [#dev-version-tech-help](https://discord.com/channels/1003759225522110524/1054942461178421289) on the discord and was told to create an issue about in on Github Issues. So here I am! I was told it could be a problem with the freshkill conversion when there is an exiled cat in the save (there is in fact, an exiled cat in the save). 
![2024-04-04_17 42 51](https://github.com/ClanGenOfficial/clangen/assets/130174845/8ec07096-164c-44e5-bd65-a0cafb9db83c)
[Original message in case you need it](https://discord.com/channels/1003759225522110524/1054942461178421289/1225455585235832913)

**Comment by Lixxis** [comment]
This was caused by a cat with the status "exiled", but cat.outside, was set to false. 
I'm not sure if this was an issue from how the exiling was handled in previous versions or not, but I fixed this edge case in an upcoming PR to the stable version.
