### ISSUE TITLE
Weird Text on Patrol

### ISSUE THREAD

**Issue by Kamachameleon** [ClanGenOfficial/clangen#2193]
<img width="1470" alt="Screenshot 2024-04-04 at 10 56 10 PM" src="https://github.com/ClanGenOfficial/clangen/assets/166100457/73f62e8d-0cbd-47e9-8739-321d59175b21">
I found this weird text during a patrol. I also found that sometimes with the new fresh kill pile it won't remember me feeding cats if I click on it again from the events screen. I don't know how to recreate that so I'm sorry, but I hope reporting this specific bug helps out :)

**Comment by sedgestripe** [comment]
Fixed in https://github.com/ClanGenOfficial/clangen/pull/2199
