### ISSUE TITLE
Issues with Feeding all hungry button

### ISSUE THREAD

**Issue by swallowmilil** [ClanGenOfficial/clangen#2197]
Feed all hungry button is bugged. When I click it, some of cats lose nutrition numbers dramatically. Use stable version.
![image](https://github.com/ClanGenOfficial/clangen/assets/166241194/d0726639-66cc-49e5-879e-33bc57f31572)
![image](https://github.com/ClanGenOfficial/clangen/assets/166241194/2f7d3349-9a3e-49f9-8ed6-e294860dfb37)
``

**Comment by ZtheCorgi** [comment]
which feeding tactic do you have selected?

**Comment by Lixxis** [comment]
less nutrition first

**Comment by archanyhm** [comment]
Can we close this since #2198 is merged and released in v0.11.2?
