### ISSUE TITLE
Male cat with female mate is pregnant

### ISSUE THREAD

**Issue by NightTheKitten** [ClanGenOfficial/clangen#2202]
My tom cat Coniferpelt has become pregnant with his cis female mate's kits. I have never edited the gender of either.
Enclosed is a (admittedly crude) screenshot collage of the clancats json + coniferpelts page, as well as the clancats.json itsself.

[clan_cats.json](https://github.com/ClanGenOfficial/clangen/files/14900466/clan_cats.json)
![i am confusion](https://github.com/ClanGenOfficial/clangen/assets/57920790/db10c52b-138e-4c71-ad6b-710de0b48805)

**Comment by starfelis** [comment]
Do you have same-sex breeding enabled? If so then this is the intended behaviour. It was changed recently so that if it's enabled, any cat is able to get pregnant regardless of their/their mates gender

**Comment by j-gynn** [comment]
Issue has been stale for 3 months with no response from author, @NightTheKitten though I doubt you can recall by now, can you confirm whether you had same-sex breeding enabled when this bug was reported? Otherwise, suggest closing issue.
