### ISSUE TITLE
 cats are always malnourished and dont have food 

### ISSUE THREAD

**Issue by Mercury984** [ClanGenOfficial/clangen#2206]
Hi! It's been scaring me to play because my cats are always starving/malnourished even tho i have WAY more food than needed. no matter what i do it does that even when i have food left over in the thousands. i dont know what i did wrong.
![mememe](https://github.com/ClanGenOfficial/clangen/assets/152252889/c7ab8be6-8466-4c9b-a0d5-b134eb7f88aa)
![mememmee](https://github.com/ClanGenOfficial/clangen/assets/152252889/598c0c73-f8a7-4e44-8e16-c8c39fde13bd)

**Comment by Oddlem** [comment]
Sorry if this is a really basic answer, but I'd like to rule out other things first. Are you manually feeding your cats? I know there's an option to click on clearing and feed non-hungry cats. Also, could you say which tactic you have enabled?

**Comment by Mercury984** [comment]
> Sorry if this is a really basic answer, but I'd like to rule out other things first. Are you manually feeding your cats? I know there's an option to click on clearing and feed non-hungry cats. Also, could you say which tactic you have enabled?

I hadn't really used any buttons, I had just expected the game to do as it should have, but i figured it out and fed my cats! Thank you for replying! It just took me a long time to figure out the problem
