### ISSUE TITLE
Double clicking to add a cat to a patrol no longer works

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2208]
Type: UI
Summary: You used to be able to double click a cat to add it to a patrol. Now you cannot
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/e400dc0a-233b-4f8b-a8b5-f069aaf3c1d6)
Grade: Non-vital
Reproduce: Try to double click on a cat in the patrol screen. Nothing happens anymore
Occurrence: Permanent
Commit #: 99a02b6e19192a7086a476566e6217fb31806a15

**Comment by keyraven** [comment]
I don't believe double-clicking was ever implemented as a "quick-add" for patrols.
