### ISSUE TITLE
App1 in a solo medicine cat patrol

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2212]
Type: Code
Summary: App1 showing up in a solo medicine cat patrol
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/95eee5d7-015c-46af-8414-cd3694281edf)
Grade: Unimportant
Reproduce: Get the bch_med_gatheringjuniper_leaf-bare1 patrol when it's just one medicine cat
Occurrence: Probably permanent?
Commit #: 99a02b6e19192a7086a476566e6217fb31806a15

**Comment by lillithrosepup** [comment]
Fixed, will be PR'd soon
