### ISSUE TITLE
Adopted litter generates with no relationship with parents and vice versa

### ISSUE THREAD

**Issue by happy413** [ClanGenOfficial/clangen#2213]
Type: Other
Summary: I have two couples who adopted litters during timeskips, not manually. I noticed in relationships that both sets of parents had empty relationships or barely existent relationships with their children and vice versa. This has continued into their adulthood, all relationship bars are empty or almost empty.
Grade: Unimportant
Occurrence: Permanent
Reproduce: Timeskip until a couple adopts a litter.
Patrol ID + Outcome Print (if applicable): n/a
Commit #: 99a02b6e19192a7086a476566e6217fb31806a15

![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/e64dc2f5-8740-46b3-b5d2-7934ead454f8)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/88ca48a7-7235-4437-a47c-7648ab729813)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/d57c6197-ce16-424f-aa6a-a4662ffbdad8)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/f9fd3a6c-5028-490c-a5f7-6f6b605b8db3)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/6b1e1ebf-ebe1-4932-8d10-d70e23d49455)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/bf80796c-9f3a-47bb-85a4-c4de8c93c8c5)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/aec773dd-3f9b-4054-9978-fe0ac107d41a)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/9038f32a-36bb-4777-9d90-d0937b0317d6)

**Comment by happy413** [comment]
Same couple just adopted another kit during a timeskip. Again, relationships are completely blank.

![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/f24be97c-1805-4638-8237-761666bd384e)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/d241c084-9283-4cee-adf7-3bc9276c47ea)
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/140ed2d9-08ae-44ba-97da-edddf6ab98e3)

**Comment by ZtheCorgi** [comment]
most likely an oversight as opposed to a bug, but it should still be seen to imo ^^

**Comment by happy413** [comment]
I'm not a coder but the issue might be adopted kits/parents (both generated and manual) not being tagged as family in relationship files as opposed to bio kits/parents? I noticed this while going to edit relationships manually.
