### ISSUE TITLE
"Next cat" Button Broke in Relationships Tab

### ISSUE THREAD

**Issue by Honeycase** [ClanGenOfficial/clangen#2214]
The system is windows 10+ and used source! Checking a relationship log of the last cat in a clan results in the "next cat" button appearing available, but clicking said button does nothing except send the error text shown below ^^

![Screenshot (843)](https://github.com/ClanGenOfficial/clangen/assets/157860472/9a3f6625-729c-4b7b-9b90-c8b62435ef69)
![Screenshot (844)](https://github.com/ClanGenOfficial/clangen/assets/157860472/bb15fe6d-ba93-48c8-8d72-fe804ed74ff3)
![Screenshot (845)](https://github.com/ClanGenOfficial/clangen/assets/157860472/20dac95f-b7b0-41a6-84c1-26dc3e4b6778)
![Screenshot (846)](https://github.com/ClanGenOfficial/clangen/assets/157860472/6a3a5426-e747-40e3-9972-5c4ef7105212)

**Comment by scribblecrumb** [comment]
I can't seem to replicate this, anyone else have any luck?

**Comment by scribblecrumb** [comment]
Ahh nevermind, I didn't realize you had to open and close the relationship log to get this to happen.  This issue was reported already here: #2195
