### ISSUE TITLE
strange wording in patrol outcome

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2215]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/c7b209f2-ada2-4122-b696-10b17cbd15f0)

![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/af5cfe57-8b16-421a-a2d9-ebc91c047671)
might just be me reading this one weirdly, but i think a better wording/punctuation for this one would be:

"This close to the nest, the eagles hardly take notice of other animals. [cat] can even see sparrows nipping in and out of their own nests, which were interwoven with the eagles'. It's a great opportunity to watch the birds and learn their body language, including their interactions with their chicks. They were surprisingly gentle."

**Comment by lillithrosepup** [comment]
Fixed, will be PR'd soon
