### ISSUE TITLE
"limitation" tag is spelled wrong on the github issues forum

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2216]
Pretty sure this is supposed to be spelled "limitation" not "limination"?
unless there's another definition for that that I'm not aware of

<img width="81" alt="Screenshot 2024-04-16 at 10 36 43 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/30da4a36-90b4-4b49-964f-6e195df60997">

**Comment by Lixxis** [comment]
fixed
