### ISSUE TITLE
Leader thinks they're not a good deputy (patrol)

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2217]
The leader of the Clan admits to their patrol they think they're not a good deputy. In this patrol, both the leader and the deputy are present. The success text says the same thing.

![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/8c330732-6e1f-4a3b-b55b-403e70347fd9)
PATROL ID: gen_train_deputydoubt1

**Comment by Tiritirimatangi** [comment]
This is weird, the patrol specifically shouldn't generate with the leader there:

        "min_max_status": {
            "deputy": [1, 1],
	        "leader": [-1, -1]
        },
  
I think I'm going to have to call in key

**Comment by scribblecrumb** [comment]
Replicated.  Oddly enough, this patrol seems to be accessible to all patrol cats (other than meds) regardless of status, even apprentices.

**Comment by scribblecrumb** [comment]
Woop, nevermind!  Replication was only allowed bc of a bug in the debug_ensure code lol.  This actually isn't replicable, so I'll be closing it.  Please reopen if it happens again.
