### ISSUE TITLE
Med patrol outcome wrongly kills cat

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2218]
During a solo medicine cat patrol (ID bch_med_gatheringdandelion_leaf-bare1), in one of the failed outcomes the text implies the cat comes back to camp only shivering, but they die instead.

![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/f3f726fb-3449-4030-89ba-3ce2971604a1)

**Comment by lillithrosepup** [comment]
Fixed, will be PR'd soon
