### ISSUE TITLE
tabs under "dens" not hightlighting when moused over

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2219]
When in the cat list, events, patrol tabs, when the user opens the 'Dens" button, only the "Dens" and "Clearing" tabs darken when moused over.

**Comment by peppst-r** [comment]
Actually, _sometimes_ the "medicine cat den" darkens. The "warriors' den" never darkens. Not sure why its inconsistent like that

**Comment by scribblecrumb** [comment]
Hmm, I can't seem to replicate this.  Are you able to find a clearer cause?

**Comment by scribblecrumb** [comment]
Closing as stale
