### ISSUE TITLE
kits peeking out from behind warrior's den label on shipwreck camp

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2225]
Type:  Code/Visual
Summary: the kits are behind the den label. I don't know if this is intentional. It is kinda cute though. 
 Grade:  Unimportant
Occurrence: Rare
Reproduce: With kits in the clan, keep reloading the camp screen till they go play hide and seek
Commit: 99a02b6e

<img width="203" alt="Screenshot 2024-04-18 at 12 39 44 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/30cc1b71-f3c7-4990-87dc-818425f15f49">

**Comment by scribblecrumb** [comment]
I think we'll be leaving this as is, since the player can always hide den labels to access any cats behind them!  But thank you for bringing it to our attention anyways :]
