### ISSUE TITLE
The game keeps deleting itself from files

### ISSUE THREAD

**Issue by Mushroom-forestt** [ClanGenOfficial/clangen#2228]
Usually happens while playing. The game crashes with no error code and deletes itself from files. The clans and cats stay, but the application to open the game deletes itself.

**Comment by ZtheCorgi** [comment]
are you in the discord server? if so, did you read the announcement in regards to antivirus flagging the game, and have you taken the steps outlined in the post to whitelist the game folder?

**Comment by scribblecrumb** [comment]
Closing this, as it's likely due to the windows defender issues we're aware of.
