### ISSUE TITLE
Non- Hover State On The Majority Of Tabs

### ISSUE THREAD

**Issue by StrangexSnake** [ClanGenOfficial/clangen#2230]
As the title states, though nothing serious, the majority of selectable tabs, such as the Managed Role, patrol types, and two or three camp tabs, don't have dark/hover states on them in the 0.9.0 dev build

**Comment by scribblecrumb** [comment]
I'm at a loss, you wanna take a look @keyraven?

**Comment by DeadGirlRisen** [comment]
While I didn't see any issues with hover states on managed roles, patrol types, or camp tags, I did find a few hover states that could be fixed and am now making a pr to fix them. If you're still encountering issues with the hover states for the mentioned things, can you please give more details to the circumstances?
