### ISSUE TITLE
Add "Healthy" Parameter to Thoughts

### ISSUE THREAD

**Issue by scribblecrumb** [ClanGenOfficial/clangen#2233]
We need a way to distinguish between thoughts for healthy cats and thoughts for sick/injured cats.  The proposed solution is adding a "Healthy" parameter to the thought format that would be a bool.  True would be the default and would mean the thinker is healthy.  False would mean the thinker is sick/injured.

A coder that takes this on should coordinate with a writer to have at least a few "sick/injured" thoughts prepared for use with this feature.

The end goal here is to prevent cats who are sick/injured from having thoughts about sparring, going on patrol, or other activities that they would not realistically be doing.

**Comment by jdowner** [comment]
I'm just taking a look at the code and there are a couple of properties that seem related to 'health', e.g. `illness` and `injuries`. If we add a new property called 'health', this would have to be kept in sync with other properties like `illness` and `injuries`. Would it work to have 'health' be a `@property` that derives its value from `illness` and `injuries`?

A complication of this is that some illnesses (e.g. 'running nose') don't seem like they would necessarily prevent a cat from taking part in activities. One way of handling that would be to have a list of illnesses/injuries that prevent a given activity, but it is not hard to imagine that quickly becoming complicated. Alternatively, illnesses/injuries of a certain level would prevent strenuous activities, i.e. a numerical level can be used to make the decision rather than enumerating the relationships between all illnesses/injuries and activities (it looks like that number might already exist? I'm not sure though -- new to the code base).

**Comment by scribblecrumb** [comment]
That's a good point, luckily we do have a system for marking certain conditions by severity.  Currently each condition gets assigned a severity (minor, major, or severe).  Major and severe mean that the cat cannot work.  This is what already determines if a cat can do their rank job (go on patrol, heal other cats, mediate).  You can check if a cat "can work" using `cat.not_working` which is a bool that returns True if the cat cannot work and returns False if they *can* work.

Sidenote, we do have the thought format documentation finished at this time: [Thought Writing Doc](https://github.com/ClanGenOfficial/clangen/wiki/%5BWriting%5D-%E2%80%90-Thoughts).  It might be helpful for understanding what all the other thought parameters are already doing.

**Comment by jdowner** [comment]
> Sidenote, we do have the thought format documentation finished at this time: [Thought Writing Doc](https://github.com/ClanGenOfficial/clangen/wiki/%5BWriting%5D-%E2%80%90-Thoughts). It might be helpful for understanding what all the other thought parameters are already doing.

Oh, reading through that I think I misunderstood the original ticket... or perhaps I misunderstand it now in a new way :) Is this work intended to update the thought format to include the `healthy` state and add support in the `cats_fulfill_thought_constraint`?

**Comment by scribblecrumb** [comment]
Yes, that's the intention!  Sorry if my initial explanation wasn't clear enough there.  Ideally `cats_fulfill_thought_constraint` would end up checking that `cat.not_working` bool to see how it compares to the new `healthy` parameter in the thought format.  Though, if we're targetting cats that are injured/ill in a way that they can't work, rather than cats who are injured/ill in general, then it may be better to use a word other than "healthy".  

Maybe just keeping it consistent and calling the parameter `not_working` would be clearest?  `False` would end up as the default, then, with `True` meaning the cat cannot work.  Then you can just check if the parameter bool matches with the cat.not_working bool, if it doesn't match then the thought is discarded.

**Comment by jdowner** [comment]
@scribblecrumb I've created a draft PR for this issue (https://github.com/ClanGenOfficial/clangen/pull/2253). Let me know if this is what you had in mind. If it's ok, I'll ask one of the writers to add some content to go with the PR.

**Comment by jdowner** [comment]
@scribblecrumb after looking at the examples created by @Tiritirimatangi (https://github.com/ClanGenOfficial/clangen/commit/83ba0ab7ce01d4ba096205c202af9302dcb236fa) I wonder if having `not_working` as a boolean property of the thoughts format is the right way to go? Should it just be a string in `main_status_constraint`?

**Comment by scribblecrumb** [comment]
> @scribblecrumb after looking at the examples created by @Tiritirimatangi ([83ba0ab](https://github.com/ClanGenOfficial/clangen/commit/83ba0ab7ce01d4ba096205c202af9302dcb236fa)) I wonder if having `not_working` as a boolean property of the thoughts format is the right way to go? Should it just be a string in `main_status_constraint`?

Personally, I feel it'll be more consistent with other event formats if it's separated as a boolean property.  `main_status_constraint` is usually meant for checking the status (a.k.a the rank, such as apprentice or leader) of the cat.  I don't think `not_working` really fits within that category.  It isn't consider a status anywhere else in the code, so I think that would end up being un-intuitive.

But I would like to hear @Tiritirimatangi's thoughts on it.

**Comment by Tiritirimatangi** [comment]
> > @scribblecrumb after looking at the examples created by @Tiritirimatangi ([83ba0ab](https://github.com/ClanGenOfficial/clangen/commit/83ba0ab7ce01d4ba096205c202af9302dcb236fa)) I wonder if having `not_working` as a boolean property of the thoughts format is the right way to go? Should it just be a string in `main_status_constraint`?
> 
> Personally, I feel it'll be more consistent with other event formats if it's separated as a boolean property. `main_status_constraint` is usually meant for checking the status (a.k.a the rank, such as apprentice or leader) of the cat. I don't think `not_working` really fits within that category. It isn't consider a status anywhere else in the code, so I think that would end up being un-intuitive.
> 
> But I would like to hear @Tiritirimatangi's thoughts on it.

I'm happy for it to be a separate boolean! I'll go with what you guys think is best <3

**Comment by scribblecrumb** [comment]
> > > @scribblecrumb after looking at the examples created by @Tiritirimatangi ([83ba0ab](https://github.com/ClanGenOfficial/clangen/commit/83ba0ab7ce01d4ba096205c202af9302dcb236fa)) I wonder if having `not_working` as a boolean property of the thoughts format is the right way to go? Should it just be a string in `main_status_constraint`?
> > 
> > 
> > Personally, I feel it'll be more consistent with other event formats if it's separated as a boolean property. `main_status_constraint` is usually meant for checking the status (a.k.a the rank, such as apprentice or leader) of the cat. I don't think `not_working` really fits within that category. It isn't consider a status anywhere else in the code, so I think that would end up being un-intuitive.
> > But I would like to hear @Tiritirimatangi's thoughts on it.
> 
> I'm happy for it to be a separate boolean! I'll go with what you guys think is best <3

boolean it is, then :+1: thanks for the input!
