### ISSUE TITLE
random cat tagged in murder confession

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2236]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/42a93d21-cfbf-433c-a7e1-24a5040aa1a7)
swamppaw you have nothing to do with this

edit: it says swamppaw was the one who found out but that wasn't stated in the event text, just in history
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/2c068893-e4c9-4f8b-b8a5-201bfe130f6a)

**Comment by scribblecrumb** [comment]
I don't believe we currently have a way to mark that a generated r_c cat shouldn't be stuck into the murder history.  I would need to look at the murder history code to make sure of what's happening.  But moon events will generally generate with both an m_c and r_c.  It's likely that this event generated with an r_c, but r_c simply wasn't referenced in the event text.  They still got carried along into the murder history though, and thus were considered the witness.

I'll try to consider this limitation in my moon events reformatting.  I can likely add a tag that will ensure certain murder reveals cannot generate if an r_c has been chosen.

**Comment by scribblecrumb** [comment]
#1850 issue is the same probelm
