### ISSUE TITLE
Stuck in the med cat's den

### ISSUE THREAD

**Issue by GingerAkao** [ClanGenOfficial/clangen#2238]
I wanted to show some people just how much herbs I have in the den and clicked the den from the clearing. I then clicked the only can in the den to look at them, when I clicked back it brought me ack to the den but when I clicked back again, it showed me that cat again

Dev build 0.9.0, new development version from 21.04.2024

https://github.com/ClanGenOfficial/clangen/assets/134950974/3cbdb0c8-fde8-4e8a-b32f-680ef729aabe

**Comment by scribblecrumb** [comment]
Already reported in: https://github.com/ClanGenOfficial/clangen/issues/2220
