### ISSUE TITLE
Left Arrow and Shut Down

### ISSUE THREAD

**Issue by banananationminion** [ClanGenOfficial/clangen#2239]
After closing out of a cat's information and immediately spamming the left arrow key, it will go to a negative page number and the game will crash.

**Comment by scribblecrumb** [comment]
What do you mean by "closing out of a cats information"?  Are you talking about the profile page?

**Comment by banananationminion** [comment]
yes

**Comment by scribblecrumb** [comment]
I'm not having any luck replicating this, can you give more information on what exactly you're doing?

**Comment by banananationminion** [comment]
Not really, it seemed pretty unusual, and I dont have any evidence. I was on the second page when I closed out of the cat info and clicked the left arrow button too many times too quickly and went into a negative number, then it crashed after showing me an error page.
