### ISSUE TITLE
Adult Cats Get 1 EXP on Fails

### ISSUE THREAD

**Issue by Honeycase** [ClanGenOfficial/clangen#2244]
I believe only apprentices get one EXP on fails usually, but I noticed that adult warriors were getting 1 EXP as well (?). Hopefully, that makes sense! ^^;

PATROL START 
Patrol Leader: Snapdragonheart
Random Cat: Snapdragonheart
chosen filter prey size: medium
Total Number of Possible Patrols | normal: 6, romantic: 0

Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snapdragonheart']
Found stat cat: Snapdragonheart

starting chance: 60 | EX_updated chance: 81
Snapdragonheart updated chance to 91 |
PATROL ID: bch_hunt_greenleaf_solosquirrel1 | SUCCESS: False
PREY ADDED: 4
PATROL END 

![Screenshot (879)](https://github.com/ClanGenOfficial/clangen/assets/157860472/94d21a98-8075-438e-89e5-8198b457ba00)
![Screenshot (880)](https://github.com/ClanGenOfficial/clangen/assets/157860472/df33809d-5568-43b1-aedb-393e33b04ea0)
![Screenshot (881)](https://github.com/ClanGenOfficial/clangen/assets/157860472/4aefc2e6-e428-4da0-8ec3-6493d9b3434c)

**Comment by DeadGirlRisen** [comment]
Hi! You have it the wrong way around basically. Adults on fails gain 1 exp, but it doesn't matter for apprentices, regardless of failing they can get more than 1 exp.
