### ISSUE TITLE
patrol says we brought home a rabbit, but no prey is gained

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2245]
Type:  Code
Summary: We are at war with WebClan and chased off a prey-stealing apprentice, then took the stolen prey, but didn't actually get it. I'm also using the "raiding other clans" focus, against WebClan specifically. 
 Grade:  Regular
Occurrence: Rare
Reproduce: Get down to 0 relations with another clan/at war, then proceed on 4 cat border patrols and hope you get this one. 
Patrol ID/ Outcome Print:
<img width="639" alt="Screenshot 2024-04-22 at 5 30 19 PM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/0b5ce06c-d871-4ccc-89b2-d9c945d239a7">
Commit: 2f5e3120
![2024_04_22_0t9_Kleki](https://github.com/ClanGenOfficial/clangen/assets/73655037/646afc16-5fd2-439b-84a8-bad2e1bc1782)

**Comment by lillithrosepup** [comment]
Fixed, will be PR'd soon
