### ISSUE TITLE
Border patrol with nothing to do with prey/no mentions of it gives prey on failed outcome

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2246]
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/d5981d52-0090-4f6c-9508-d21d39d0e612)
Type: Code
Summary: This border patrol gives a very small amount of prey upon being failed when based on the text, no prey should be involved. Only clan relations.
Grade: Unimportant
Occurrence: Probably permanent? Might need more testing
Reproduce: Send a cat on a solo border patrol and get this patrol + outcome
Patrol ID + outcome print:
Patrol Leader: Nightcall
Random Cat: Nightcall
Total Number of Possible Patrols | normal: 9, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Nightcall']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Nightcall']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Nightcall']
No Stat Cat Found
---
starting chance: 30 | EX_updated chance: 41
Nightcall updated chance to 41 | 
PATROL ID: fst_bord_soloneutral1 | SUCCESS: False
PREY ADDED: 2.0

Commit #: 67d009d49cf0f7e336df246774d65d27349345b9

**Comment by lillithrosepup** [comment]
Fixed, will be PR'ed soon
