### ISSUE TITLE
text error "begin jeering at the Lionstar"

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2247]
Type:  Text
Summary: Patrol refers to a cat as "the (name)". They're particularly legendary? I guess? 
 Grade:  Non-vital
Occurrence: Rare
Reproduce: Get down to very low rep with another clan, then go on 4 cat border patrols till you encounter this one
edit: I'm also at war with this clan
Patrol ID/ Outcome Print: 
<img width="645" alt="Screenshot 2024-04-23 at 2 03 00 AM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/ae2cb497-4728-4b63-b156-475b19494681">
Commit: 2f5e3120
<img width="687" alt="Screenshot 2024-04-23 at 1 58 28 AM" src="https://github.com/ClanGenOfficial/clangen/assets/73655037/20bef0df-1420-4ed7-bbf3-8469a16874b8">

**Comment by lillithrosepup** [comment]
Fixed, will be PR'ed soon
