### ISSUE TITLE
[BUG] Outside-the-clan mate border patrol causes early-graduated apprentice to gain a mate

### ISSUE THREAD

**Issue by gr4yroblox** [ClanGenOfficial/clangen#2249]
**Type**: Code

**Describe the bug**
So, I had this apprentice that graduated early (10 moons), and i sent them on patrol alone, and they got the patrol where they have a mate from outside the clan and they get them to join, but they were still an apprentice so the generated cat was also an apprentice (nine moons) and i cannot access the choose mate screen because they're still apprentices so theres no way to separate them manually

**Grade**: Regular (im not able to unmate them since i cant access the mate screen because they are still apprentices, but i believe it still goes in regular)

**Reproduce**
1. Send an apprentice that graduated early on patrol
2. Get the (not sure what its called, but it's the one where a mate from outside the clan joins) patrol
3. proceed and mate joins (patrol succeeded)
4. Mate is also an apprentice

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**:  2243 developmental pull

**Additional context**
the new cat also had the other cat as their mentor (i forgot to take a screenshot of the patrol outcome)

**Screenshots**

![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/e54ad53c-ebdd-4d0a-a3d6-85502662ebc1)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/7ba0e14e-83bb-4f92-9f1a-b6e699130236)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/6b6a76d6-aeca-4566-afdb-b30d9d9872e8)
<img width="505" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/167941017/d737313c-6575-4aaa-a960-19dcd3ea60cd">

this is my first time doing a bug/issue report so im sorry if its bad/explanation isnt very good (dinopaw page screenshot taken one moon after the patrol)

**Comment by ZtheCorgi** [comment]
i thought we were removing this patrol because its a bug factory... i guess that was missed? it causes many issues and this is only one of them
