### ISSUE TITLE
[BUG] Leader with multiple lives has single death during birth but treated as though fully dead

### ISSUE THREAD

**Issue by kshaw98** [ClanGenOfficial/clangen#2250]
**Type**:
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
-Leader lost a life during kitting but is described as having completely died. (She still have eight lives left.)

**Grade**:
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Have pregnant leader with lives to spare.
2. Have leader die during kitting.

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: v0.11.2

**Additional context**

**Screenshots**
![lion](https://github.com/ClanGenOfficial/clangen/assets/167948387/3c49d48f-143a-48b7-8de5-2084706b1f88)

**Comment by keyraven** [comment]
This is intended behavior at the moment - we don;t have any special dying-in-kitting death texts for leaders.  It would be feasible to add some, however.

**Comment by keyraven** [comment]
This is a good first issue for newcomers!

**Comment by joesandmeyer** [comment]
I created a pull request here to solve the issue https://github.com/ClanGenOfficial/clangen/pull/2266
