### ISSUE TITLE
[BUG] Update not Downloading

### ISSUE THREAD

**Issue by RaineTopia** [ClanGenOfficial/clangen#2251]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
I've been stuck on the verifying update window box for 30 mins. My internet is fine. I can back out of the box and play the game without the new update, but trying to update again just leads to the same problem. 

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. Start clangen
2. Click the proceed/accept button when it asks to download the new update
3. See error

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 

**Additional context**

**Screenshots**
![20240423_230929](https://github.com/ClanGenOfficial/clangen/assets/167958866/c671b021-82ba-4482-a619-1529ee9aafbd)

**Comment by Lixxis** [comment]
Sometimes the Auto-Updater has some troubles.
Best to download the new version manually: https://clangen.io/download
