### ISSUE TITLE
[BUG] Kit scared after 'witnessing' a murder that ocurred before they were born

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2254]
**Type**: Code

**Describe the bug**
Moon event says a kit is scared of a murderer after witnessing it... but the murder happened before this kit was even born.

**Grade**: Non-vital

**Reproduce**
Moonskip until a murder with an unknown culprit occurs. Then keep moonskipping until a reveal event happens, check if it's a possible witness or not (I guess this could happen with cats who joined the Clan after the murder event, too).

**Commit # or Game Version Number**: 67d009d49

**Additional context** n/A

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/b4b25dda-3233-4752-98fb-e56858686a4c)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/19dd1751-0ebe-4c87-a10b-a3f982da791d)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/c46c7aa2-b767-412a-8fd3-d00c44633154)

**Comment by scribblecrumb** [comment]
I'll see if I can add some sort of check for this, since I'm reformatting moon events anyways.
