### ISSUE TITLE
[BUG] Lost medicine cat comes back to camp as a warrior

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2255]
**Type**: Code

**Describe the bug**
A medicine cat who gets lost/taken by Twolegs comes back to Clan, but their role is changed to warrior, when they should be automatically back to being a medicine cat.

**Grade**: Regular 

**Reproduce**
Get a medicine cat to become lost, then skip moons until they randomly come back, and check their current role.

**Commit # or Game Version Number**: 67d009d49

**Comment by joesandmeyer** [comment]
The same thing happens with deputies. But I assume you want deputies to return as warriors, to avoid a greystripe / brambleclaw situation.

Fixed here at this PR: https://github.com/ClanGenOfficial/clangen/pull/2276
