### ISSUE TITLE
[BUG] Missing period in patrol outcome text

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2259]
**Type**: 
UI (Text generation error?)

**Describe the bug**
Sentences in patrol outcome do not have a period

**Grade**: 
unimportant

**Reproduce**
Get patrol outcome where prey and herbs are collected

**Patrol ID + Outcome Print (if applicable)**:
bch_hunting_patrol_dolphinofferings1 (trying to see if multiple patrols have this issue)

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/ed976cc1-4cc7-4aea-83e2-bb48b39aa350)

**Comment by joesandmeyer** [comment]
Fixed on this PR here: https://github.com/ClanGenOfficial/clangen/pull/2267
