### ISSUE TITLE
[BUG] Missing scar?

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2261]
**Type**: Sprite

**Describe the bug**
Cat was scarred due to a claw -wound but no scar is present on the sprite

**Grade**: Regular

**Reproduce**
acquire "SCRATCH" scar

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/9050ba5a-415c-462d-87b8-a37d597f2053)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/5564374f-8294-4c80-b453-3900bb048dc5)

**Comment by scribblecrumb** [comment]
Looks like SCRATCH isn't actually a scar in the game, though there are two scars with SCRATCH in their name, so perhaps it was meant to be one of those, but wasn't typed all the way.  It would be prudent to scrub the patrols and see if one is trying to assign SCRATCH as a scar, then remove accordingly.

If the reporter knows how the cat was injured in the first place, the info would be appreciated.

**Comment by peppst-r** [comment]
I believe that injury was from a rogue patrol, unfortunately I didn't think to grab which exact patrol

Also, if I'm seeing similar warnings in the console for other scars but the scar IS appearing, should I report the warning message?

**Comment by scribblecrumb** [comment]
No worries! It's helpful to at least have it confirmed that it was from a patrol.

And yes, please do report the warning message so that we can double check if those scars *should* be creating a perm condition.

**Comment by scribblecrumb** [comment]
#2209 is linked to this bug
