### ISSUE TITLE
[BUG] med cat dies in patrol that shouldn't kill?

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2262]
**Type**: Code

**Describe the bug**
Med cat app dies after patrol. Patrol should _probably_ result in the shivering condition rather than death

**Grade**: Important

**Patrol ID + Outcome Print (if applicable)**:
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/f82cfb8c-e607-4871-b3ea-0a5ab86fbe57)

bch_med_gatheringwildgarlic_leaf-bare1

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/393538ed-f60f-4ecf-973c-435dc03ed777)

**Comment by joesandmeyer** [comment]
This might be intentional. It looks like all medicine cats have a chance to die from searching for herbs during leafbare.

![image](https://github.com/ClanGenOfficial/clangen/assets/1490730/92c3bc0b-4309-4332-8a47-baba8e6e6af0)
