### ISSUE TITLE
[BUG] missing cat in tags

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2265]
**Type**: Code

**Describe the bug**
Murderer should be tagged in this moon event

**Grade**: Regular

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/02fdcf80-f671-404f-a32c-c2613d3fb4ed)

**Comment by scribblecrumb** [comment]
Hopefully fixed in #2256
