### ISSUE TITLE
[BUG] history does not show moon a murderer was discovered

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2275]
**Type**: (only select one)
...ui..?

**Describe the bug**
despite having "show moon when an event occurred" on in a cat's history, the moon the cat was found out as a murderer is not listed

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. skip moons till a cat kills another
2. skip moons till its found out
3. turn on "show moons" in the killer's history

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 0e554eee9ae64863e6ffb1aeef0c77ce0c5b2405

**Additional context**

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/833300c9-2922-4b3a-8636-84847dc18813)

**Comment by scribblecrumb** [comment]
Looks like `reveal_murder` in History class doesn't actually record the current moon, just an oversight.  Need to add a new `revelation_moon` key to both murderer and victim history dictionaries.  Also adjust `get_murder_text` in profile screen accordingly.
