### ISSUE TITLE
[BUG] Kit joins clan, and becomes a warrior instantly

### ISSUE THREAD

**Issue by Sparrow-Moon** [ClanGenOfficial/clangen#2280]
**Type**: (only select one)

- Code 
- 
**Describe the bug**
A queen runs off with a single kit, and later the kit joins the clan and proceeds to be the littlest warrior

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to patrols
2. Click on border patrols, with 3 cats minimum
3. Click proceed every time
4. Rinse and repeat until you come across a Queen that sprints away with a child.

**Patrol ID + Outcome Print (if applicable)**:
"gen_bord_sparrowgift1" and its a success outcome, but I dont know the EXACT print

**Commit # or Game Version Number**: 
Its from a modded version of the game, but its close behind Dev's version

**Additional context**
I was asked to submit this by Tiri to see if its possible to replicate in normal dev, 

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/110138073/31e46e5a-27c6-4e69-8794-3c57720672c6)

**Comment by CL0WNTH0UGHTS** [comment]
Do you know if the modded version you are playing on is before or after https://github.com/ClanGenOfficial/clangen/pull/2258? #2258, in normal dev, should have fixed this based on the changelog (from Lixxis, "[fixes] outsider kitten joined as warrior in clan")

**Comment by Sparrow-Moon** [comment]
> Do you know if the modded version you are playing on is before or after #2258? #2258, in normal dev, should have fixed this based on the changelog (from Lixxis, "[fixes] outsider kitten joined as warrior in clan")

ah,, probably before, then, seems i missed the changelog
apologies!

**Comment by CL0WNTH0UGHTS** [comment]
No don't be sorry! Its always good for us to get some context on where the version is, just to make sure the bug isn't a repeat offender (in which case, could indicate something biggers going on in the code)! Thank you for reporting anyways :3!

**Comment by Sparrow-Moon** [comment]
o7 No problem!!

**Comment by keyraven** [comment]
Closing, since it would appear this issue was fixed in https://github.com/ClanGenOfficial/clangen/pull/2258.
