### ISSUE TITLE
[BUG] Trait error

### ISSUE THREAD

**Issue by woltige** [ClanGenOfficial/clangen#2289]
Type:
Typo

Describe the bug
This bug makes the cat able to have a trait that is against their permanent condition (in this example - "deaf" condition with "careful listener" trait)

Grade:
- Non-vital - This bug can easily be ignored and does not have a large impact on play

Commit # or Game Version Number: 
v0.11.2

**Screenshots**
![Screenshot 2024-04-30 214646](https://github.com/ClanGenOfficial/clangen/assets/157845239/5cc9eceb-01b8-44dc-befb-4efa1bee22ee)

**Comment by ZtheCorgi** [comment]
not considered to be a bug to my knowledge. "listening" can be meant metaphorically as in, they just pay very careful attention /info
