### ISSUE TITLE
[BUG] Leader keeps "losing lives to weak leg" but doesn't actually lose them

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2290]
**Type**: Code

**Describe the bug**
I have a Clan leader with the weak leg permanent condition. After the last update, every moonskip I get the message she "lost a live to weak leg". It gets recorded on her history text, but she doesn't actually lose any lives.

**Grade**: Regular/Important

**Reproduce**
Get a leader with the weak leg permanent condition, then skip moons and check the events and their death history text.

**Commit # or Game Version Number**: f586b2462

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/9f79c3fc-7090-4036-9198-cf24939dabf3)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/912af71b-1b81-4918-bacc-979d1f6daffb)

**Comment by ChickenBatnana** [comment]
The same thing happens with lost tail:
![image](https://github.com/ClanGenOfficial/clangen/assets/55719034/854a6374-c25a-4587-87bc-f960f065b9fe)
