### ISSUE TITLE
[CODE] Modify new_cat code to specify romance between outsiders and clan cats

### ISSUE THREAD

**Issue by Tiritirimatangi** [ClanGenOfficial/clangen#2294]
Currently the new_cat code (documented here: https://github.com/ClanGenOfficial/clangen/wiki/%5BWriting%5D-%E2%80%90-Patrols#new_cat-listliststr) has the ability to specify mates - so for example you can generate a pair of mated new_cats who join the clan together, or you can have a new_cat join as the mate of a cat on patrol

I would like to modify this code and expand it to include checking if the cat is applicable to have romance with the new_cat. This would be "romance:{index},{index}" and "age:romance". This prevents future bugs when specifying relationship romantic gains with new cats, such as having a 80 moon old new cat flirt with a 13 moon old warrior.

**Comment by sedgestripe** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/110428732/e4c743ef-e5b5-4d18-9798-cb0f95610040)
![image](https://github.com/ClanGenOfficial/clangen/assets/110428732/15a7163d-e8a6-45f1-a36c-4712c0798701)
![image](https://github.com/ClanGenOfficial/clangen/assets/110428732/c0d76110-e5b4-4cbb-9487-ceb395812b51)
![image](https://github.com/ClanGenOfficial/clangen/assets/110428732/810280e5-9e87-41d6-90aa-1d00fe78abca)

I have added the "romance:{index},{index}" and "age:romance" tags to patrol. I believe this should be the exact same logic used with mate:{index},{index} and age:mate, except it should not set the two cats as mates? Let me know if this is what you wanted.

**Comment by Tiritirimatangi** [comment]
> ![image](https://private-user-images.githubusercontent.com/110428732/331048592-e4c743ef-e5b5-4d18-9798-cb0f95610040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDg0ODMsIm5iZiI6MTcxNTg0ODE4MywicGF0aCI6Ii8xMTA0Mjg3MzIvMzMxMDQ4NTkyLWU0Yzc0M2VmLWU1YjUtNGQxOC05Nzk4LWNiMGY5NTYxMDA0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjg2YjEyZGYyNTZhYTUwOWRlZDFhN2U2NDg2NzA0NjFlNTUyNzg2MzZjMjhhZDNhNjkwZmJjMGU1YjBlYmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gNkrE0q0yCqr2yRLy6HC0npOGFgPuBAv9_aU7JCIpdo) ![image](https://private-user-images.githubusercontent.com/110428732/331048651-15a7163d-e8a6-45f1-a36c-4712c0798701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDg0ODMsIm5iZiI6MTcxNTg0ODE4MywicGF0aCI6Ii8xMTA0Mjg3MzIvMzMxMDQ4NjUxLTE1YTcxNjNkLWU4YTYtNDVmMS1hMzZjLTQ3MTJjMDc5ODcwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTdmYzAwNDJhYzc0YjEyNGRjYzM5M2Y2NTIzOTQ2Zjg2MDNkOTg1OGFjMmJkMzQ5ZWJhNDlmNjJlOGVlMjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cEXvDjenMp_A0wqm5IuEkBvy3j3QbMdyeioQhFGlHxk) ![image](https://private-user-images.githubusercontent.com/110428732/331048709-c0d76110-e5b4-4cbb-9487-ceb395812b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDg0ODMsIm5iZiI6MTcxNTg0ODE4MywicGF0aCI6Ii8xMTA0Mjg3MzIvMzMxMDQ4NzA5LWMwZDc2MTEwLWU1YjQtNGNiYi05NDg3LWNlYjM5NTgxMmI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjViNzE5MWVkODQ1ODE0NmE5YmFmYzY1NmVkOGU1MGFhM2MxNDgyMTlhZjYyNTRkODViM2NiNzBjODJkMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yUvymaNcopdyPnWBG1oc8aUxlzuhUfgnHvRYZnTJ25I) ![image](https://private-user-images.githubusercontent.com/110428732/331048752-810280e5-9e87-41d6-90aa-1d00fe78abca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDg0ODMsIm5iZiI6MTcxNTg0ODE4MywicGF0aCI6Ii8xMTA0Mjg3MzIvMzMxMDQ4NzUyLTgxMDI4MGU1LTllODctNDFkNi05MGFhLTFkMDBmZTc4YWJjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzQ5NzA0OGU5NzcwZTA4YjM4YThjZDMzYTk3NjliZWJlMGFiODAwZDQxNzRjZWQyMWU5YTFmNGQ4YzZmMDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dWK_yNyLwmnxbulnYSYQ3ngWYmI4ZTktU2WYyO8QI9c)
> 
> I have added the "romance:{index},{index}" and "age:romance" tags to patrol. I believe this should be the exact same logic used with mate:{index},{index} and age:mate, except it should not set the two cats as mates? Let me know if this is what you wanted.

This is EXACTLY what I wanted, thank you so much! Can I get you to document exactly what these new tags do so that I can accurately add them to the documentation?

**Comment by sedgestripe** [comment]
"romance:{index},{index}" | Indexes of cats to romance with the new cat. You can also specify patrol-cats (p_l, r_c, or s_c).


"age:{some_age}"                            | Cats are "newborn", "kitten", "adolescent", "young adult", "adult", "senior adult", "senior". You can also specify "mate" to put them in the same age-category as the first specified mate, "romance" to put them in the same age-category as the first specified romantic partner or "has_kits" to generate an age between 14 and 120 moons. Be very careful specifying both age and status-  there is no extra check to ensure they make sense together.
