### ISSUE TITLE
[BUG] MY GAME CRASHED AND MY OPEN GAME BUTTON DISAPPEARED

### ISSUE THREAD

**Issue by RaineTopia** [ClanGenOfficial/clangen#2295]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
I was updating my game and then it crashed and now my button to open my game is gone

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
1. Open the game
2. Click on proceed when game asks to update
3. Watch as it crashes and the button breaks

**Commit # or Game Version Number**: 
I don't know. I can't pull it up. I always keep my game updated, however. 

**Additional context**
I posted a bug on this site before about my update freezing, so I'm worried of that bug somehow got worse. I've been looking for the game starter or installer in my Files, but I'm not sure where it is. I provided a photo of my search in the Files if that helps any. I just want my game back. 

**Screenshots**
Should be my shortcut of the Clangen open button no longer being the button 
![20240501_232225](https://github.com/ClanGenOfficial/clangen/assets/167958866/aac7e0a1-77ea-44ad-9251-74bd820d0c24)
-
Should be what happens when I click the no longer my start game button
![20240501_232237](https://github.com/ClanGenOfficial/clangen/assets/167958866/46d69c92-8964-43e0-955e-b251b448c95d)
-
Should be my Files search. Hopefully it helps
![20240501_232259](https://github.com/ClanGenOfficial/clangen/assets/167958866/510e5ad3-ba29-4897-b88f-66eca017cd14)

**Comment by RaineTopia** [comment]
I don't know what to do and I'm scared that all my clans are gone and I want to play my game but I don't know what happened!

**Comment by DeadGirlRisen** [comment]
Hi! Are you on the discord server? If you are, you could try asking in players helping players or official tech support, someone might be able to walk you through and help you better there to be able to get the game up and running again. If you aren't on the server, I'd recommend going there for help with this. I hope this helps a bit.

My only real recommendation is to redownload the game, as the files should still be there to my knowledge.

**Comment by ZtheCorgi** [comment]
you should check out the announcements too, there was a recent announcement about anti-virus deleting clangen files and how to prevent it, and it sounds like this might have happened to you.

**Comment by archanyhm** [comment]
Closing this issue as it has been stale for a while.
