### ISSUE TITLE
[BUG] Scar_to_condition dict error

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2296]
**Type**: Code

**Describe the bug**
Scar isn't in the scar_to_condition dict, but shows up on sprite at least. Injury occurred in moon event with twoleg trap

**Grade**: regular 

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/184b40ca-0bc7-425f-88ee-bccd069f93ca)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/8295a7ba-c080-468b-9535-b1eda9da5791)

**Comment by peppst-r** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/885a4980-9825-4255-8b00-a791322baf7d)
 and another one from a moon event, broken bone from getting grabbed and dropped by an eagle

**Comment by j-gynn** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/569e743f-7c18-463c-b554-9075054730c5)
Additional, not sure where this comes from as I found it whilst testing for other things

**Comment by j-gynn** [comment]
I'll write an extension to the event analyser currently in development that can find all these (hopefully) - I can hopefully then just port it across to the patrol analyser variant
