### ISSUE TITLE
[BUG] continual losing lives to lasting grief but no lives are lost

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2299]
**Type**: Code

**Describe the bug**
Leader has lasting grief permanent condition, I have gotten two "lost a life to lasting grief" during moon events and it also says it in the leader's history tab BUT they still have 9 lives

**Grade**: Important

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/16072678-b938-4f60-a50f-72914a8c5509)

**Comment by peppst-r** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/36c4c667-0350-41c3-85f8-c35ad34ce228)
also, "live" should be "life"

**Comment by Lixxis** [comment]
Code behavior should be fixed in #2312

**Comment by j-gynn** [comment]
PR to fix this has been merged, suggest closing issue.
