### ISSUE TITLE
[BUG] Leader lost life to a weak leg, not actually losing life, happens multiple moons in a row

### ISSUE THREAD

**Issue by Chase1218** [ClanGenOfficial/clangen#2300]
**Type**: (only select one)
Code

**Describe the bug**
I get a continuous moon event saying my leader has lost a life to a weak leg. The life counter doesn't go down and the event doesn't clear the next moon.

**Grade**: (only select one)
Important

**Reproduce**
Make a leader, give them the weak leg condition, see if the error occurs.

**Patrol ID + Outcome Print (if applicable)**:
N/A
**Commit # or Game Version Number**: 
0.9.0 (Latest Dev released yesterday, May 1st 2024)

**Additional context**

**Screenshots**
![Screenshot 2024-05-02 124659](https://github.com/ClanGenOfficial/clangen/assets/149440038/4c987f72-fd62-4227-bfe7-5af7fbb3784c)
![Screenshot 2024-05-02 125308](https://github.com/ClanGenOfficial/clangen/assets/149440038/e00a72bd-f2ca-4419-be8a-13c9d24c0cd6)
![Screenshot 2024-05-02 125320](https://github.com/ClanGenOfficial/clangen/assets/149440038/1205726d-2dce-4e48-bbb0-20fdc48bf342)
![Screenshot 2024-05-02 125333](https://github.com/ClanGenOfficial/clangen/assets/149440038/4c4923d4-3d9f-4982-8468-26e56f32ca11)
![Screenshot 2024-05-02 125349](https://github.com/ClanGenOfficial/clangen/assets/149440038/96c4ee5c-3d09-46d5-ab73-43651f58ea64)

**Comment by Lixxis** [comment]
Already reported in #2290 and should be fixed with #2312
