### ISSUE TITLE
[BUG] Names Cut Off On Small Screen Version Of The Game

### ISSUE THREAD

**Issue by kiwiskaatzzz** [ClanGenOfficial/clangen#2311]
**Type**: (only select one)
UI

**Describe the bug**
When viewing individual cats profiles, the names are obscured and cut off and the buttons supposedly to view the full name or expand the name does not work. I've noticed this bug specifically on the small screen version of the game and when full screen is activated the names show per usual.

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
Not sure. Supposedly this happens on the small screened version of the game but i'm not sure if the same error occurs on other players games.

**Commit # or Game Version Number**: 
Dev Build: 0.9.0

**Screenshots**
![Screenshot 2024-05-03 2 48 39 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/1eed5aab-3ca4-480d-bbd6-a7de5433e1bf)
![Screenshot 2024-05-03 2 48 46 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/e7923117-0fde-42c3-996a-b7bb92b24487)
![Screenshot 2024-05-03 3 00 16 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/bae4ffe6-a49e-48a0-8d57-36474e042aec)

**Comment by ZtheCorgi** [comment]
this is actually a UI bug! so the type would be UI /info
