### ISSUE TITLE
[BUG] 2 neighbouring Clans have the same name

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2321]
**Type**: Code

**Describe the bug**
After generating a Clan, 2 of the border Clans share the same exact name.

**Grade**: Regular

**Reproduce**
Generate a new Clan, then use the Clan focus feature to check if any of the neighbour Clans have the same name.

**Commit # or Game Version Number**: ec191a97

**Additional context**
Seen at the screenshots channel.

**Screenshots**
(Published by c1candy in screenshots channel)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/4a3a3935-47fd-4134-b601-9758d5c69919)

**Comment by Oddlem** [comment]
I don't think this is a bug, but there definitely should be a check. That being said, I've never seen this screen before and there's nothing that I can see in the code that shows anything like this. I'm not sure if this is the same build to be honest

**Comment by scribblecrumb** [comment]
> I don't think this is a bug, but there definitely should be a check. That being said, I've never seen this screen before and there's nothing that I can see in the code that shows anything like this. I'm not sure if this is the same build to be honest

That screen is the warriors den, which is a recent addition to the dev build.  You are correct that this is more of an enhancement, though.

**Comment by archanyhm** [comment]
Should be fixed with #2348
