### ISSUE TITLE
[BUG] The wrong cat dies on a training patrol

### ISSUE THREAD

**Issue by untitledids** [ClanGenOfficial/clangen#2322]
**Type**
Code

**Describe the bug**
A random cat (r_c) gets stuck on a training patrol. In one outcome after proceeding, triggered by a different cat having a certain stat trait (ambitious, bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful), the stat cat (s_c) dies instead of the random cat.

It should be the random cat who dies, because they were the one who got stuck, and the stat cat wasn't in danger in this scenario. The text says "The patrol can't help s_c in time" despite the fact it was r_c who was stuck.

It is also heavily implied that the cat who survived killed the cat who died, or at least found enjoyment in their death, which implies that it should actually be the stat cat surviving due to their personality trait.

This happens in the beach, forest, and mountainous biomes.

In the plains biome, the random cat dies instead, and the stat cat lives, which seems to be what is also meant to happen in the other biomes.

**Grade**
Important

**Reproduce**
1. Send a group of 3 - 6 cats on a training patrol
2. Bring at least one cat that has one of the following traits: ambitious, bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful
3. Get the specific training patrol listed below
4. Proceed on the patrol and hope the specific outcome triggers

**Patrol ID + Outcome Print (if applicable)**
PATROL ID: bch_train_stuck1 | SUCCESS: False
PATROL ID: fst_train_stuck1 | SUCCESS: False
PATROL ID: mtn_train_stuck1 | SUCCESS: False
PATROL ID: pln_train_stuck1 | SUCCESS: False

```
PATROL START ---------------------------------------------------
Patrol Leader: Auburnbracken
Random Cat: Boulderpaw
Total Number of Possible Patrols | normal: 16, romantic: 2 
attempted romance between: Snakepaw Boulderpaw
final romance chance: 22
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snakepaw', 'Haystripe']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snakepaw', 'Haystripe']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snakepaw', 'Haystripe']
Found stat cat: Snakepaw
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snakepaw', 'Haystripe']
Found stat cat: Snakepaw
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Snakepaw', 'Haystripe']
Found stat cat: Snakepaw
---
starting chance: 50 | EX_updated chance: 81
Auburnbracken updated chance to 81 | Snakepaw updated chance to 66 | Haystripe updated chance to 66 | Boulderpaw updated chance to 66 | 
PATROL ID: bch_train_stuck1 | SUCCESS: False
Boulderpaw ('27', 'stability', 1)
Boulderpaw ('27', <SkillPath.CAMP: ('picky nest builder', 'steady paws', 'den builder', 'camp keeper')>, 2)
PATROL END -----------------------------------------------------
```

**Commit # or Game Version Number**
v0.11.2

**Additional context**
[Beach biome training patrol:](https://github.com/ClanGenOfficial/clangen/blob/development/resources/dicts/patrols/beach/training/any.json)

Trailing behind the patrol, the dune {PRONOUN/r_c/subject}{VERB/r_c/'re/'s} crossing shifts beneath r_c's paws. {PRONOUN/r_c/subject/CAP} {VERB/r_c/look/looks} around wildly for safe footing - just as the sand caves in beneath {PRONOUN/r_c/object} and the world goes dark.

The patrol can't help s_c in time, and as s_c starts to drift off to StarClan, the eyes of r_c glint malevolently. Was this...? s_c doesn't have a chance to finish {PRONOUN/r_c/poss} last thought.

[Forest biome training patrol:](https://github.com/ClanGenOfficial/clangen/blob/development/resources/dicts/patrols/forest/training/any.json)

Trailing behind the patrol, there's a mighty crash above r_c. They look around wildly - just as the world is blotted out by a tangle of heavy falling branches.

The patrol can't help s_c in time, and as s_c starts to drift off to StarClan, the eyes of r_c glint malevolently. Was this...? s_c doesn't have a chance to finish their last thought.

[Mountainous biome training patrol:](https://github.com/ClanGenOfficial/clangen/blob/development/resources/dicts/patrols/mountainous/training/any.json)

r_c is trailing behind the patrol when there is a mighty clatter of stones from below them. They look around wildly, just in time for the world to tip upside-down as the scree slope beneath them collapses.

The patrol can't help s_c in time, and as s_c starts to drift off to StarClan, the eyes of r_c glint malevolently. Was this...? s_c doesn't have a chance to finish their last thought.

[Plains biome training patrol:](https://github.com/ClanGenOfficial/clangen/blob/development/resources/dicts/patrols/plains/training/any.json)

Trailing behind the patrol, the ground trembles beneath r_c's paws. {PRONOUN/r_c/subject/CAP} {VERB/r_c/look/looks} around wildly for safe footing - just as the earth caves in beneath {PRONOUN/r_c/object} and the world goes dark.

The patrol can't help r_c in time, and as r_c starts to drift off to StarClan, the eyes of s_c glint malevolently. Was this...? r_c doesn't have a chance to finish {PRONOUN/r_c/poss} last thought.

**Screenshots**
![Screenshot (1)](https://github.com/ClanGenOfficial/clangen/assets/137177923/0352dcd0-b8eb-4ed4-8436-a1d1d70f2c02)
![Screenshot (2)](https://github.com/ClanGenOfficial/clangen/assets/137177923/40f830c7-cfb7-4b5f-8ff0-5e0dbc2bc60d)

**Comment by ZtheCorgi** [comment]
i think there are other outcomes for the stuck patrols that also mistakenly put s_c where r_c is supposed to be in the outcome text, i remember the one where they don't have time for some idiot who got stuck seems like it's got the names mixed up too

**Comment by untitledids** [comment]
Yeah, I think that line needs to be fixed for all biomes as well. I wasn't sure if I should make a new report or not about it, or mention it in this one. I'll probably just make a new bug report.
