### ISSUE TITLE
[BUG] warrior gets moon event intended for leader

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2323]
**Type**: code

**Describe the bug**
a warrior died while giving birth, but the event text said the birth "came at the cost of one of their nine lives"

**Grade**:
regular

**Reproduce**
1. have pregnant warrior
2. have them die while giving birth
3. reset until you get a message where it says they lost one of their nine lives

**Commit # or Game Version Number**: 
30850281483f8d159b9609faa177bb2f11638422

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/117624277/fff0fd9d-c890-456f-b712-1150d08f342c)

**Comment by ZtheCorgi** [comment]
beetquill is 100% dead and in starclan btw

**Comment by KiraDragoness** [comment]
I have a PR open to address this issue (#2312)! I'm just waiting for Lixxis to review a change she asked for.

**Comment by scribblecrumb** [comment]
Fixed in #2312
