### ISSUE TITLE
[BUG] Cats mixed up on the stuck training patrols in forest & plains

### ISSUE THREAD

**Issue by untitledids** [ClanGenOfficial/clangen#2324]
**Type**
Code

**Describe the bug**
A random cat (r_c) gets stuck on a training patrol. Proceeding has the chance of the random cat or patrol leader (p_l) harshly telling the stat cat (s_c) that they don't have time for some idiot who got stuck. The stat cat should be the one calling the random cat an idiot, because the random cat was the one who got stuck, and it would match the stat cat's trait to say it.

On the patrol IDs fst_train_stuck1, pln_train_stuck1, pln_train_stuck2, and pln_train_stuck3, this event can be triggered if you have a cat on the patrol with the trait ambitious, bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful.

On the patrol IDs fst_train_stuck2 and fst_train_stuck3, this event can be triggered if you have a cat on the patrol with one of the same traits as the patrols above, or bossy.

In the forest biome, the patrol outcomes begin with "As s_c rarely has patience for other cats," which is correct. It then continues with "r_c tells them harshly that they don't have time for some idiot who got stuck, making s_c resentful as they pull themselves out from under the branches" even though it was r_c who was the one stuck.

The plains biome is the same, except that it is the patrol leader telling the stat cat they don't have time for some idiot who got stuck. The patrol leader shouldn't be a part of this outcome text at all.

Here is an example of fst_train_stuck1 in plain text:
Trailing behind the patrol, there's a mighty crash above Boulderpaw. They look around wildly - just as the world is blotted out by a tangle of heavy falling branches.
As Snakepaw rarely has patience for other cats, Boulderpaw tells them harshly that they don't have time for some idiot who got stuck, making Snakepaw resentful as they pull themselves out from under the branches.

**Grade**
Non-vital

**Reproduce**
1. Send cats on a training patrol in the forest or plains biome.
2. Send three to six cats for the chance to trigger fst_train_stuck1 or pln_train_stuck1.
3. Send two cats only for the chance to trigger fst_train_stuck2, fst_train_stuck3, pln_train_stuck2, or pln_train_stuck3.
4. Bring at least one cat that has one of the following traits: ambitious, bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful.
5. Get one of the specific training patrols listed.
6. Proceed on the patrol and hope the specific outcome triggers.

**Patrol ID + Outcome Print (if applicable)**
PATROL ID: fst_train_stuck1 | SUCCESS: False
PATROL ID: fst_train_stuck2 | SUCCESS: False
PATROL ID: fst_train_stuck3 | SUCCESS: False
PATROL ID: pln_train_stuck1 | SUCCESS: False
PATROL ID: pln_train_stuck2 | SUCCESS: False
PATROL ID: pln_train_stuck3 | SUCCESS: False

**Commit # or Game Version Number**
v0.11.2

**Additional context**
The other biomes' code for this specific outcome on the stuck training patrols are correct.

**Comment by archanyhm** [comment]
Should be fixed with #2348
