### ISSUE TITLE
[BUG] The wrong cat gets injured on a training patrol

### ISSUE THREAD

**Issue by untitledids** [ClanGenOfficial/clangen#2325]
**Type**
Code

**Describe the bug**
A random cat (r_c) gets stuck on a training patrol in the beach biome. In one outcome after proceeding, triggered by a different cat having a certain stat trait (bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful), the stat cat (s_c) gets a blunt force injury and cheek scar. It also says that the stat cat made it out and blames the random cat for pushing them. The random cat was the one stuck in the first place, so it should be them blaming the stat cat for pushing them, and the random cat should also be the one with the injuries.

The patrol's code:
Trailing behind the patrol, the dune {PRONOUN/r_c/subject}{VERB/r_c/'re/'s} crossing shifts beneath r_c's paws. {PRONOUN/r_c/subject/CAP} {VERB/r_c/look/looks} around wildly for safe footing - just as the sand caves in beneath {PRONOUN/r_c/object} and the world goes dark.
Even though s_c made it out, {PRONOUN/s_c/subject} {VERB/s_c/swear/swears} someone pushed {PRONOUN/s_c/object}, and {VERB/s_c/blame/blames} r_c. r_c denies it and says they should get s_c back to camp to get {PRONOUN/s_c/poss} injury looked at.

Plain text example:
Trailing behind the patrol, the dune they're crossing shifts beneath Boulderpaw's paws. They look around wildly for safe footing - just as the sand caves in beneath them and the world goes dark.
Even though Snakepaw made it out, they swear someone pushed them, and blames Boulderpaw. Boulderpaw denies it and says they should get Snakepaw back to camp to get their injury looked at.

**Grade**
Important

**Reproduce**
1. Send a group of 3 - 6 cats on a training patrol in the beach biome.
2. Bring at least one cat that has one of the following traits: bloodthirsty, cold, fierce, shameless, strict, troublesome, or vengeful.
3. Get this specific training patrol.
4. Proceed on the patrol and hope the specific outcome triggers.

**Patrol ID + Outcome Print (if applicable)**
PATROL ID: bch_train_stuck1 | SUCCESS: False

**Commit # or Game Version Number**
v0.11.2

**Additional context**
The other biomes' code for this specific outcome on their stuck training patrols are correct.

**Comment by archanyhm** [comment]
Should be fixed with #2348
