### ISSUE TITLE
[BUG] Cat speaks with his dead mates to start dating a new cat

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2326]
**Type**: Code

**Describe the bug**
A cat has currently 2 dead mates (from who he hasn't moved on yet) and one living mate. When he wants to start dating a new cat, instead of talking only with his current living mate, he talks to the 2 dead ones as well.

**Grade**: Non-vital

**Reproduce**
My guess is this only happens when a cat has both one or more dead mates and a living mate, and they want to start dating a new one. So to reproduce it you would need to:
1. Kill a cat's mate.
2. Get that cat to date other cat.
3. Get that cat to want to date a third cat, before they move on from the dead one.

**Commit # or Game Version Number**: f586b2462

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/537a41a1-e2d1-4ad4-9abd-f49f5528f8d2)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/a3469dc0-7af9-438e-83f1-38dba98609ee)

**Comment by archanyhm** [comment]
Should be fixed with #2348
