### ISSUE TITLE
[BUG] immortal exiled leaders

### ISSUE THREAD

**Issue by c1candy** [ClanGenOfficial/clangen#2331]
**Type**: Code 

**Describe the bug**
It seems that if you exile a leader and save the game before the next cat gains nine lives (?), the exiled cat will became bugged and virtually immortal.

From my experience the "immortal exiled leader" cannot die from timeskips as long as there is a living leader in the clan. The game will try to kill the banished cat and this will be noted in the cat's history, but the cat will not actually die (as you can see in the first two screenshots).

Getting rid of the "immortal exiled leader" with "kill cat" button also removes the lives from the current leader.

**Grade**: Regular

**Reproduce**
1. Create a clan
2. Exile the leader
3. Immediately save the game (do NOT timeskip if you have a deputy)
4. Close and open the game

congrats, now your exiled leader should be immortal!
You can also repeat the steps to get more of the glitchy kitties.

From what I've seen the profile screen of "immortal glitchy leaders" will still show the "leader ceremony" button and remaining lives, but the profile screens of normal/mortal exiled leaders will not.

5. Timeskip/Appoint a new leader and allow leaders to automatically choose a new deputy
6. timeskip, timeskip, timeskip (...) timeskip I guess

**Additional context**
This is an issue I first encountered a few months ago
because it happened to me more than once and I saw some extremely old banished leaders in screenshots, I decided to see if I could deliberately reproduce what's happening and that's what I managed to find

**Screenshots**
Clangen telling me that exiled leader died (for the ~22nd time).
![Zrzut ekranu 2024-05-11 124538](https://github.com/ClanGenOfficial/clangen/assets/169532431/b61b06a8-e810-4314-8939-65fc4b8b46f6)

But she's still alive. And you can see some of the many times she "lost a life" already.
![Zrzut ekranu 2024-05-11 124557](https://github.com/ClanGenOfficial/clangen/assets/169532431/c31af421-a59d-43c3-ac90-f99ea9330d9d)

3439 moons old exiled leader from a different clan. And many deaths that didn't do anything.
![Zrzut ekranu 2024-05-11 160502](https://github.com/ClanGenOfficial/clangen/assets/169532431/592f3db4-441b-43ad-bdad-f468398f54b3)

What happens to the current clan leader if you kill the "immortal exiled leader". He traveled to starclan the next time he lost a life.
![Zrzut ekranu 2024-05-11 150804](https://github.com/ClanGenOfficial/clangen/assets/169532431/34cf3efa-ef8c-4e2c-b3eb-b9187d0ff88b)

**Comment by Oddlem** [comment]
I THINK this is the same bug that got fixed in [#2312](https://github.com/ClanGenOfficial/clangen/pull/2312)!

**Comment by j-gynn** [comment]
Can't replicate on the current development branch - seems to have been fixed.

![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/b95dd487-19ab-4514-902d-8d26576608aa)
Volestar (now Volewhisker) has, tragically succumbed to death.
