### ISSUE TITLE
[BUG] Scrollbars in the wrong places

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2337]
**Type**: UI

**Describe the bug**
There are scrollbars appearing in weird places where they shouldn't be, like in the relationship's page when a rel. bar is at the romantic/platonic love level, or in the view sprite page for the "Show as healthy" option.
EDIT: Also happening in the Cats Outside of the Clan page.

**Grade**: Non-vital

**Reproduce**
Open any cat's view sprite page, or go to the relationship page of a cat that has romantic or platonic love for other cat.

**Commit # or Game Version Number**: 1f8fb2e6c

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/35c8fe14-1b44-472e-ace4-d8c6a68f8e6a)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/fb8f1919-e225-41c1-bb9e-ca03e11ac307)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/798a654a-4927-4c4d-9fde-7b393738cafa)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/5b18fceb-9813-4057-b4e3-12aebca204e6)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/c1e39cc1-3827-48ec-bfc4-8f099e2b00c5)

**Comment by keyraven** [comment]
Note - this is one of the many small issues associated with the update to pygame_gui 0.6.10
