### ISSUE TITLE
[BUG] Hover text not appearing in some places/areas

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2339]
**Type**: UI

**Describe the bug**
The text that should appear while hovering over some cats is not appearing, but is consistently only happening to certain restricted areas. For example, while viewing the family tree, it doesn't work for the first 2 and a half cats of every row, but appears for the rest of the cats in any category. In the medicine den, it works for the herbs but doesn't appear for the first 3 cats of any row.

**Grade**: Regular

**Reproduce**
Visit any cat's family tree, try hovering over the first cats in any of the available categories. Go to the medicine den and do the same for the sick/injured cats.

**Commit # or Game Version Number**: 1f8fb2e

**Comment by KiraDragoness** [comment]
There's also a bunch of buttons that don't darken or work properly when hovering over them:
-The "Cats" and "Log" buttons in the fresh-kill page.
-All the tabs from the main events page (all events/ceremonies/births & deaths, etc.) work when you first open the game, but stop doing so after you visit and come back from the warrior's den specifically.
-When you try going back to the main menu and save via the pop up, the "Save" button stays gray instead of turning green like it does in the camp page.

More hovers not working properly:
-When you hover over the "Open Data Directory" in the Clan settings, the hover text appears on top of the page instead of next to the button.
-The same thing happens with the help hover in the notes section of a cat, but I'm unsure if that's intentional since the text box is so big.

**Comment by keyraven** [comment]
Note - this is one of the many small issues associated with the update to pygame_gui 0.6.10

**Comment by scribblecrumb** [comment]
Tooltips appearing in the top right corner when no space is available below the button is a bug within pygui 0.6.10.  Issues that could be fixed are fixed in #2342
