### ISSUE TITLE
[BUG] Wrong cat 'lost one of their nine lives' giving birth.

### ISSUE THREAD

**Issue by JkHowling** [ClanGenOfficial/clangen#2340]
**Type**: Code?

**Describe the bug**
Sunstar's mate, Stormyfox (the deputy), died while giving birth, however the event incorrectly stated she lost 'one of her nine lives' instead. 

**Grade**: non-vital

**Commit # or Game Version Number**: 72741e69

**Additional context**

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/26156840/ffd87622-1305-49ca-b41b-c557176539d9)
![image](https://github.com/ClanGenOfficial/clangen/assets/26156840/ba762844-81a5-4319-afaf-bf2c84a83c24)

**Comment by archanyhm** [comment]
Should be fixed with #2348
