### ISSUE TITLE
[BUG] Crashing on start

### ISSUE THREAD

**Issue by mangomadds** [ClanGenOfficial/clangen#2353]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Crashing on startup, cannot get it to successfully open. It was opening just fine yesterday, I've tried turning off my antivirus, restarting my laptop, running it as administrator to no avail. 

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game
- 
**Reproduce**
1. Click to open

**Patrol ID + Outcome Print (if applicable)**:
N/A

**Commit # or Game Version Number**: 
6e4718e5ee9038f54859023462acd39a69913eea - I'm assuming since it's the most recently uploaded one on clangen.io 

**Additional context**
N/A

**Screenshots**
https://screenrec.com/share/nDsHYcBq5m

**Comment by mangomadds** [comment]
It's happened yet again, I had to redownload the game. It seems to happen after updates, might be corrupting.

**Comment by mangomadds** [comment]
New Steps.
1. Update the game when it prompts you to after opening the application.
2. Once updated, make a new clan.
3. Hit Main menu button, save clan.
4. Instead of pressing quit, press the X on the window. 
After that, the application will refuse to open. I just tested this as well.

**Comment by ZtheCorgi** [comment]
so this is an application version of the game? you don't open the game using thonny/vscode or a terminal/command line?

**Comment by mangomadds** [comment]
> so this is an application version of the game? you don't open the game using thonny/vscode or a terminal/command line?

Yes! This is the application vers only.

**Comment by scribblecrumb** [comment]
Highly likely to be an antivirus issue
