### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fauxjasper** [ClanGenOfficial/clangen#2354]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
ex.: I was editing my save file and adding my own cats. I added a few cats outside the clans (all kittypets) and one of them, Izzy, was 144 moons old. I didn't bother adding relationships for them as I added the cats, as I figured I could open the game and hit "save" and it'd create random relationship values. Well, Izzy randomly generated a **romantic** relationship value with Ghoststrike, a 17 moon old warrior. Since the biggest age gap (to my knowledge) is 40 moons in the game, this is a concern. I also would like to add I was using the **Genetics** mod. However, since that mod doesn't edit the actual values besides how the patterns and such are generated, I assume this is most likely not something the mod created. I still let Chinch (op of Genetics) know, just in case. 

**Grade**: 
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Add a few new cats into your save file as a kittypet outside the clans who is 41+ moons older than any warrior.
2. Add a few new warriors who are 41+ moons younger than the kittypet.
3. Open the game and save so that it creates relationships.

**Commit # or Game Version Number**: d77c9440

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/170052900/03b56bbb-5f5a-477b-84d7-663ad500d45b)

**Comment by fauxjasper** [comment]
Apparently it happened in my other saves too.
![image](https://github.com/ClanGenOfficial/clangen/assets/170052900/c4b6732a-22f7-467c-be6a-fab6d31e4f4d)

I also want to say that the younger cats are NOT developing any relationship values at all. It's just the older cats having romantic like for younger warriors.

**Comment by sedgestripe** [comment]
Please refrain from reporting bugs when save-file editing and/or modding is involved as there are multiple places where the error could have occurred that we cannot control. If you are able to reproduce this bug with base ClanGen let us know.
