### ISSUE TITLE
[BUG] feeding tactic info at top of screen

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2356]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
when hovering over the feeding tactic "high exp first", the information is on the top of the screen. all other tactics' info is shown on the bottom

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. open the clearing
2. go to select a tactic
3. hover over 'high exp first'

**Commit # or Game Version Number**: f58ed31872ec5b180bd5355d2706dd82f51dc819

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/13b2584d-9bb0-4884-9c05-63f4fe047015)

**Comment by scribblecrumb** [comment]
This is a limitation of the current version of py_gui.  Perhaps fixable via a subclass, but likely a pain in the ass to figure out.

(however, the white text within the tactic box *is* a bug and I'll fix it lmao)
