### ISSUE TITLE
[BUG] Fourteen additional cats that were not listed in mass extinction event died

### ISSUE THREAD

**Issue by ReenieKitty** [ClanGenOfficial/clangen#2359]
I tried putting the screenshots in a spoiler to reduce scrolling. Spoiler worked just fine, but it broke the image display amd would only show the links no matter what I tried. 

**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Had a mass extinction event and fourteen cats that were not listed in the event died. Curiously, one cat, Whistleflit, is mourned despite their death never being declared. 

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player
Not major but it was honestly really surprising to find a ton of cats had disappeared that hadn't even died according to the announcements in game. 

I could definitely see someone who doesn't edit files and save scums to revive cats they don't want to die being upset if this happened to them and they saved before noticing. I honestly only noticed because my main cat and all my medicine cats vanished without their deaths being mentioned.

**Reproduce**
1. Have mass extinctions on
2. Moonskip until one happens
3. See if any cats died that are missing from the list

**Commit # or Game Version Number**: 
Lifegen's current patch, unsure what Clangen version is running underneath

**Additional context**
This was in Lifegen, but I'm like 90% sure this is a vanilla Clangen thing as I'm pretty sure I've seen this specific mass extinction in vanilla. 

**Screenshots**
**These are the cats it says died:**
![Screenshot (480)](https://github.com/ClanGenOfficial/clangen/assets/169868390/4acf841f-a72b-4b15-8238-3abce3a25d46)
**This is the rest of the births and deaths tab for that moon, no other max extinctions happened that moon:**
![Screenshot (483)](https://github.com/ClanGenOfficial/clangen/assets/169868390/8d6d0291-7745-40d1-bdb4-5d2673f12bcd)
![Screenshot (484)](https://github.com/ClanGenOfficial/clangen/assets/169868390/fcc75c17-7f92-418c-ad30-44214ccefeab)
**These are all the other cats that died in that same mass extinction despite it not saying they died in the event:**
![Screenshot (476)](https://github.com/ClanGenOfficial/clangen/assets/169868390/d6170d2b-8dfd-471c-9cae-9e011797e90b)
![Screenshot (478)](https://github.com/ClanGenOfficial/clangen/assets/169868390/ef5c179e-80af-4915-b2c9-80bdc194b722)
![Screenshot (479)](https://github.com/ClanGenOfficial/clangen/assets/169868390/f72f098f-1495-45a8-8d9a-a6593f72e0d5)
![Screenshot (485)](https://github.com/ClanGenOfficial/clangen/assets/169868390/9aeb5991-5b15-47db-b5b7-da630d5b14bd)
![Screenshot (486)](https://github.com/ClanGenOfficial/clangen/assets/169868390/b3a08ca1-8618-4cac-954c-ecd5535a99c2)
![Screenshot (487)](https://github.com/ClanGenOfficial/clangen/assets/169868390/32ab9cda-5699-4d85-ad0d-83db73f3dbb4)
![Screenshot (488)](https://github.com/ClanGenOfficial/clangen/assets/169868390/f7bbc34b-753e-4763-81ba-e71bae0ae134)
![Screenshot (489)](https://github.com/ClanGenOfficial/clangen/assets/169868390/661b02ff-c15e-44d9-bce7-500fd8975c10)
![Screenshot (491)](https://github.com/ClanGenOfficial/clangen/assets/169868390/9d338e05-7d8b-4101-bdfe-9728bfd2e8dc)
![Screenshot (492)](https://github.com/ClanGenOfficial/clangen/assets/169868390/219f574d-6a93-493d-a21c-fabfb7291a2a)
![Screenshot (493)](https://github.com/ClanGenOfficial/clangen/assets/169868390/cfebe97e-27e2-4f36-b059-7d62f9465c56)
![Screenshot (494)](https://github.com/ClanGenOfficial/clangen/assets/169868390/088281fc-927c-4158-8785-5fea0f4e5906)
![Screenshot (495)](https://github.com/ClanGenOfficial/clangen/assets/169868390/d860f738-1711-4da5-8a16-18506a5eba7c)
![Screenshot (496)](https://github.com/ClanGenOfficial/clangen/assets/169868390/bbc63ae1-c1d7-4b5b-8ebd-ebff7f6f882b)

**Comment by scribblecrumb** [comment]
Mass extinction is being refactored in #2264 anyways, so this bug will hopefully not carry over when that gets merged.

**Comment by ReenieKitty** [comment]
> Mass extinction is being refactored in #2264 anyways, so this bug will hopefully not carry over when that gets merged.

I hope so too, that way there wouldn't be any extra work for anyone. Once that update drops I suppose I'll let someone know if I see it again, but I'm not sure how to replicate it exactly as it's the only time I've ever seen it, or noticed it at the very least. 

I've been paying close attention to all the mass extinctions since this happened. It's been 50 moons and there's only been one, the one where people come and take cats. Nothing out of the ordinary happened, all cats that were stated to have been taken were taken, no more, no less. So this definitely doesn't happen every single time there's a mass extinction at the very least.

**Comment by ReenieKitty** [comment]
Sorry, I didn't mean to close this, it just did it automatically when I commented and I can't seem to disable that.

**Comment by scribblecrumb** [comment]
Hopefully fixed in #2256
