### ISSUE TITLE
[BUG] Grabbed by a hawk not tagged as no body, but kit death version is. 

### ISSUE THREAD

**Issue by rkzma** [ClanGenOfficial/clangen#2361]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
An adult cat died by being "grabbed by a hawk, never to be seen again". However, the grief events treat that there was a body- it is mentioned multiple times throughout both major grief events and minor grief thoughts that there is a body and there is a grave. Oddly enough, when a kit died from being "taken by a hawk" earlier in the save file, it treated it as if there was no body? I don't have screenshots for that example, though. 

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Create a Clan in the Mountainous biome.
2. Skip moons while ensuring at least 2 cats are alive (Since the death event needs two cats.)

**Commit # or Game Version Number**: 
v0.11.2

**Additional context**

**Screenshots**
![Screenshot 2024-05-18 at 10 13 43 PM](https://github.com/ClanGenOfficial/clangen/assets/168918767/5caf1744-bdba-4533-81de-74dedbe7b487)
![Screenshot 2024-05-18 at 9 54 59 PM](https://github.com/ClanGenOfficial/clangen/assets/168918767/1d712313-5581-406b-a926-e7649dae1ad0)
![Screenshot 2024-05-18 at 10 03 34 PM](https://github.com/ClanGenOfficial/clangen/assets/168918767/2a142b23-6a15-4843-a0fe-7b012d4ec1c7)

Specific death events:

> Adult:
> ![Screenshot 2024-05-18 at 10 03 07 PM](https://github.com/ClanGenOfficial/clangen/assets/168918767/91e14f20-3e85-42b5-8a5b-fb3488a8f51e)
> Kit:
> ![Screenshot 2024-05-18 at 10 08 51 PM](https://github.com/ClanGenOfficial/clangen/assets/168918767/faa64d09-b96e-4797-87c7-664f18bab710)

**Comment by scribblecrumb** [comment]
Hopefully fixed in #2256
