### ISSUE TITLE
[BUG] Weird family tree logic

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2362]
**Type**: Code

**Describe the bug**
I just noticed a weird logic in a cat's family tree. In a kit's family tree, one of their full older siblings appear as "not blood related" while the other siblings are correctly labelled as blood related. When you view the family tree from the problematic sibling's perspective, this kit correctly appears as full sibling. 
Maybe it has something to do with the intrincancies of their situation. This kit has 3 parents (2 biological and 1 adoptive because they are a polycule). The problematic sibling is mates with the adoptive parent's daughter, who is not blood related and would be their adoptive sister.
It works the same for every kit in that litter.

**Grade**: Non-vital

**Reproduce**
This might be complicated, but I'll try to set up the steps to replicate the situation:
1. Get 2 mates to have a first litter.
2. Get one cat from that litter to start dating a cat that has a parent in the Clan.
3. Get that parent to start dating one of the original 2 mates (forming a polycule).
4. Get a second litter with the first 2 mates, check their relations to the specified cat from the first litter.
It's unknown if this issue can happen in any other situation.

**Commit # or Game Version Number**: 59b4d5ec7

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/8ae439ab-e4e8-49a1-94f2-60d252201af1)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/28e51bbb-75cc-4198-a7cd-38afc15cb953)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/0726db4e-cde6-489f-bae4-003cbe684335)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/1f7401f2-3f0c-42e3-a98f-375af9bf9eea)

**Comment by LaeLita** [comment]
sounds like the parents are gaslighting that kit so much 💀
