### ISSUE TITLE
[BUG]  Dead Cats won't show up when trying to show dead in relationship screen

### ISSUE THREAD

**Issue by DeadGirlRisen** [ClanGenOfficial/clangen#2368]
**Type**: 
- UI 

**Describe the bug**
When you click Show Dead, it doesn't actually show the dead. You have to click show dead, and then show empty for it to reload and actually show the dead.

**Grade**: 
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Have a dead cat
2. Go to relationships of a living cat who knew the dead cat.
3. Click show dead, it won't actually change anything
4. Click show empty, and it'll reload the screen allowing for the dead to be seen.

**Commit # or Game Version Number**: 
59b4d5ec

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/82120509/b94fac59-57ec-4395-810f-9b2fb62eabe4)
![image](https://github.com/ClanGenOfficial/clangen/assets/82120509/a2473ebf-c6fd-4841-935e-af5f5ceb13af)

**Comment by KiraDragoness** [comment]
I noticed the problem here is that they're not automatically showing, if you click the next page the dead cats load suddenly.

**Comment by DeadGirlRisen** [comment]
> I noticed the problem here is that they're not automatically showing, if you click the next page the dead cats load suddenly.

Yeah, I think its probably a small coding thing or a ui on button press issue, where its forgetting to tell the code to refresh the elements.
