### ISSUE TITLE
Patrol gen_bord_abandonedkittypet1_kittypet4 consistently fails everytime I encounter it

### ISSUE THREAD

**Issue by DeadByte13** [ClanGenOfficial/clangen#2385]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
The patrol gen_bord_abandonedkittypet1_kittypet4 always falls no matter what, I haven't encountered it once through several dev releases and succeeded

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to patrols
2. border patrol until you get gen_bord_abandonedkittypet1_kittypet4
3. proceed
4. Should fail

**Patrol ID + Outcome Print (if applicable)**:
PATROL START ---------------------------------------------------
Patrol Leader: Burdockstar
Random Cat: Partridgedapple
Total Number of Possible Patrols | normal: 9, romantic: 0
starting chance: 30 | EX_updated chance: 73
Burdockstar updated chance to 73 | Splashwhisper updated chance to 73 | Partridgedapple updated chance to 73 |
PATROL ID: gen_bord_abandonedkittypet1_kittypet4 | SUCCESS: False
PATROL END -----------------------------------------------------

**Commit # or Game Version Number**: unsure where to find it but it's the pronoun release

**Comment by selkirks** [comment]
looks just like bad rng. same exact version + patrol. got a success
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/bab6f2e7-3de7-4aef-b5d1-a42b86916ca2)
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/a47b092c-0bbf-4961-9c74-e9e55a8818e1)
