### ISSUE TITLE
Code Bug - Focus Feature Bug

### ISSUE THREAD

**Issue by TrixieStargazer** [ClanGenOfficial/clangen#2387]
Code
During a moon event in the miscellaneous tab. A error message would appear "This is a bug, report it - focus feature'
Grade
- Non-vital - This bug can easily be ignored and does not have a large impact on play

Reproduce
1. Go to Warrior Den 
2. Click on 'Hoarding Resources'
3. Go to 'Event Tab'
4. Click on 'Timeskip One Moon'
5. Scroll down to 'miscellaneous'
6. See error

Game Version Number: Dev Build : dba6e299

Screenshots
![Screenshot 2024-06-01 140235](https://github.com/ClanGenOfficial/clangen/assets/171448108/22890258-f994-45ce-853d-21fa2219179c)

**Comment by j-gynn** [comment]
Unable to replicate in current development version or the dev build mentioned. Not sure what's going on there, but seeing as it seems to be fixed in development, I'm inclined to say this is resolved?
