### ISSUE TITLE
[BUG] Started a new clan... and it generated with 145 cats?

### ISSUE THREAD

**Issue by JkHowling** [ClanGenOfficial/clangen#2401]
**Type**: Code??

**Describe the bug**
Downloaded the most recent dev and generated a new clan named Ruinclan, and it genereated with 145 cats instead of the 8 I selected

**Grade**: Important?

**Reproduce**
1. Created a new clan off a fresh dev download

**Commit # or Game Version Number**: 85dd91978514e159aeec40974b0e392def34d6e9

**Additional context**
Clan was named Ruinclan, in the new Ruins camp, with the Peak clan symbol.
Some of the cats seem to be from my other save files, but some I don't recognize at all. Some of the original cats I selected at the start do appear as well.

**Screenshots**

![image](https://github.com/ClanGenOfficial/clangen/assets/26156840/7e35b63b-d3e6-4f0d-8b34-9e464900ed16)

**Comment by JkHowling** [comment]
Additional info: I left to the main menu and opened the clan again, and all the excess cats have vanished? Super strange and wish I'd tested more on things like patrols and such.

**Comment by selkirks** [comment]
most normal clangen bug /silly

**Comment by j-gynn** [comment]
I can repeat this bug - it looks like it's combining your save from the previous clan with this one. Also, if I click for more details, it cycles through the same three cats endlessly, none of whom were "supposed" to be in this lot. Very odd. Also, quitting and reloading does fix it. Looks like a pathing load issue, perhaps?
