### ISSUE TITLE
(UI) Most minor thing ever

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2410]
**Type**:
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
Please look at the screenshots before reading the description. While editing the history tab, if you press enter and then delete the new line, there is a static, fake typing line that just sits there until you change screens. You can have multiple white lines, but only the functional one flashes like normal. In the screenshots, my functioning cursor is the one highest up.

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to a cat's history tab and access the customizable tab.
2. Click on the box to edit it.
3. Press enter as many times as your heart desires.
4. Delete at least one of those new lines.
5. Annoying fake text line or lines.

**Commit # or Game Version Number**: 43448b39f91f8ed8e6c42d8418159d0437b116af

**Screenshots**
(https://github.com/ClanGenOfficial/clangen/assets/123250433/ad59ec07-6068-4fe0-aed1-2aac77c616a9)
(https://github.com/ClanGenOfficial/clangen/assets/123250433/01acc1cb-618e-463f-9695-192c3ce0826a)

**Comment by scribblecrumb** [comment]
Seems like something that's a pygame_gui limitation, unforunately

**Comment by PoppyBlossom** [comment]
I can't replicate this, perhaps it's already fixed.
