### ISSUE TITLE
[BUG] can't delete my game

### ISSUE THREAD

**Issue by spook-eboy** [ClanGenOfficial/clangen#2412]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- Sprite - an issue with the art in the game
- Code - general bugs related to how the game runs and responds to you. 
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here: https://github.com/ClanGenOfficial/clangen/issues/1818

**Describe the bug**
ex.: This bug implies that the cat is never ....

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game
- Dire - Still playable, but a major feature is broken
- Important - The bug has a large affect on the gameplay, but is not urgent
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player
- Non-vital - This bug can easily be ignored and does not have a large impact on play
- Unimportant - This bug has little to no impact on play. 

**Reproduce**

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 

**Additional context**

**Screenshots**

**Comment by spook-eboy** [comment]
type: code (?)
desc: Application file for the game won't extract and zipped copy is impossible to delete
grade: gamebreaking (and possibly computer breaking)
i just downloaded the windows 10+ version off the official site and ive extracted everything twice now with no application file in sight (even though its there in the zipped version). i came here to see if this was a fixable issue and found a report from a few months ago that was resolved by just dragging the zipped version out of the folder to manually extract it. tried that and nothing happened so i went to delete it, thinking the whole thing was a bust, and windows tells me i cant delete the app because it doesnt exist. all throughout this im getting warnings that this thing is malware and im getting more and more nervous.

**Comment by spook-eboy** [comment]
update: ive successfully deleted everything (the zipped copy on my desktop just disappeared??) but not being able to extract the application itself, or find the extracted version i guess, makes it unplayable for me

**Comment by archanyhm** [comment]
Not a bug.
