### ISSUE TITLE
Cat gets grief text for a living cat

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2413]
**Type**: Code

**Describe the bug**
Cat gets grief text for a cat who's not dead after her kit died

**Grade**: Non-vital

**Reproduce**
1. Have a cat lose someone without getting the grief condition for that cat
2. See what their grief text is

**Commit # or Game Version Number**: 43448b39f91f8ed8e6c42d8418159d0437b116af

**Additional context**

This cat has the grieving condition for a different cat who died this moon and the cat I assume the grief text would be for her kit who was killed in the same event.

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/e306f136-7f2d-439e-9c38-885d32a0ed68)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/645a0b76-9c9c-41da-a140-5992aaf1082b)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/6cf840e3-685d-48d6-84d3-bb455337390e)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/05a1ef9b-9051-44d2-a427-5ff1a2eca2e2)

**Comment by j-gynn** [comment]
This is - hopefully - fixed in the latest release (courtesy of #2408). Please let us know if you find it again! <3

**Comment by archanyhm** [comment]
See comment above. Reopen if persists.
