### ISSUE TITLE
Cat ID being overwritten upon a kit being born

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2415]
**Type**: Code

**Describe the bug**
One of my cats fell pregnant. Upon the single kit being born, it took up ID slot "1" when that was already assigned to a dead cat

**Grade**: Dire (Depending on how often it happens. Needs more testing)

**Reproduce**
1. Have a cat take up an ID outside of the initial starting cat IDs
2. Have a new cat be born (Or POTENTIALLY join, still need to test that)
3. Watch the old cat not exist anymore

**Commit # or Game Version Number**: 43448b39f91f8ed8e6c42d8418159d0437b116af

**Additional context**
This happened in a clan that has been having a lot of bugs from a cat giving birth to the cat who just got overwritten, to a dead newborn having a mentor with no ceremony. See my other two reports for the full context. #2414 and #2413 

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/3f341c38-950c-44f2-bf02-4e64064a5188)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/7a573b8d-a95a-4998-aec1-d35791214382)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/7f2fb0a9-5e1e-4303-a193-17556dafd598)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/d744ff1d-43c3-4dc7-8020-da2345ac2a20)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/5ce14ea9-1742-4010-ae64-15b0aa35b443)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/7a006a53-e148-4013-80d7-ae5c1174e8fe)

**Comment by ZtheCorgi** [comment]
for further context, nightriver was an outsider who joined the clan. i'm thinking there may be issues with how outsiders are being added to the clan currently

**Comment by ZrainydayXXX** [comment]
I had the issue again on a new clan. But they weren't loners/from outside the clan. They were two halfclan kits that died young. I did not screenshot them before they were gone but Popstar had two dead kits that have now disappeared.
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/0d485f9f-c914-4245-9f12-6cedb360afe5)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/5163fa4c-657c-4d4d-b779-0686ef6bbaf7)

(I only remember Leopardkit's name)

**Comment by j-gynn** [comment]
This is a result of #2408  - chances are good that this save is corrupted.

Yeah, this is an old commit - this should be fixed.

**Comment by archanyhm** [comment]
See the comment above. Reopen if persists.
