### ISSUE TITLE
[CODE] Adjust the display of leader death history

### ISSUE THREAD

**Issue by scribblecrumb** [ClanGenOfficial/clangen#2428]
**Description**
Currently, leader death history is displayed as one long run-on sentence (leader lost lives to [death], [death], [death], [death], and [death].)  It would be nice to change this to a single sentence for each death (Leader lost their first life to [death].  Leader lost their second life to [death].  Leader lost their remaining lives to [death].)

**Comment by Sumwatt0** [comment]
I think this issue should be closed.
