### ISSUE TITLE
[GITHUB] /assign-me feature broken

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2433]
**Type**: (only select one)
- Other (GitHub)

**Describe the bug**
GitHub /assign-me action workflow fails with "Cannot access resource."
[Recent action job that failed](https://github.com/ClanGenOfficial/clangen/actions/runs/9465737187/job/26075874926)

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. comment "/assign-me"
2. get Action workflow failure

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: N/A

**Comment by archanyhm** [comment]
I fixed the workflow; it should work as expected now.
