### ISSUE TITLE
[BUG] "FIERCE" AND "SCALE" clan symbols labeled as bird

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2439]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- 
**Describe the bug**
sorry if this isnt a bug but SCALE and FIERCE are listed under the 'bird' category in clan symbols which i dont believe should be correct?

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. make a clan
2. on the clan symbol screen, deselect all symbols except bird
3. see

**Commit # or Game Version Number**: efddf470bc5de0f463a8f75584a896eaf567c88c

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/bbeeef14-eaf2-4d7d-8237-edca70d33311)
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/c43232b2-4d1a-4c4f-bf25-60bb042c04e9)

**Comment by scribblecrumb** [comment]
Already fixed here: #2423

**Comment by selkirks** [comment]
> Already fixed here: #2423

oh rad, thank you so much!
