### ISSUE TITLE
[BUG] "event changed relationships but did not create a relationship log"

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2440]
**Type**: code

**Describe the bug**
repetitive warnings in Thonny when certain patrols finish

**Grade**: Non-vital

**Patrol ID + Outcome Print (if applicable)**:
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/932133b0-95a9-4064-81c3-7b8ef9c64305)

**Additional context**
will add more in comments on this thread as I find them, I notice them on a _lot_ of patrols

**Comment by peppst-r** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/48e1d5bc-3280-4273-a282-33eaaf657377)

**Comment by peppst-r** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/4ecc82f1-7e1e-4fc7-8bc0-f4572102e74d)
(deleted the original comment bc i thought it was the same one as the first post but the success outcome is different)


![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/e01adcd5-7b24-435a-bea7-506ea5f3b814)

**Comment by peppst-r** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/da648a77-a5bc-4860-a872-dff40f2871ff)
.
.
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/7daebdad-9146-4420-bc64-616d0e3ad8f0)
.
.
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/f9a064e7-3f07-4725-a874-05449af049b7)
.
.
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/8dafed8f-b131-4601-917f-46d5d0691ab4)

**Comment by scribblecrumb** [comment]
Not really a bug, this is known and intended behavior and doesn't really break anything.  Though it would be good for us to adjust the relationship utility to use the patrol outcome text in place of a log if no log was given in the patrol format.
