### ISSUE TITLE
[BUG] Retired cat thinks about retiring

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2444]
**Type**: Code

**Describe the bug**
Got an event where an elder (senior retired) is thinking about retiring. If I'm correct, this is an event typically reserved for leaders.

**Grade**: Non-vital

**Reproduce**
With at least one elder in your Clan, skip moons until you see this event.

**Commit # or Game Version Number**: 6c5f99b55

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/58bcf6a0-0834-41c4-942b-121bc04ef124)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/1cd30222-ad9e-4595-a7d8-106252f65b82)

**Comment by archanyhm** [comment]
@CL0WNTH0UGHTS Please re-try the command. It should work now.
