### ISSUE TITLE
[BUG] Events with invalid relationship tags

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2445]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
The following events have the given invalid tag on either `m_c` or `r_c`. If these are valid and I'm mistaken, sorry! Let me know and I'll A: change my code and B: remove them

```
----------------------------
m_c relationships incorrect
----------------------------
can_romance:
    gen_misc_accessoryapprentice1

---------------------------
r_c relationships incorrect
---------------------------
can_romance:
    gen_misc_accessoryapprentice1
mates:
    gen_new_cat_anypolymate1
```

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Comment by scribblecrumb** [comment]
Pretty sure this has been fixed, but reopen if that's not the case!
