### ISSUE TITLE
[BUG]Wrong Secret Murderer Listed

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2446]
**Type**: UI
**Describe the bug**
Had a moon event where there was a secret murder, went to look at the history and it listed that the cat was secretly murdered by themselves and not the actual killer. Don't know if this information is helpful, but the particular cat murdered had been invited into the clan moons earlier via the leader den. 

**Grade**: (only select one)
Regular

**Reproduce**
1. Get a moon event of a secret murder.
2. Look at history of murdered cat.

**Commit # or Game Version Number**: 
6c5f99b5

**Screenshots**
![2024-06-12 (1)](https://github.com/ClanGenOfficial/clangen/assets/149605071/07ed7f54-5ad9-4925-bfc2-4b83d310afc6)

**Comment by j-gynn** [comment]
So far, I've tracked it down to moonskip event murder generation - it looks like the victim is being hardcoded in as the killer on the text before it is then saved to their .json. Will continue to investigate.

**Comment by j-gynn** [comment]
Found it. `death_history` is run through `history_text_adjust`, which is expecting `m_c` to be describing the cat whose history we are looking at... but in murder histories, `m_c` is the murderer. Now to wait until I can get a murder to happen to check I've fixed it...
