### ISSUE TITLE
[BUG]Losing Leader and Going to Leader's Den Crashes Game

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2447]
**Type**: UI

**Describe the bug**
Lost a leader to this patrol: PATROL ID: mnt_bord_waterfall | SUCCESS: False along with another warrior. Went to click on the leader's den on the same moon and the game crashed.

**Grade**: Game-breaking

**Reproduce**
1.Get this patrol/lose the leader on patrol.
2. Click on leader's den on the same moon.

**Patrol ID + Outcome Print (if applicable)**:
PATROL ID: mnt_bord_waterfall | SUCCESS: False
Game crash:
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen\main.py", line 384, in <module>
    game.all_screens[game.current_screen].screen_switches()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\LeaderDenScreen.py", line 172, in screen_switches
    pygame.transform.scale(game.clan.leader.sprite, (300, 300)),
AttributeError: 'NoneType' object has no attribute 'sprite'

**Commit # or Game Version Number**: 
6c5f99b5

**Comment by PoppyBlossom** [comment]
I already fixed this in #2616
