### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wedel39** [ClanGenOfficial/clangen#2453]
- Code - general bugs related to how the game runs and responds to you. 
-
ex.: This bug makes the game not being able to open 

- Game-breaking - a bug that makes it impossible to play the game

1. Go to clangen fan edit folder
2. Click on  clanngen folder
3. Scroll down to clangen main and click it 

version 11.1

**Screenshots**

![Zrzut ekranu 2024-06-13 150618](https://github.com/ClanGenOfficial/clangen/assets/172592224/f0c2650c-87e3-49e7-af97-6c14897840ee)
![Zrzut ekranu 2024-06-13 150633](https://github.com/ClanGenOfficial/clangen/assets/172592224/d0b36900-2402-40ec-b412-e24799da1ca2)

**Comment by j-gynn** [comment]
Please re-read the README on GitHub carefully and follow the installation instructions. If you are still having problems after that, please join the Discord where you will be able to get help in `#players-helping-players`.

**Comment by archanyhm** [comment]
It seems you've edited your cat; the error message mentions troubles when decoding the cat. Therefore, not a bug.
