### ISSUE TITLE
[BUG] Typed text doesn't appear on first use

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2458]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
Will probably be fixed during the UI work going on, but I will raise it anyway.

The first time you try and type anything in the cat search box, it shows up empty. The moment you click off it, it appears. From then on, the box functions as expected.

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to cat list
2. Select search box
3. Type something
4. Lay thine eyes upon it and see that it is barren
5. Click off the search box
6. Ta da, it is back

**Commit # or Game Version Number**: [6dc3ac1](https://github.com/ClanGenOfficial/clangen/commit/6dc3ac1bcd130ea1dda78359dacb2070b1ddf33a)

**Screenshots**

https://github.com/ClanGenOfficial/clangen/assets/48025294/b538e665-a6dc-4110-9b44-8b067ccd172a

**Comment by j-gynn** [comment]
Thinking about it, this looks like it might be related to the bug reported with the text input box on the new clan screen. Running Win10.

**Comment by j-gynn** [comment]
This looks like it might be to do with the code that clears out the "name search" string, based on other unrelated adventures i'm having through PyGame

**Comment by scribblecrumb** [comment]
Fixed in #2419
