### ISSUE TITLE
[BUG] Loner Invite Crash

### ISSUE THREAD

**Issue by kiwiskaatzzz** [ClanGenOfficial/clangen#2474]
Type
- Code - general bugs related to how the game runs and responds to you. 

Describe the bug
This bug causes the game to freeze and or stop running. It occurs when attempting to invite a loner into your clan via the leaders den tab, then when trying to timeskip one moon the game freezes/crashes.

Grade:
- Dire - Still playable, but a major feature is broken

Commit # or Game Version Number: 
Dev Build 0.90

Screenshots
[Screen recording 2024-06-15 7.03.14 PM.webm](https://github.com/ClanGenOfficial/clangen/assets/140553534/baa5680a-4767-45bd-92d5-5ebcc3406cd0)

**Comment by PoppyBlossom** [comment]
The crash log wasn't very clear can you post the whole thing?

**Comment by scribblecrumb** [comment]
Closing as stale
