### ISSUE TITLE
Kit doesn't show up on Cats list normally.

### ISSUE THREAD

**Issue by gr4yroblox** [ClanGenOfficial/clangen#2483]
**Type**: UI (Possibly Code too[?] but I'm not exactly sure unfortunately)

So, my cat (leader specifically) brought back a litter of two kits. I went to the cat list, and one of the kits wasn't on the page, and there's only 1, it's not full, so it's not possible that the kit is on another page. Sorting by age up seems to have it finally show up on the list. Pressing the next cat button on Lightningkit's page pulls up Shalekit's profile. Using the search button on any sort by filter appears to have Shalekit show up. 

**Grade**: Regular
**Reproduce**
1. Have a cat have a litter.
2. Go to Cat List.
3. Kit does not show up in Cat List.

**Commit # or Game Version Number**: Dev Build 0.9.0 (Pull 2475)

**Additional context**
Kit seems to only show up on the age up arrow sort by filter WITHOUT searching, but for every other sort by filter, searching the name of the kit has it show up. This is also the first litter in the clan.
**Screenshots**
I am SO sorry for the large amount of screenshots, but most of them are for proof of the kit not being in any other section somehow
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/eb15de7e-eedf-479c-a52e-32cfb47bcd02)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/667f6f21-d75f-420b-8002-9d2e36920a12)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/db5336ea-c9d9-4281-a225-2dc992a5eacf)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/a7d1bb81-cff7-4390-bf04-ea9ab78ec472)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/f8bb7672-8923-428a-ab56-354c624e4d44)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/3cb1722e-713e-4433-ba45-f2110c79f78d)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/1cc01302-8b26-440c-8cb7-f01fb9b07215)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/b5a6f76b-6eb4-46b6-85c5-242dedca890f)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/1665759f-b95b-4a99-ade0-33fb666681ef)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/5f0b3108-6a11-4224-bb10-fc55bf23fcc9)
![image](https://github.com/ClanGenOfficial/clangen/assets/167941017/49253e53-689a-45e1-b0a8-db627f500f0a)

**Comment by j-gynn** [comment]
Hopefully this will be fixed by #2481 - we got one of the bugs, but there's another!

**Comment by ChaoticAlignment** [comment]
Type: UI?

This happened both when my leader/dep adopted some kits and a normal warrior had kits.

Grade: Regular (In both litters this clan has has this happened.)

Steps to reproduce the behavior:

Have a full row of cats and the a cat should adopt or birth a litter of kits.
Kits shouldn't be there.


Commit # or Game Version Number: 5ccf17b

Additional context
Kits will show up if you change depending on what you're sorting by. But it will remove another cat?

First Litter
![Screenshot 2024-06-18 150637](https://github.com/ClanGenOfficial/clangen/assets/122629099/a5543fcb-2334-4645-9537-6d79a260bde5)
![Screenshot 2024-06-18 150632](https://github.com/ClanGenOfficial/clangen/assets/122629099/a3c1a295-0123-45c2-8cd1-a6a96ef68234)
![Screenshot 2024-06-18 150802](https://github.com/ClanGenOfficial/clangen/assets/122629099/e7917b2c-d09f-44cf-aeb6-b6541e39a497)
![Screenshot 2024-06-18 150830](https://github.com/ClanGenOfficial/clangen/assets/122629099/cbf1103d-e535-48ba-929a-ac27005331d4)

Second Litter
![Screenshot 2024-06-18 151420](https://github.com/ClanGenOfficial/clangen/assets/122629099/d224da2b-b7ec-4611-a2ae-3dc15fc8d79a)
![Screenshot 2024-06-18 151407](https://github.com/ClanGenOfficial/clangen/assets/122629099/77c079c1-6c9a-45e1-8b0e-e9493c990386)
