### ISSUE TITLE
Firepaw got . on bch_bord_trackrogue6

### ISSUE THREAD

**Issue by ZrainydayXXX** [ClanGenOfficial/clangen#2485]
**Type**: Code

**Describe the bug**
When a cat is injured on a rogue patrol, the injury is not displayed. Only a .

**Grade**:
- Non-vital

**Reproduce**
1. Go on a border patrol (Not sure if it matters but I got it with a mentor and apprentice)
2. Get bch_bord_trackrogue6
3. Proceed and get the success: false outcome

**Patrol ID + Outcome Print (if applicable)**:

Patrol Leader: Morningstream
Random Cat: Firepaw
Total Number of Possible Patrols | normal: 12, romantic: 0 
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: ['app']
POSSIBLE STAT CATS []
No Stat Cat Found
---
starting chance: 40 | EX_updated chance: 65
Morningstream updated chance to 65 | Firepaw updated chance to 65 |
PATROL ID: bch_bord_trackrogue6 | SUCCESS: False
Firepaw ('2', 'lawfulness', -1)
Firepaw ('2', <SkillPath.SENSE: ('oddly observant', 'natural intuition', 'keen eye', 'unnatural senses')>, 3)

**Commit # or Game Version Number**: 

50c25beb7e46a14f5585e8485c378722031165de

**Screenshots**

![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/32fed364-6058-482f-84e9-24783e7ac1d6)
![image](https://github.com/ClanGenOfficial/clangen/assets/77426212/704b94db-92db-4c38-a022-21dbd8f11768)

**Comment by selkirks** [comment]
for more info for those who wanna look into this more: this occurs when a cat with a pre-existing minor condition goes on patrol and gets the same minor condition
