### ISSUE TITLE
[BUG] Cat dies defending another from a fox, history says they saved themselves

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2489]
**Type**: UI

**Describe the bug**
i'm aware [there is a similar issue with the "[cat] died defending [cat] from a badger" event](https://github.com/ClanGenOfficial/clangen/issues/2486), but the "fox" variant is also affected by this bug. the screenshots depict this happening to my leader, but it also happened to another one of my cats, i just reset over it so i didn't screenshot it. i believe it doesn't make a difference either way.

**Grade**: Regular

**Reproduce**
1. Moonskip until a cat dies defending another from a fox
2. Check their history

**Patrol ID + Outcome Print (if applicable)**: n/a

**Commit # or Game Version Number**: version 50c25beb

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/fc57c5cf-5af0-4cd0-be51-51526d39012d)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/b76b5967-40d0-4ea2-a764-13b8bb64b171)

**Comment by j-gynn** [comment]
I think this is similar to #2446 which I fixed earlier, so I'll check it out.
