### ISSUE TITLE
[BUG] Herb stores almost always wiped out at the same time as a pregnancy event

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2501]
**Type**: Code

**Describe the bug**
very, _very_ weird title, i know. but this has gotten me so frustrated and i find it hard to believe that it's bad rng because at this point this is ridiculous. almost every single time i get a pregnancy event (be it initial announcement, how many kits will probably be born and/or the actual birth) my herb stores are also completely wiped out, in the same moon. i have 7 screenshots here, but it's happened 4-5 more times before i actually started screenshotting everything, so in reality this has occured 11-12 times now. 
what confuses me, and what makes me have some glimmer of hope that this is just shitty luck, is that it's not _always._ there have been occassions where this just.. doesn't happen. but i want to make it known that the complete wipeout happens more often. like, _way_ more often. this clan is 131 moons old, and it's happened to me with - i'm pretty sure - _every_ single pregnancy i've had so far.

**Grade**: Important

**Reproduce**
1. Moonskip until a pregnancy is announced/amount of kits is revealed/kits are born
2. Check for the "medicine den wipeout" event

**Patrol ID + Outcome Print (if applicable)**: n/a

**Commit # or Game Version Number**: 2b4e3e9f

**Additional context**
it could be perfectly possible that this is not a bug, and just bad rng. but the fact it's happened 10+ more times is starting to worry me. if anyone is able to recreate this, either you have the same shitty luck as me, or this is actually a bug, lol. either way, i think i deserve some sort of award. /dramatic

**Screenshots**
(important note: this is NOT every time this has happened. 4-5 more times went undocumented. i also want to note, for some of these, i had to scroll a little to see the wipeout event after the pregnancy, so i edited both events together for practicality. still the same moon.)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/e6d6f175-1acd-4f4d-8b50-baedab143eda)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/c2e09e6d-fb97-4231-ab05-49e0ae707847)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/b49ccf8c-c1b9-48a4-9df5-d568d34ad4f0)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/eec59896-878f-40ed-8d74-33ef83cb31d6)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/26d76830-0a45-4f26-bb1d-40527ce3d156)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/ac5e700a-5bfc-4c71-ada4-d44af2651b3d)
![image](https://github.com/ClanGenOfficial/clangen/assets/172712347/fa86a2b3-43ca-4178-97d7-f46c817466d7)

**Comment by selkirks** [comment]
i feel like this just may be incredibly bad rng. played through a 100 moon clan, had 15 initial pregnancy events and 6 herb ruin events

on only one occassion did the pregnancy event and herb ruin event happem on the same moon

and for another 100 moon clan, i had 11 pregnancy events and 10 herb ruin events

likewise, on only one occassion did the pregnancy event and herb ruin event happen on the same moon

**Comment by scribblecrumb** [comment]
I can look into making these events less common, but as selkirks said, this is just bad RNG rather than a bug.
