### ISSUE TITLE
[BUG] pronoun scrollbars continously scroll

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2503]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
you can infinitely scroll both the vertical and horizontal scrollbars in the pronoun screen

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. make a lot of pronoun sets (at least 5)
2. scroll to ur hearts content

**Commit # or Game Version Number**: 7c03e8a4bf725e823d153f71bb4dcf58019fbeb8

**Screenshots**

https://github.com/ClanGenOfficial/clangen/assets/126827015/a56020a8-f4b9-4812-87bc-658ad5ebefb1

**Comment by scribblecrumb** [comment]
Seems to have been fixed, likely unintentionally in the fullscreen refactor.
