### ISSUE TITLE
[BUG] cat list still bugged

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2507]
**Type**: Code/UI
**Describe the bug**
missing two kits in cat list

**Grade**: Dire

**Reproduce**
Have more than 15 clan cats? I guess??

**Additional Context**
I have one cat living outside the clans, five starclan cats, and two unknown residence. If that affects cat list loading at all

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/f25c0e62-19d5-4b97-a76f-c928ddb3d8db)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/ce470b09-e8e6-4f89-bae5-8b3e242d56bb)

**Comment by j-gynn** [comment]
Thanks for putting in this bug report! #2481 should hopefully fix this once it gets merged in.

**Comment by j-gynn** [comment]
This should now be closed as the target PR has been merged. Recommend closing and to open a new ticket if issue recurs.
