### ISSUE TITLE
[CODE] Refactor `Personality.mentor_influence` to remove circular import

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2526]
**Description**
Basically, change `Personality.mentor_influence` so that its argument `mentor` is instead the mentor's personality. In doing so, fix the return so that it's no longer returning the mentor's ID (which it doesn't use or calculate and the calling function must have had to pass in the mentor `Cat` object).

**Comment by rustykitty** [comment]
@j-gynn, it looks to me like you did this yourself in https://github.com/ClanGenOfficial/clangen/commit/e91b4b10b464e9451a89956e8b5f963502ac7daf. Did you want a refactor of the mentor influence on SkillPath, or are you requesting something else?

**Comment by j-gynn** [comment]
...oops.
