### ISSUE TITLE
[BUG] new kits received same prefix

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2529]
**Type**: Code

**Describe the bug**
Two orphaned kits both received the prefix "Daisy"

**Grade**: Regular

**Patrol ID + Outcome Print (if applicable)**: gen_med_rescue10 
 
**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/6944d5eb-2e72-455e-b838-4d2f64afa848)

**Comment by ZtheCorgi** [comment]
to my knowledge, this may not be a bug, as i do not believe there is currently anything in place to prevent this from happening...? if it's not then this could potentially be a good enhancement, i think ^^

**Comment by selkirks** [comment]
> to my knowledge, this may not be a bug, as i do not believe there is currently anything in place to prevent this from happening...? if it's not then this could potentially be a good enhancement, i think ^^

https://github.com/ClanGenOfficial/clangen/issues/2277 was created to prevent this from happening. i suppose it doesnt account for non-clanborn kits

**Comment by ZtheCorgi** [comment]
ah, yeah, that's probably it. i must have missed that PR, thanks!
