### ISSUE TITLE
[BUG] Cat List still bugged? Page Arrows still not disabling?

### ISSUE THREAD

**Issue by JkHowling** [ClanGenOfficial/clangen#2546]
**Type**: Code

**Describe the bug**
The bugs fixed several PR's ago are still occurring, and quite consistently, even on the most recent updates to dev. This is a decently fresh download off clangen.io, updated today.

**Grade**: Dire

**Reproduce**
1. Have a new cat join the clan.

**Commit # or Game Version Number**: 3c0f4ab5

**Additional context**
It's quite consistent, occurring, without fail, any time a new cat is generated; whether a kit is born, a loner joins, a patrol finds someone, etc. And once they join, the page arrows bug out again.

**Screenshots**
![image](https://i.imgur.com/0ekiDif.gif)

**Comment by JkHowling** [comment]
A brand new download no longer seems to happen, so it seems to occur only via updating through the game's launcher? I have no idea. Maybe its tied to the issue with the game files cloning themselves when updating?

**Comment by scribblecrumb** [comment]
https://github.com/ClanGenOfficial/clangen/commit/3c0f4ab506b53b6ce16e6af1b2111184fda2fcb4 is also a commit from a couple days ago.  I'm inclined to think this is some weird issue with git or the auto updater, rather than a problem with the cat list code.
