### ISSUE TITLE
[BUG] dead cat relationships not disappearing after 'show dead' is turned off

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2547]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
sorry if this is a limitation or anything! basically when you go to a cat's relationhips page and click 'show dead' then turn it off, dead cats still appear. once again, unsure if this is a limitation or not. going to another page gets rid of the dead cat relationships, as it shld

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. go to a kitty cat relationships page
2. click show dead
3. turn show dead off
4. profit

**Commit # or Game Version Number**: 3c0f4ab506b53b6ce16e6af1b2111184fda2fcb4

**Screenshots**

https://github.com/ClanGenOfficial/clangen/assets/126827015/5adcd128-b153-47ee-aa42-878b3e5329d3

**Comment by DeadGirlRisen** [comment]
I swear I brought this up before.

But yeah, it'll only toggle the update when you also toggle show empty /info

def a bug that needs to be fixed
