### ISSUE TITLE
[ENHANCEMENT] newborns are not tagged in moon event

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2548]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
on certain moon events, newborns are not tagged in them as they should be. i provide an example of an event tagged properly with newborns and one that doesnt tag them

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moon skip till a cat brings in kits
2. check if the kits are tgaged in the moon event or not

**Commit # or Game Version Number**: private dev branch but is completely up to date (and confirmed to be a general dev issue)

**Screenshots**
kit not tagged: 
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/cf3db270-cb66-404d-9fd8-ef0d7cc22deb)
kit tagged: 
![image](https://github.com/ClanGenOfficial/clangen/assets/126827015/42ecffba-383a-4f14-8361-d5611e51bc8a)

**Comment by keyraven** [comment]
Newborns are not tagged birth events due to limitations regarding how many tagged cats can fix on the event. Since there can be 4+ kittens born in a single litter, that's 6 total cats tagged, which would overflow the box.  Kits shouldn't have been tagged in your second example - that appears to be the actual oversight.

**Comment by selkirks** [comment]
...bug report failed successfully? /silly /ref

**Comment by scribblecrumb** [comment]
> Newborns are not tagged birth events due to limitations regarding how many tagged cats can fix on the event. Since there can be 4+ kittens born in a single litter, that's 6 total cats tagged, which would overflow the box. Kits shouldn't have been tagged in your second example - that appears to be the actual oversight.

@keyraven With the changes I've made in #2545 we no longer have to worry about that box overflow!  So we can indeed start tagging all the kits in the events.

**Comment by scribblecrumb** [comment]
Changed title to ENHANCEMENT as this is more of a QoL change than a bug in the system.  Either way, it would be a quick change to make for anyone who would like to handle this.
