### ISSUE TITLE
[BUG] Game crashes when skipping a moon

### ISSUE THREAD

**Issue by everythinn** [ClanGenOfficial/clangen#2555]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Game crashes after trying to skip a moon when a cat in the Clan is deaf

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Have a deaf cat
2. Attempt to skip a moon

**Game Version**: v0.11.2

**Additional context**
The game ran fine for a few moons after the cat became deaf, until it became hurt in the ear again. I think it might've been caused by the script intending to have an event where that second injury made the cat deaf but since it already was it crashed ? Just a guess though.

**Screenshots**
![Capture d'écran 2024-06-25 202022](https://github.com/ClanGenOfficial/clangen/assets/103243345/195a9412-e71c-4a07-b844-2f0d70c17007)

**Comment by j-gynn** [comment]
Looks like there's a key error in `possible_string_list = Condition_Events.PERMANENT_CONDITION_GOT_STRINGS[injury][condition_got]`.

It'd be great to get the error log for this bug if possible - the screenshot only shows half of the traceback and unfortunately it's the less-useful half(...!).

**Comment by scribblecrumb** [comment]
Closing as stale
