### ISSUE TITLE
[BUG] game does not open / crashes command prompt immediately

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2562]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
I am unsure if this is a ClanGen/dev version/game bug in general or if it is just my computer, but it's been happening for a long time and idk how to stop it. I download the dev version from the website, extract the files to my desktop, and click the clangen application for it to open. It works for a while, but sometimes it will randomly stop opening, and I have to go into the nested _internal folder and open that clangen application. Eventually it happens to all like 3 nested applications and I have to delete everything and redownload the dev version again.

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
I am unsure how to reproduce, as it happens at random for me. Someone once suggested to run the .exe from command prompt as a filepath to see if it gives an error message, and this is what it said.
<img width="611" alt="errormessagecrash" src="https://github.com/ClanGenOfficial/clangen/assets/172937440/5398bb4b-503b-41e7-80ca-ba6be796a3ee">

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: Dev Build 60fefd79, but it has been going on for quite a while/with past versions too

**Additional context**
N/A

**Screenshots**
Video of what I experience trying to open the ClanGen application from my desktop folder. Sorry for the link, it won't let me add the video directly for some reason. If the google drive link cannot be viewed, please let me know and I can send it directly over Discord if needed.
https://drive.google.com/file/d/10fyOyYOHERo9lSLwip8JXF5L5iKjtn-j/view?usp=drive_link

**Comment by scribblecrumb** [comment]
Duplicate
