### ISSUE TITLE
[BUG] Strange error saying the leader died

### ISSUE THREAD

**Issue by Hammy-Sammy** [ClanGenOfficial/clangen#2564]
It was a typo saying: "Foreststar lost a live to deaf."
![Screenshot (151)](https://github.com/ClanGenOfficial/clangen/assets/174381170/d9e72de9-8955-42ce-ba6a-15baafbadc99)
When I checked Foreststar it said they still had 9 lives
![Screenshot (152)](https://github.com/ClanGenOfficial/clangen/assets/174381170/6db28eaf-4d8d-47dd-b585-c9ec175c6a30)
I was playing Lifegen but I reported it to the Discord, and they said it was a Clangen bug, so I'm reporting it here.

**Comment by Patricia-Berges** [comment]
This bug was already fixed in dev version!

**Comment by KiraDragoness** [comment]
This bug was already fixed in dev version!

**Comment by ZtheCorgi** [comment]
in future, please don't report bugs that you get in lifegen, even if they tell you in the server it's from base game. lifegen is not up to date with current clangen dev and bugs you find there will almost never be relevant to clangen unless you can reproduce them in the current dev version! /info

**Comment by Hammy-Sammy** [comment]
ok ty!!!
