### ISSUE TITLE
[BUG]  Missing buttons

### ISSUE THREAD

**Issue by pumpkinstep** [ClanGenOfficial/clangen#2571]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**

The navigation buttons on the cat list screen are missing. The button to go to starclan works but it is invisible, all other location buttons are missing entirely. Cat search and favorites star is still present. 
All other buttons are still present and unaffected as far as i can tell. 

This happened after reinstalling the game

**Grade**: (only select one)

- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**

unfortunately i'm not quite sure how to reproduce the bug.

Hopefully this info helps:

I had lost/maybe accidentally deleted the original folder a long time ago and recently downloaded a new folder off of the website. I didn't delete the folder that contains the save files and the like, just the main file the application is kept in. 
Ive done this a few times before but this is the first time i've come across this issue.

I'm sure the problem will go away if i back up my saves and do a fresh clean install, but i was told i'd be a good idea to report this bug.

**Screenshots**
<img width="599" alt="Screenshot 2024-07-02 183355" src="https://github.com/ClanGenOfficial/clangen/assets/174563081/2039d5d1-1439-4b25-b603-b281ee96455a">
i couldn't capture the cursor but its right next to the search bar

**Comment by scribblecrumb** [comment]
Not sure what's up here, but with the recent UI changes this likely isn't relevant anymore.
