### ISSUE TITLE
[BUG] "Dens" button sometimes gets carried to camp view

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2573]
**Type**: UI

**Describe the bug**
I've noticed the "Dens" button stays when you go from the cat list or the allegiances pages to the camp page, when it should disappear instead. Going to camp view from other pages like events make it disappear as intended. If you try to click it from the camp view, it doesn't do anything.

**Grade**: Non-vital

**Reproduce**
1. Go to the cat list or the allegiances page.
2. Change directly to the Camp page.
3. Look at the top left corner to verify if the Dens buttons is there.

**Commit # or Game Version Number**: 3657f1307

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/2389c9b2-4250-4eb8-b210-e24f7fabe04e)

**Comment by j-gynn** [comment]
Seems to have been fixed by fullscreen changes, senior devs please close unless it can be replicated
