### ISSUE TITLE
[BUG] Cannot create clan, crashes when symbol is selected

### ISSUE THREAD

**Issue by carlean101** [ClanGenOfficial/clangen#2574]
Type: Coding bug(?)

Description:
When 

Grade: Game-breaking

Steps to reproduce:
1. Launch game
2. Create new clan
3. Choose clan name, cats, and map
4. On symbol selection screen, choose symbol or randomize
5. Instant crash

Version:
Dev 0.9.0

Notes:

- Crash is not impacted by the choice of classic mode or expanded mode
- Crash is not impacted (as far as I can see) by the selected name, cats, or map
- Crash does not occur when "Quick Start" is chosen

Error Log:
root - CRITICAL - main.py / log_crash / 117 - Uncaught exception
Traceback (most recent call last):
  File "main.py", line 338, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\username\Downloads\clangen-development\clangen-development\scripts\screens\MakeClanScreen.py", line 186, in handle_event
    self.handle_choose_symbol_event(event)
  File "C:\Users\username\Downloads\clangen-development\clangen-development\scripts\screens\MakeClanScreen.py", line 552, in handle_choose_symbol_event
    self.refresh_text_and_buttons()
  File "C:\Users\username\Downloads\clangen-development\clangen-development\scripts\screens\MakeClanScreen.py", line 794, in refresh_text_and_buttons
    symbol_name = self.symbol_selected.removeprefix("symbol")
AttributeError: 'str' object has no attribute 'removeprefix'

When starting on quick start, this error is thrown in the console for every npc clan that is generated upon clan creation:
WARNING: attempted to return symbol string, but there's no clan symbol for (CLAN NAME).  Random symbol string returned.

Not sure why I haven't seen anybody else post about this because it seems like a pretty serious issue. Is it just a me problem? When launching the game, the console tells me that I'm not missing or outdated in any dependencies. Any solutions?

**Comment by selkirks** [comment]
unable to recreate this on the most recent version. are you sure you arent on a modded game? additionally, 0.9.0 hasnt been a recent dev build for... a While

**Comment by DeadGirlRisen** [comment]
> unable to recreate this on the most recent version. are you sure you arent on a modded game? additionally, 0.9.0 hasnt been a recent dev build for... a While

Thisbonly seems to happen to some users, Ive noticed it happens more in builded versions from moss mod, then from non builds. It seems to happen to a good amount of people though, but Ive not figured out why.

Idk if OP was using moss mod build or something else  but I know Anju (Or Zabe, cnat remember which rn) had gotten it before on the normal dev. 

Hope this information is somewhat helpful.

**Comment by ZtheCorgi** [comment]
wasn't me. i haven't been able to play clangen since before custom pronouns were merged into dev due to health problems

**Comment by selkirks** [comment]
> > unable to recreate this on the most recent version. are you sure you arent on a modded game? additionally, 0.9.0 hasnt been a recent dev build for... a While
> 
> Thisbonly seems to happen to some users, Ive noticed it happens more in builded versions from moss mod, then from non builds. It seems to happen to a good amount of people though, but Ive not figured out why.
> 
> Idk if OP was using moss mod build or something else but I know Anju (Or Zabe, cnat remember which rn) had gotten it before on the normal dev.
> 
> Hope this information is somewhat helpful.

ooh yes this did happen to anju before, i remember that. thats so odd

**Comment by carlean101** [comment]
> unable to recreate this on the most recent version. are you sure you arent on a modded game? additionally, 0.9.0 hasnt been a recent dev build for... a While

what?? is it not the most recent dev version with the unreleased symbols, leader's den, and warriors' den features?? and yes, this is unmodded, i downloaded the development zip straight from here.

**Comment by selkirks** [comment]
> > unable to recreate this on the most recent version. are you sure you arent on a modded game? additionally, 0.9.0 hasnt been a recent dev build for... a While
> 
> 
> 
> what?? is it not the most recent dev version with the unreleased symbols, leader's den, and warriors' den features?? and yes, this is unmodded, i downloaded the development zip straight from here.

if its just the zip and not through github, then im not sure (i dont play via zips). ive asked scribble though, as this bug has been reported (tho not reported as a github issue) before, to see if theres any fix

edit: zips are built diff. inchresting. still though, unable to replicate on 0.9.0 dev

**Comment by carlean101** [comment]
> if its just the zip and not through github, then im not sure

What do you mean by this? I downloaded the development zip from github, how are you playing the game? Am I playing it incorrectly?
I have met several other people who face this same issue which is why I'm concerned that it hasn't been addressed before, sure hope that it's fixed soon

**Comment by archanyhm** [comment]
@carlean101 Please update the version to reflect the actual commit hash or version number. To retrieve said commit hash, clone the repository by using git (or a git GUI like GitHub desktop) or download the development build from the website via https://clangen.io/download-development

**Comment by archanyhm** [comment]
Since no update was given within two weeks, I'll close this as stale issue.
