### ISSUE TITLE
[BUG] Missing something for dev version?

### ISSUE THREAD

**Issue by elias777777777** [ClanGenOfficial/clangen#2580]
it keeps saying i’m missing something for the dev version? but i have everything downloaded i believe.

**Comment by KiraDragoness** [comment]
Could you share a capture of the message? Otherwise it's difficult to know what the problem is without more information.

**Comment by archanyhm** [comment]
@elias777777777 If you're missing requirements, I'd advise you to read the README.md thoroughly as we don't offer support for running source versions of the game beyond our documentation.
