### ISSUE TITLE
[BUG] Cat deaths not listed in moon events

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2582]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Certain cats are not given specific/individual death entries in the moon events, but are said to have gone to StarClan ain the end entry. In my screenshots, it says Mossfur, Wildpaw, and Dewpelt have taken their place in StarClan, but Mossfur is the only one that has their death described or pointed out. They are in fact dead though, as they are gone from the cat list.

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
Unsure how to reproduce, it just happened. (Sorry :/)

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: Dev Version: cfcf13b8

**Additional context**
N/A

**Screenshots**
<img width="424" alt="missingdeaths1" src="https://github.com/user-attachments/assets/997a4a97-efbd-4b1e-9abe-60785e4fc31e">
<img width="422" alt="missingdeaths2" src="https://github.com/user-attachments/assets/e5037599-8057-4aa5-9f54-d9de6390631a">
<img width="427" alt="missingdeaths3" src="https://github.com/user-attachments/assets/68c4ddfc-06bc-43f3-8dee-bd3896d44c98">

**Comment by KiraDragoness** [comment]
This is already reported! It's a problem with the Twoleg mass-extinction event, that kills cats that are not mentioned in the text #2463

**Comment by mirandarts** [comment]
oops, my bad! i scanned the board to see if it had been reported but i guess i missed it ;^^

**Comment by scribblecrumb** [comment]
closing as it's a duplicate
