### ISSUE TITLE
[BUG] Half-Clan and Outsider roots kits getting the wrong backstory

### ISSUE THREAD

**Issue by Saline-fin** [ClanGenOfficial/clangen#2586]
**Type**:
- Code - general bugs related to how the game runs and responds to you.

**Describe the bug**
I had a male cat give birth to half-clan kits and the kits have the backstory which suggests that they were brought into the clan rather than born in the clan. (Quick extra note: I've had this happen both on stable and dev. I just have Moss Mod Lite thrown on as well.)

**Grade**: 
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Have 'ignore biology' and 'allow cats to have kittens with a second unknown parent' on
2. Skip until a male cat is pregnant
3. Skip until the cat gives birth to half-clan or outsider roots kits
4. Check the history of the kits

**Commit # or Game Version Number**:
Commit: cfcf13b82223580546ec6f4846bbd56fe90302e5

**Screenshots**

https://github.com/user-attachments/assets/498ec241-45e6-40c2-8abb-e9f8d7312616
https://github.com/user-attachments/assets/3ca5211b-ac4e-4360-90c2-48d2ec7a5844

**Comment by scribblecrumb** [comment]
I don't know that this can be easily fixed atm.  With how we have it set up, we don't mark either parent as being the "birthing" parent.  So when biology is ignored and a halfclan litter is generated, we don't know if the male was the birthing parent or not.  Right now it's set up to just always assume the female is the birthing parent.  We would need to rework the `get_kits` function to be capable of making the distinction.

EDIT: nevermind!  zabe made the wonderful suggestion of checking the parent's condition status if it hasn't been removed yet.  solution was made by checking if the parent had the pregnant condition or not.
