### ISSUE TITLE
[BUG] Medicine cat has apprentice patrol without apprentice

### ISSUE THREAD

**Issue by deadpaan7391** [ClanGenOfficial/clangen#2589]
**Type**: Code

**Describe the bug**
A medicine cat sent on patrol alone had a text box for a patrol with an apprentice.

**Grade**: Unimportant

**Reproduce**

Patrol with a solo medicine cat and it may occur again. I'm unsure how common this is as it's only happened to me once.

**Screenshots**
![Screenshot 2024-07-23 225958](https://github.com/user-attachments/assets/9998226d-facb-4133-a943-b66456350830)

**Comment by j-gynn** [comment]
Reproduced on dev, will investigate.

**Comment by j-gynn** [comment]
Actually, no... I can't replicate this on development. I **can** if I use `debug_ensure_patrol_id`, but that ignores the game's selection process now by default (Not sure it should do this in the way that it does...). From what I can see from manually checking, this event can't appear in normal gameplay.

**Comment by PoppyBlossom** [comment]
> Actually, no... I can't replicate this on development. I **can** if I use `debug_ensure_patrol_id`, but that ignores the game's selection process now by default (Not sure it should do this in the way that it does...). From what I can see from manually checking, this event can't appear in normal gameplay.

@j-gynn It shouldn't ignore any selection processes if debug_override_patrol_stat_requirements is set to false.
I will gladly fix any problems I have created.

**Comment by scribblecrumb** [comment]
Stale, please reopen if encountered again
