### ISSUE TITLE
[BUG] History crash

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2591]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
One of my cats just really likes to crash the game when I try to look at his history. I've crashed my game like seven times trying to figure out what exactly is going on. 
I originally thought it was crashing because he died saving a cat who has now faded. However, on a different clan, save file editing in the same death and fading a cat, it didn't crash, so now I'm not sure. 

**Grade**:
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
I don't actually know. If I definitively figure out what's causing this, I'll update this section to reflect that. 

**Commit # or Game Version Number**: cfcf13b8

**Additional context**
This was originally reported by ServalBones on discord, who had a similar crash specifically when turning on the "view moon" setting in a murdered cat's history. While trying to reproduce it, I got this crash, which I think is slightly different but I'm not completely sure. 

**Screenshots**
crasher of games: 
<img width="603" alt="Screenshot 2024-07-27 at 12 00 16 AM" src="https://github.com/user-attachments/assets/4eb085c6-7475-45eb-b121-d54eae4a374d">
crasher of games' history file: 
<img width="600" alt="Screenshot 2024-07-27 at 12 05 50 AM" src="https://github.com/user-attachments/assets/b17f07d5-16fa-4e2a-9a51-91568933faa3">
crash log: 
<img width="620" alt="Screenshot 2024-07-27 at 12 06 30 AM" src="https://github.com/user-attachments/assets/e087d7b7-2892-4b08-a484-3cf1fc829b50">

ServalBones' original bug report: 
<img width="627" alt="Screenshot 2024-07-28 at 4 09 18 PM" src="https://github.com/user-attachments/assets/730c4060-0fa5-4b77-9e89-72c77edd5548">
History file from that cat: 
<img width="627" alt="Screenshot 2024-07-28 at 4 10 26 PM" src="https://github.com/user-attachments/assets/4f5b00a3-e379-4744-a71a-52283a55c095">
<img width="627" alt="Screenshot 2024-07-28 at 4 10 51 PM" src="https://github.com/user-attachments/assets/0251beca-c85e-455e-b7b6-b1b992527a8d">
crash log: 
<img width="627" alt="Screenshot 2024-07-28 at 4 11 28 PM" src="https://github.com/user-attachments/assets/1dd38087-ee7b-4724-8355-125dd24ae956">

**Comment by PoppyBlossom** [comment]
Thank you for opening this issue. From the crash log you provided it seems like it's trying to get the r_c(random cat)'s pronoun but failed, I assume the choice function received null which caused the crash. I'm going to try recreating the crash.

**Comment by PoppyBlossom** [comment]
In cfcf13b when a cat fades it sets its pronoun to an empty array _(script/cat/cats.py line 371)_  which explains the 'cannot choose from an empty sequence' part of the crash log.

**Comment by ZtheCorgi** [comment]
none pronouns with left crash....

**Comment by ngbb2012** [comment]
> In https://github.com/ClanGenOfficial/clangen/commit/cfcf13b82223580546ec6f4846bbd56fe90302e5 when a cat fades it sets its pronoun to an empty array  

Nevermind that was just the constructor

**Comment by PoppyBlossom** [comment]
Here's a breakdown of the problem
1. cat faded, script/game_structrue, line 476 creates a simplified version of the cat's info, which has an empty array for pronouns
2. trying to read the faded cat's pronoun information using the function choice in script/utility, line 2005, which resulted in a crash.

possible fix: there is no simple way around this unless changing the way the faded cat's info is preserved. Or we can use gender-neutral pronouns, it's better than crashing.

**Comment by PoppyBlossom** [comment]
I managed to replicate this crash. Follow these steps: Find a cat and modify the "die_by, text" in its history file to something like "m_c died of old age because of r_c." Make sure to specify an ID of a faded cat from the "faded_cats" folder in the "involve" field. After making these changes, run the game and check the cat's history. The game will crash as a result.
![image](https://github.com/user-attachments/assets/fc473f2d-c4fc-4ec3-b88b-7b7d1312f582)

**Comment by PoppyBlossom** [comment]
@LaurelWillow thank you for the infomations! If you don't mind you can make ServalBones's bug report a separate issue since they are quite different.

**Comment by LaurelWillow** [comment]
Yup I can do that! 
Thankful my guy Fincrest will no longer be a gamebreak hazard 👍
