### ISSUE TITLE
[BUG] Game crashes on moonskip (ceremony related?)

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2597]
**Type**: Code

**Describe the bug**
I was playing normally and the game just keeps crashing on moonskip. I cannot progress anymore. I have no idea why it's crashing - the only save file editing I'd done recently was changing the amount of dead moons for some cats so they'd fade quicker, but I doubt that's the issue as the crash log seems to mention a ceremony of some sort? At first I theorized it might be because I'm trying to invite in an outsider (I saw a similar crash before somewhere) so I tried moonskipping without inviting them and it crashed anyway, but the crash log was slightly different (highlighting different lines as the source of the error). Since I have absolutely zero idea what's going on, I've attached my save file + the two different crash logs I've gotten.
_stderr_20240729_124228_ is the log I got when trying to invite the outsider, and _stderr_20240729_124309_ is the log I got when I moonskipped without doing so.

**Grade**: Game-breaking

**Reproduce**
To be completely fair I have no clue. At first I thought it was a random crash since I rebooted the game and it worked fine, but now it just doesn't work at all. It keeps crashing.

**Commit # or Game Version Number**: cfcf13b8

**Additional context**
Weirdest crash I've ever encountered so far, I'm completely stumped as to how or why this is happening. Sorry for the lack of instructions on how to reproduce it but I am absolutely clueless.

**Screenshots**
![image](https://github.com/user-attachments/assets/e10c7ff4-364f-409a-9925-2be7a7eb684e)
(unsure if clan age is relevant, but I'll put it here.)

Attached is my save file + the crash logs.
[Ember.zip](https://github.com/user-attachments/files/16417054/Ember.zip)
[stderr_20240729_124228.log](https://github.com/user-attachments/files/16417068/stderr_20240729_124228.log)
[stderr_20240729_124309.log](https://github.com/user-attachments/files/16417070/stderr_20240729_124309.log)

**Comment by j-gynn** [comment]
This appears to be to do with that save editing. The parent of Daisypaw is a faded cat, so when the game tries to call the apprentice graduation ceremony, it fails. It tries to get the parent's pronouns - but the cat is faded, so they're no longer stored.

Thank you for adding the save file, that made this a super-quick check!

**Comment by Vickarooni** [comment]
ooh i see! thank you so much!!! i think i can fix that  by manually making them a warrior and skipping that whole process. appreciate it :)

**Comment by PoppyBlossom** [comment]
Oh, I fixed this in #2613. If it's in the event_text_adjust function.

**Comment by PoppyBlossom** [comment]
Never mind. I think I can still fix this using the same method though

**Comment by PoppyBlossom** [comment]
Fixed it.
![image](https://github.com/user-attachments/assets/2315a2af-ee38-47ac-be35-0fa5cfe0c385)
