### ISSUE TITLE
[BUG] Dens button remaining on screen after leaving events page

### ISSUE THREAD

**Issue by ArtemisEnby** [ClanGenOfficial/clangen#2599]
**Type**: UI

**Description**: The dens button remains on screen after entering the events page and going to any other page. If you switch between pages a bit it goes away again, but if you open the events page again it reoccurs.

**Grade**: Unimportant

**Reproduce**: Go to the events page, then return to the camp/cat list/patrol page.

**Commit # or Game Version Number**: cfcf13b82223580546ec6f4846bbd56fe90302e5

**Screenshot**
![image](https://github.com/user-attachments/assets/28a072f1-87bc-4a27-847e-4e9e978c71a6)

**Comment by KiraDragoness** [comment]
Already reported in #2573 and waiting for the fix #2572 to be approved^^

**Comment by scribblecrumb** [comment]
duplicate
