### ISSUE TITLE
[BUG] Patrol: All the wrong cats get lost

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2604]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
In this patrol, one cat wanders forwards with their patrol, but they escaped while the rest of the patrol was captured. 
I don't know if this is intended or not, but it doesn't make a whole lot of sense to me. 

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
Send out four-cat border patrols until you fail the patrol bch_hunt_gonetnr3 such that the stat cat doesn't get lost. 

**Patrol ID + Outcome Print (if applicable)**: bch_hunt_gonetnr3
<img width="626" alt="Screenshot 2024-08-02 at 2 13 18 AM" src="https://github.com/user-attachments/assets/8877f6d1-6367-4cb6-9533-7558c8c322b5">

**Commit # or Game Version Number**: fafb44a8

**Screenshots**
<img width="697" alt="Screenshot 2024-08-02 at 2 09 39 AM" src="https://github.com/user-attachments/assets/6005d1e0-4c97-428c-9dc1-30df2f855df3">

**Comment by arisaema12** [comment]
didn’t realise you had to mark issues as fixed in pull requests ^^” but this can be closed now!
