### ISSUE TITLE
[BUG] Game crashes when going to the leader's den without one

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2607]
**Type**: Code

**Describe the bug**
What it says on the tin. I have a clan where I'm only starting out with one kit, therefore the clan does not have a leader. Clicking on the "leader's den" button crashes the game. I feel like this could be fixed by adding a special message like "[clan] does not have a leader!" or something, similar to what happens with the medicine cat den when you have no medicine cats.

**Grade**: Regular

**Reproduce**
1. Remove the leader by demoting, erasing them from the save, etc
2. Click on the leader's den

**Commit # or Game Version Number**: 7b48f10b

**Additional context**
I am aware the game displays the deputy if the leader is unable to work, and the medicine cat if both are incapacitated - since the Clan I experienced the crash with does not have either of these, I am unsure if the game also crashes if you have a deputy/med cat but no leader. Might be worth looking into?

**Screenshots**
the singular kitten..
![image](https://github.com/user-attachments/assets/a2e771ac-ec5e-4444-9448-4076c9d83e82)

**Comment by scribblecrumb** [comment]
Do you have the actual error message from the crash?  The leader's den can already handle a variety of leadership configurations, all the way down to a clan that has died out and has 0 cats.

**Comment by LaurelWillow** [comment]
I was able to reproduce this crash, just by demoting the leader and then trying to click leader's den. here's the error log
<img width="512" alt="Screenshot 2024-08-04 at 10 22 26 AM" src="https://github.com/user-attachments/assets/90f78f06-165b-44d5-82b6-ac57fbadc30f">

**Comment by scribblecrumb** [comment]
Ah interesting.  It seems killing them doesn't trigger the crash (which is how i tried to replicate), only demoting.

**Comment by Vickarooni** [comment]
> The leader's den can already handle a variety of leadership configurations, all the way down to a clan that has died out and has 0 cats.

really? i just tried setting the kit to be dead so the clan dies out and the game crashes anyway ^^" i was curious to see the message but i must've done it wrong

**Comment by PoppyBlossom** [comment]
I think I can fix this.

**Comment by PoppyBlossom** [comment]
> Ah interesting. It seems killing them doesn't trigger the crash (which is how i tried to replicate), only demoting.

Killing doesn't work because game.clan.leader still exists _(just with a dead flag),_ but if you demote the leader, then game.clan.leader will be None which is what caused the crash.
