### ISSUE TITLE
[BUG] Running Nose Text Not Visible

### ISSUE THREAD

**Issue by kays2point0** [ClanGenOfficial/clangen#2609]
**Type**: Typo 

**Describe the bug**
The text informing the player that a cat has contracted a running nose after hunting during newleaf (mountainous biome) does not appear in the sentence, instead showing "[Cat] got ." 

**Grade**: Unimportant - This bug has little to no impact on play. 

**Reproduce**
-> 49 Moons, Newleaf, Mountainous Biome
1. Go to 'Patrol'
2. Click on '+1 Random Warrior'
3. Click on 'Hunting Patrol Type'
4. Click 'Go on Patrol'
-> Correct Patrol ID (Listed Below)
5. Click 'Proceed'
-> Fail Patrol, Gain "Running Nose"
6. See error

**Patrol ID + Outcome Print (if applicable)**: gen_hunt_hugeprey_balancing_solowarriorhunt1 | SUCCESS: False
> PATROL START -
> Patrol Leader: Acorntrail
> Random Cat: Acorntrail
> chosen filter prey size: very_small
> Total Number of Possible Patrols | normal: 1, romantic: 0 
> 
> Finding stat cat. Outcome Type: Success = True, Antag = False
> Can Have Stat: ['p_l']
> POSSIBLE STAT CATS ['Acorntrail']
> No Stat Cat Found
> 
> starting chance: 50 | EX_updated chance: 88
> Acorntrail updated chance to 88 | 
> PATROL ID: gen_hunt_hugeprey_balancing_solowarriorhunt1 | SUCCESS: False
> PATROL END -

**Commit # or Game Version Number**: v0.11.2 , Expanded

![Screenshot 2024-08-05 020211](https://github.com/user-attachments/assets/c7d10836-78f2-4f10-951f-543534322687)
![Screenshot 2024-08-05 020933](https://github.com/user-attachments/assets/0ae2df88-227c-4701-969f-87ff5814410d)

**Comment by j-gynn** [comment]
This is a known bug that has been fixed in the latest development branch :) Thank you for letting us know!
