### ISSUE TITLE
[BUG] History crash when clicking the "view moon" button

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2614]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Crash when clicking the "view moon" button in a dead cat's history- originally reported by ServalBones on discord. 

**Grade**: (only select one)
- Game-breaking 

**Reproduce**
Unsure as I have not been able to reproduce this personally. Definitely involves clicking the "view moon" button in the history tab. 

**Commit # or Game Version Number**: Stable 11.2

**Additional context**
Crash occurred with fading turned off, so no faded cats are involved. 

**Screenshots**
ServalBones' original bug report: 
<img width="627" alt="Screenshot 2024-07-28 at 4 09 18 PM" src="https://github.com/user-attachments/assets/730c4060-0fa5-4b77-9e89-72c77edd5548">
History file from that cat: 
<img width="627" alt="Screenshot 2024-07-28 at 4 10 26 PM" src="https://github.com/user-attachments/assets/4f5b00a3-e379-4744-a71a-52283a55c095">
<img width="627" alt="Screenshot 2024-07-28 at 4 10 51 PM" src="https://github.com/user-attachments/assets/0251beca-c85e-455e-b7b6-b1b992527a8d">
crash log: 
<img width="627" alt="Screenshot 2024-07-28 at 4 11 28 PM" src="https://github.com/user-attachments/assets/1dd38087-ee7b-4724-8355-125dd24ae956">

**Comment by PoppyBlossom** [comment]
I checked the latest development branch, and this issue has already been fixed and should no longer occur (after the next release).
new:
`
    name_list.append(f"{name} (Moon {victim_names[name][0]})")
`
old:
`
    name_list.append(name + f" (Moon {', '.join(victim_names[name])})") # This is where the crash happened
`

**Comment by PoppyBlossom** [comment]
This issue can be closed now :)

**Comment by j-gynn** [comment]
@scribblecrumb Can we get this issue closed as it seems resolved?

**Comment by scribblecrumb** [comment]
hell yes
