### ISSUE TITLE
[BUG] Patrol ends unexpectedly when switching tab.

### ISSUE THREAD

**Issue by PoppyBlossom** [ClanGenOfficial/clangen#2627]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Patrol ends unexpectedly when switching to a tab other than patrols.

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**

https://github.com/user-attachments/assets/25b6abcd-b3ab-4f15-9343-e6bb4951ff08

**Patrol ID + Outcome Print (if applicable)**:
![image](https://github.com/user-attachments/assets/6c034694-a49c-4715-b543-88d0461d50a9)

**Commit # or Game Version Number**: 
7b48f10

**Comment by j-gynn** [comment]
Hi there! This should be fixed as part of #2577 as an unexpected side effect :)
