### ISSUE TITLE
[BUG] death history text is misleading

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2629]
**Type**: Text code

**Describe the bug**
A cat received a claw wound while on patrol. The next moon, they die of this claw wound. Their death history text suggests that they died on patrol rather than from the wound received during the patrol.

**Grade**:  Non-vital

**Reproduce**
Have a cat get a claw wound from a rogue encounter patrol, then have them die of the wound

**Screenshots**
![image](https://github.com/user-attachments/assets/68a3491c-df7f-484c-9ae7-6eaacaf33ffc)
![image](https://github.com/user-attachments/assets/dac5d251-5da4-408a-bca9-c3f103fbb8bb)

**Comment by tobes03** [comment]
@peppst-r I don't suppose you remember exactly which patrol? I know you said "Rogue encounter" but any more clarifying details would help me squish this one.

**Comment by tobes03** [comment]
Even if you can just give me which camp/environment you're on in this save
