### ISSUE TITLE
[BUG] Medicine patrol implies medicine apprentice is a warrior

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2630]
**Type**: Code

**Describe the bug**
I sent a medicine cat and his apprentice in a patrol, and the text refers to the medicine apprentice as if she was a warrior.

**Grade**: Non-vital

**Reproduce**
Send a medicine cat and a medicine cat apprentice together in patrols until this one appears.

**Patrol ID + Outcome Print (if applicable)**: gen_border_otherclan_meeting1 

**Commit # or Game Version Number**: 7b48f10be

**Screenshots**
![image](https://github.com/user-attachments/assets/6fc47a63-6ba1-4b82-8e06-9eb6dcfe8372)
![image](https://github.com/user-attachments/assets/c91cab2d-40f3-4e7e-a9d8-20de19ff6665)

**Comment by LaurBee** [comment]
That's actually one of my patrols (gen_med_stressed1, 2, or 3). Bug has already been addressed and is just waiting on a merge ^^

**Comment by KiraDragoness** [comment]
Oh, sorry about that! I tried searching for a similar report but I probably didn't use the correct terms for the search. I'll close then :)

**Comment by LaurBee** [comment]
No worries! Just wanted to make sure nobody spends time fixing my problem children only to find out that the work's already been done 🤣
