### ISSUE TITLE
[BUG] Cat randomly dies on timeskip with no death log or cause.

### ISSUE THREAD

**Issue by JkHowling** [ClanGenOfficial/clangen#2633]
**Type**: 
Code

**Describe the bug**
A cat just suddenly died on timeskip with no warning. It's not listed on the timeskip messages, nor are they given a cause of death in their history log.

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Timeskip until it occurs?

**Commit # or Game Version Number**: 
7b48f10b

**Additional context**
I literally have no idea what happened. He wasn't sick or injured, the patrol he went on the previous moon was a successful hunt with 4 other cats, and no death message popped up during the timeskip aside from his mate mourning him. Furthermore, there's no cause of death listed in his history log.

**Screenshots**
Patrol Outcome from previous moon
![image](https://github.com/user-attachments/assets/f003257e-51a4-4662-bd32-f049a5bd6161)
No death message, no cause of death
![image](https://i.imgur.com/aGm5QIR.gif)

**Comment by KiraDragoness** [comment]
Hi! This is a problem with the "taken by Twolegs" mass-exctinction event. It's reported in #2463 and should be fixed once #2628 is merged^^
