### ISSUE TITLE
[BUG] Alive cat has cause of death in their history

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2636]
**Type**: Code

**Describe the bug**
A rogue joined on moonskip, and their history says they died of a heart attack, but they are very much alive and not even old enough to die from that. They're 45 moons old.

**Grade**: Non-vital

**Reproduce**
Uh... moonskip until an outsider joins? Not too sure, honestly. It's one of those "this just happened" things.

**Commit # or Game Version Number**: cacc01ce

**Screenshots**
![image](https://github.com/user-attachments/assets/91f1d5fb-e55f-40f4-a551-916599ed972a)
![image](https://github.com/user-attachments/assets/ac16a6db-80ec-44d5-91fa-c1150ec7e778)

**Comment by Vickarooni** [comment]
UPDATE: looks like every outsider you get or invite in has a death cause for whatever reason. just invited this guy in and it says this.
![image](https://github.com/user-attachments/assets/25d396ba-e3eb-4376-b1cc-f87e1bfa6184)

**Comment by j-gynn** [comment]
Cannot reproduce on the same version... (cat 1 was sought out, cat 2 joined randomly through moon event).
![image](https://github.com/user-attachments/assets/529fd44e-15da-4a19-aea6-41f6f33ec6e0)
![image](https://github.com/user-attachments/assets/ab95df60-3099-4f6e-bc7c-113a2e6fb1af)

**Comment by Vickarooni** [comment]
. Huh
this clangen is unmodded and i havent save file edited since the faded cats incident i believe
i'll try to invite in some more outsiders or get some from moonskips and update y'all on it
i can also send my save file again if needed

**Comment by j-gynn** [comment]
Oop before we get too excitable - just remembered, that was a Classic clan. IDK if that could make a difference, so I'll see if I can recreate with an Expanded clan. Please hold...

**Comment by j-gynn** [comment]
Nope, can't reproduce with an Expanded clan either :( 
![image](https://github.com/user-attachments/assets/9246005c-2ee2-4807-823b-8b7d1591a4cb)

**Comment by Vickarooni** [comment]
uh??? okay so it's not just outsiders, EVERY cat that joins the clan is fucked up. this newborn kit was murdered by a cat who has been in the dark forest for 200+ moons and was discovered by a dead cat.  what the shit
![image](https://github.com/user-attachments/assets/3fa0695c-371f-4b94-9dff-84ec884000f9)

some other examples with clanborn cats:
![image](https://github.com/user-attachments/assets/aa255b6d-51a5-4298-8090-54ca8021bbc1)
![image](https://github.com/user-attachments/assets/e33d9378-0136-48b9-9f61-899ebbe7a6e0)
![image](https://github.com/user-attachments/assets/fea80fc3-5927-49b6-bb94-3553161e8cc3)

i recognize the murder. freckle _was_ a murderer and ashpelt _did_ discover it. it's stealing death reasons from other cats and putting them in here???

**Comment by j-gynn** [comment]
uh- haunted save file? Could you send that across please?

**Comment by Vickarooni** [comment]
here you go! No idea what is happening
[Ember.zip](https://github.com/user-attachments/files/16652811/Ember.zip)

**Comment by j-gynn** [comment]
thank you~ Will investigate. It's possible the faded cat thing is causing Problems from beyond the grave. Just wanna exclude that.

**Comment by Vickarooni** [comment]
if its that again istg LMFAO at least it stopped crashing because i couldn't even progress before

**Comment by selkirks** [comment]
> thank you~ Will investigate. It's possible the faded cat thing is causing Problems from beyond the grave. Just wanna exclude that.

if faded cats' ids are reused, its possible that new cats are being generated with that same id and therefore same history? idk im just throwing stuff out there

**Comment by Vickarooni** [comment]
> if faded cats' ids are reused, its possible that new cats are being generated with that same id and therefore same history? idk im just throwing stuff out there

thats actually a really good point

**Comment by Vickarooni** [comment]
update: sel might be onto something. i checked who freckle murdered and it was a cat named oakleywhistle who has in fact faded. it also fucked up any mention of their name as you can see here
![image](https://github.com/user-attachments/assets/919c80d1-e6b5-476d-8e58-ef527a48d695)

**Comment by j-gynn** [comment]
It's definitely reusing existing, faded IDs. Looks like faded IDs aren't being properly removed from the pool of possible IDs to pick from.

**Comment by Vickarooni** [comment]
just checked, and yep! gorse (the cat i showed on the initial post) is using ID 7 which belonged to a faded cat as well
i apologize looks like everything i report these days is related to faded cats x_x

**Comment by j-gynn** [comment]
It's okay! It looks like your file has broken here: line 33 of Ember.json
![image](https://github.com/user-attachments/assets/3b617a42-9b24-4e3c-a5f3-e94082764a04)

Have you edited this file at all? /genq
It should be an easy fix of just... writing all the faded IDs there, but if you haven't edited this and it somehow wiped itself we may have a problem on our paws.

**Comment by Vickarooni** [comment]
i think i did, when i was trying to fix all the faded cat related crashes i was getting. maybe it's that! i'll change the new cats' IDs and put them all there. thank u :P

**Comment by j-gynn** [comment]
No worries. Seems like this one can be closed 😅

**Comment by Vickarooni** [comment]
my bad, everyone! that was the problem. i have rectified the IDs and the histories show properly. sorry for the hassle x_x
