### ISSUE TITLE
[BUG] button is askew

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2637]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- 
**Describe the bug**
sorry i suck at titles :sob: but the "sort by:" button is able to be hovered over and clicked on to change the sorting option.

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to ur cats page
2. hover over "sort by"/click it

**Commit # or Game Version Number**: cacc01ceef687e3563325215deb10d16daa95061

**Additional context**

**Screenshots**

https://github.com/user-attachments/assets/3a43b434-54ac-400b-8c10-f1dff35d67b9

**Comment by j-gynn** [comment]
I believe this is intended, although understandably confusing. Sort by is the label for the dropdown so clicking it is basically clicking the dropdown.

**Comment by selkirks** [comment]
ooh alright, thank you! ill close this rq
