### ISSUE TITLE
[BUG] "raspberry" accessory does not exist

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2642]
**Type**: (only select one)
- Sprite - an issue with the art in the game

**Describe the bug**
on an event, a kit got the "raspberries" accessories. i checked their profile, and they had no accessory on. gonna ping @Clayteeth since its yr accessory

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. debug event ensure "gen_misc_any_accessorykit2"
2. have kits in yr clan
3. moon skip till one gets the "raspberries" accessory
4. view profile

**Commit # or Game Version Number**: cacc01ceef687e3563325215deb10d16daa95061

**Screenshots**
![image](https://github.com/user-attachments/assets/829f97f7-2b0f-46b8-b5b5-08421ecb38a5)
![image](https://github.com/user-attachments/assets/a087a3e2-d9e5-4243-8f8e-ce4f007a0997)

**Comment by KiraDragoness** [comment]
I just replicated this bug:
![image](https://github.com/user-attachments/assets/815dd048-947b-4dd3-bc51-7f8276902786)
![image](https://github.com/user-attachments/assets/d344edfc-2e42-47c8-b408-f076cf9e05f4)

**Comment by Vickarooni** [comment]
![image](https://github.com/user-attachments/assets/5e3fa448-ba49-4ea9-a3f8-622932c1a31b)
i also have a cat w/ invisible raspberries lol
