### ISSUE TITLE
[BUG] War Issues

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2646]
**Type**: (only select one)
Code

**Describe the bug**
When going to war with a clan, periodically a warning will pop-up in the shell after moonskips saying that there were no injury/death/accesory war events found for certain cats.

**Grade**: (only select one)
Regular?

**Reproduce**
1. Have a war declared with a clan.
2. Moon skip until you see the warning text.

**Commit # or Game Version Number**: 
cacc01ceef687e3563325215deb10d16daa95061

**Additional Info**
Some cats mentioned within the Warnings
//////
Cat: Saphowl 
Age - 31 moons (Young Adult)
Status - Warrior
Backstory - Clanborn
Cat: Beamcinder
Age - 50 moons (Adult)
Status - Warrior
Backstory - former loner
General War Message - Amidst turmoil, empathy blooms between the ShriekClan and FlameClan leaders, kindling hope for reconciliation beyond the battlefield. 

///////
Cat: Flurryfeather
Age - 117 moons (Senior Adult)
Status- Medicine Cat 
Backstory - Formerly a rogue
Cat: Weedsight
Age - 158 moons (Senior)
Status - Elder 
Backstory - Formerly a loner
General War Message - Seeking peace, ShriekClan and FlameClan ponder an end to their war.

//////
Cat: Sparrowscar
Age - 30 moons (Young Adult)
Status - Warrior
Backstory - Clanborn
Cat:  Graykit
Age - 3 moons (Young)
Status - Kitten
Backstory - Outsider roots
Cat: Beamcinder
Age - 52 moons (Adult)
Status - Warrior
Backstory - Formerly a loner
Cat: Slate 
Age - 94 moons (Adult)
Status - Warrior
Backstory - Formerly a loner
Cat: Ashenkit
Age - 3 moons (Young)
Backstory - Outsider roots
Cat: Brindlefur
Age - 30 moons (Young Adult)
Backstory - Clanborn
General War Message - In the midst of conflict, a spark of understanding flickers between ShriekClan and FlameClan cats, hinting at a potential path to peace.

**Screenshots**

![2024-08-21](https://github.com/user-attachments/assets/b213d0a7-6832-439f-8e9f-0dcf53c0b953)
![2024-08-21 (1)](https://github.com/user-attachments/assets/fb23d3ae-e8d0-4166-bc13-42f698a35a2e)
![2024-08-21 (2)](https://github.com/user-attachments/assets/c76d59d9-04ca-49d9-8815-72a2d872c21c)

**Comment by PoppyBlossom** [comment]
This warning message is normal according to this comment unless you encounter other problems in the game.

![image](https://github.com/user-attachments/assets/11802e92-62b0-4ae7-91bd-05296655f123)

Typically when you see warning messages like this are usually fine, except when you start running into problems.
