### ISSUE TITLE
[BUG] Scroll Bar Down Arrow

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2649]
**Type**: 
- UI

**Describe the bug**
On the moon event skip page, the down arrow on the scroll bar seems to hardly/not work when there are multiple events in the 'all events', 'relationships', and 'health' tabs. At least, those are the tabs I've noticed.

**Grade**: 
- Non-vital

**Reproduce**
1. Get a lot of events for these tabs and try pressing the down arrow. 

**Commit # or Game Version Number**: 
cacc01ceef687e3563325215deb10d16daa95061

**Additional context**
It seems to have to do with the number of events that happens each tab? Sometimes the down arrow works, sometimes it doesn't, sometimes it works for a little bit then stops. 24 events were in the 'all events' tab and the down arrow won't work at all, for the 'health' bar the down arrow works constantly until around 6 events then stops.

**Comment by j-gynn** [comment]
I remember this - should be fixed by #2577 :) The events layer over the button due to how the page is set up.
