### ISSUE TITLE
[CODE] Update prophecy list to use pronouns

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2656]
**Description**
Just a quick one to update the prophecy list to use pronouns. Will probably require a little bit of finagling?

**Comment by j-gynn** [comment]
There's also something quirky in the generation code for prophecies that I think means clair_list can't pull from dream_list too.
![image](https://github.com/user-attachments/assets/ed31a6b2-f5da-4199-bb2f-44bae3f0264a)
get_special_snippet_list, line 1784.

Should probably also get looked at to determine the correct functionality at the same time.

**Comment by scribblecrumb** [comment]
Taken care of in #2725
