### ISSUE TITLE
[BUG] "There's nothing here, and that's a problem!" Patrol Outcome

### ISSUE THREAD

**Issue by k8ertotz** [ClanGenOfficial/clangen#2659]
**Type**: Code (I think) 

**Describe the bug**
Received this response when proceeding on a training patrol (I don't remember which one)
![image](https://github.com/user-attachments/assets/f495b921-5eec-4cdb-9739-7c3eaabde991)

**Grade**: Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. proceed on training patrol (if i see it again i will update which one) 

**Patrol ID + Outcome Print (if applicable)**: Training patrol, again not sure which one. 

**Commit # or Game Version Number**: Chinch's Genemod on dev build b185da73

**Comment by DeadGirlRisen** [comment]
You should check with genemod in case they edited patrols, or try and replicate this on the non modded version of dev.

My guess would be that theres something with how the perfectionist added trait that caused this issue, so it'd be something for the mod, not clangen ^^

**Comment by k8ertotz** [comment]
I didn't even consider that! Perfectionist is actually from a trait mod so i'll let them know. Thanks!
