### ISSUE TITLE
[BUG] pregnancy crashes the game

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2668]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
pregnancy crashes the game on classic mode

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. start classic clan
2. moon skip

**Commit # or Game Version Number**: f83899029b6c67244f18c182d71e0c69b8bf0e87

**Additional context**
self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1193, in one_moon_cat
    Pregnancy_Events.handle_having_kits(cat, clan=game.clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 125, in handle_having_kits
    Pregnancy_Events.handle_zero_moon_pregnant(cat, second_parent, clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 245, in handle_zero_moon_pregnant
    text = event_text_adjust(Cat, text, cat, clan=clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\utility.py", line 1996, in event_text_adjust
    replace_dict["m_c"] = (str(main_cat.name), choice(main_cat.pronouns))
AttributeError: 'NoneType' object has no attribute 'name'

**Screenshots**

**Comment by j-gynn** [comment]
Cannot replicate so far on latest version of dev - multiple successful pregnancies (more than 10), including GNC and one trans kitty for pronoun variety. Any save modifications? Looks like, somehow, the cat that's been passed in to make a pregnancy doesn't exist. Very strange.

**Comment by selkirks** [comment]
> Cannot replicate so far on latest version of dev - multiple successful pregnancies (more than 10), including GNC and one trans kitty for pronoun variety. Any save modifications? Looks like, somehow, the cat that's been passed in to make a pregnancy doesn't exist. Very strange.

no save modifications. completely new clan made for reporting this. are you on classic or expanded?

**Comment by selkirks** [comment]
plus pregnancy settings
![image](https://github.com/user-attachments/assets/fe13965b-570b-47bf-9fe0-47f5f8039883)

**Comment by j-gynn** [comment]
Aha! It's one of those pregnancy settings that's causing the problem. All of those successful pregnancies have been using default settings - just turned on all your doodads and crashed. Will investigate :D

**Comment by selkirks** [comment]
> Aha! It's one of those pregnancy settings that's causing the problem. All of those successful pregnancies have been using default settings - just turned on all your doodads and crashed. Will investigate :D

my hero

**Comment by selkirks** [comment]
issue looks to be 'pregnancy ignores biology'

**Comment by j-gynn** [comment]
Issue found, working on permafix <3
