### ISSUE TITLE
[BUG] Audio: Muting music in main menu overrides mute elsewhere

### ISSUE THREAD

**Issue by j-gynn** [ClanGenOfficial/clangen#2676]
**Type**: (only select one)
- Audio

**Describe the bug**
UPDATE: It's actually the main menu & make clan screen buttons together. They seem to override the other mute buttons in the game.
UPDATE 2: Actually no, the clicky buttons return if you're on the make clan screen (or any subscreen), but not on the main menu. Strange.

~~If you mute the audio whilst in the make clan screen (specifically the name your clan step) and exit without creating a clan, it stays muted no matter what you do until you go back to that screen and unmute it there. Sounds get re-enabled for some reason but not music.~~

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken
- 
**Reproduce**
1. Go to make clan screen
2. continue to name your clan
3. toggle the sound off
4. exit screen
5. clicky button sfx is back but music is not
6. try to re-enable music via the mute toggle (nothing happens, button is registered as clicked but does not toggle)

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: cadd40

**Additional context**

**Screenshots**

**Comment by PoppyBlossom** [comment]
It looks like `settings["audio_muted"]` and `music_manager.muted `are not synchronized correctly.
Edit: I also managed to crash the game while randomly clicking buttons with no terminal output.
Edit2: `settings["audio_muted"]` will switch to true (mute) when entering and exiting any screen for some unknown reason. While `music_manager.muted` remains false.

**Comment by PoppyBlossom** [comment]
\assign-me
