### ISSUE TITLE
[BUG] r_c showing instead of name after death during patrol

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2680]
**Type**: 
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
Instead of showing the name of the cat that died, it shows "r_c"

**Grade**: 
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Become enemies with another Clan. (You don't have to be at war, though).
2. Proceed on border patrols.
3. Witness an entire patrol of your children be slaughtered.
4. Check their causes of death and find "r_c" instead of their name.

**Patrol ID + Outcome Print (if applicable)**:
PATROL START ---------------------------------------------------
Patrol Leader: Smallstar
Random Cat: Morelspeckle
Total Number of Possible Patrols | normal: 13, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
starting chance: 20 | EX_updated chance: 68
Smallstar updated chance to 68 | Morningfeather updated chance to 68 | Morelspeckle updated chance to 68 | 
PATROL ID: gen_bord_ambush_hostile_disaster2 | SUCCESS: False
PATROL END -----------------------------------------------------

**Commit # or Game Version Number**: 
fb113c9330f3fc2c767df8ee4a5444a128483517

**Additional context**

**Screenshots**
![image](https://github.com/user-attachments/assets/9fd89d73-b1c0-4e7e-a292-61aad0bf61d5)

**Comment by PoppyBlossom** [comment]
Replication confirmed.
Update: It truns out some patrols have r_c in their death text instead of m_c.
