### ISSUE TITLE
[BUG] Not all deaths counted for leader

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2681]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Despite Smallstar dying four times from this event, her death record only showed one death. She is still alive.

**Grade**: 
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Become enemies with another Clan.
2. Proceed on border patrols with your leader present.
3. Get ambushed and murdered by that enemy Clan.
4. Check the death record on your leader and it should show only one death despite how many lives they actually lost.

**Patrol ID + Outcome Print (if applicable)**:
PATROL START ---------------------------------------------------
Patrol Leader: Zinniachill
Random Cat: Icyheart
chosen filter prey size: medium
Total Number of Possible Patrols | normal: 11, romantic: 1 
not a potential mate or current mate
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Skysplash']
No Stat Cat Found
---
starting chance: 20 | EX_updated chance: 49
Zinniachill updated chance to 49 | Icyheart updated chance to 49 | Skysplash updated chance to 49 | 
PATROL ID: bch_hunt_leaf-bare_squirrel_rattlesnakerumble1 | SUCCESS: False
PATROL END -----------------------------------------------------
PATROL START ---------------------------------------------------
Patrol Leader: Smallstar
Random Cat: Morelspeckle
Total Number of Possible Patrols | normal: 13, romantic: 0 
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
---
Finding stat cat. Outcome Type: Success = False, Antag = False
Can Have Stat: []
POSSIBLE STAT CATS ['Morningfeather']
No Stat Cat Found
---
starting chance: 20 | EX_updated chance: 68
Smallstar updated chance to 68 | Morningfeather updated chance to 68 | Morelspeckle updated chance to 68 | 
PATROL ID: gen_bord_ambush_hostile_disaster2 | SUCCESS: False
PATROL END -----------------------------------------------------

**Commit # or Game Version Number**: 
fb113c9330f3fc2c767df8ee4a5444a128483517

**Additional context**
The leader is still alive right now, if that effects the UI here at all.

**Screenshots**

**Comment by j-gynn** [comment]
Will be fixed by #2664
