### ISSUE TITLE
[BUG] Life-giving cat says that they are almost done when they are definitely not

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [ClanGenOfficial/clangen#2683]
**Type**: 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
8 cats were giving lives and the third one "reassures Antfleck that she is almost done."

**Grade**: 
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Kill a few cats (it might have to be less than 9 total in StarClan, I'm not sure)
2. Click on a new leader's "leader ceremony" 
3. Read through the cats and see if anyone says this line really early
4. If none said it, repeat from step 2

**Commit # or Game Version Number**: 
fb113c9330f3fc2c767df8ee4a5444a128483517

**Additional context**
This might be a potential issue with all leader ceremonies or only with leader ceremonies without 9 dead cats.

**Screenshots**
![image](https://github.com/user-attachments/assets/6a16380f-3cd6-4a18-bb0c-573c395487f5)

**Comment by PoppyBlossom** [comment]
The line "She is almost done" refers to Heneyspeckle's almost done giving Antfleck her life, in this specific scenario. It does not mean entire ceremony being almost done if that's what you thought was the issue :3
