### ISSUE TITLE
[BUG] Game closes if you invite an outsider

### ISSUE THREAD

**Issue by Hazitos** [ClanGenOfficial/clangen#2687]
**Type**:

- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
If you try to invite an outsider, the game immediately closes when you skip a moon.

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent

**Reproduce**
1. Go to the leader's den
2. Click on the outsiders tab
3. Select a cat and click on the "invite" option
4. Leave the den and go to the Events tab
5. Timeskip one moon
6. See error

**Commit # or Game Version Number**: Dev build 6f64ccdd

**Comment by PoppyBlossom** [comment]
It works fine for me, do you have an error log or a crash log?

**Comment by scribblecrumb** [comment]
stale
