### ISSUE TITLE
[BUG] mute button does not work once you load in a clan

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2702]
**Type**: Audio

**Describe the bug**
Mute button doesn't work once you load a clan in. 

**Grade**: Unimportant

**Reproduce**
Load in an existing clan save with sound on, try to hit mute button in lower right hand corner in various pages/dens

**Comment by PoppyBlossom** [comment]
Yeah, I noticed that. It's most likely to be on the wrong layer.

**Comment by j-gynn** [comment]
It's also possible that it's creating another version of itself without deleting the first (when really we should be sharing the same instance across all screens). That would mean the older one that's not tied to the click function is literally blocking the new one from being clicked on. That's just a guess based on experience with getting the menu buttons working in fullscreen tho

**Comment by PoppyBlossom** [comment]
Omg, J-gynn, you literally predicted the future! I tried hiding all the mute buttons, but the one on the clan screen doesn't seem to be affected. I've been experimenting with the mute buttons, and it's so frustrating that I can't figure out why that particular mute button is not responding to my actions. Now I just need to find out where those extra versions of the mute buttons are coming from.

**Comment by j-gynn** [comment]
Mhm, if I had to guess, it's to do with how they're being imported. I can't remember exactly how this got fixed in my fullscreen branch (or at least, I think the fix I use there is only possible thanks to another fix required for full screen - it's a long story).

**Comment by PoppyBlossom** [comment]
It looks like there is a missing `self.mute_button_pressed(event)` on some screens. Like in the event screen.

**Comment by PoppyBlossom** [comment]
Okay, I fixed all of the broken mute buttons! Only the main menu has an extra mute button obstructing the interaction the others are all missing `self.mute_button_pressed(event)`

**Comment by j-gynn** [comment]
Could consider moving that call to the superclass Screens and ensuring that every `handle_events` calls `super().handle_events(event)`?

**Comment by j-gynn** [comment]
I think this is ultimately fixed in #2577 so don't need to worry too much about it

**Comment by PoppyBlossom** [comment]
So is my pull request #2715 still necessary?

**Comment by j-gynn** [comment]
Double checking the fullscreen PR to make sure it's not missing anything... I think it might be unnecessary. So sorry for wasting your time...!

**Comment by PoppyBlossom** [comment]
No problem at all, I'm just doing this for fun anyway :3
