### ISSUE TITLE
[BUG] 'Default string, this should never appear'

### ISSUE THREAD

**Issue by Say0rnis** [ClanGenOfficial/clangen#2703]
**Type**: Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
A moon relationship event gave a default string that notes that it should never be seen. Uncertain exactly what happened, the command window error only says 'ERROR: No interaction with this conditions.  platonic decrease high'

**Grade**: Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Start a clan
2. Roll moon events & check the relationships tab

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: Commit  #2690

**Additional context**
Checking the events.json file, the cats involved in the interaction are Orchidroot (warrior/thoughtful/good speaker & talented swimmer/has an apprentice/adult/clan founder) and Shadebellow (elder/fierce/good climber/senior/clan founder/has had water in her lungs for one moon). Very little else of note has happened, the clan is only 2 moons old.

Uncertain which traits here would be causing the event to fail and use the default string, but hopefully this narrows it down a little

**Screenshots**
![image](https://github.com/user-attachments/assets/9e06fda0-9c8d-40a8-8f3a-ab0cc3af50c4)
![image](https://github.com/user-attachments/assets/68e1f259-63e7-473a-b39d-9e125242ea97)

**Comment by Say0rnis** [comment]
Edited the main post for clarity after narrowing things down by checking events.json

**Comment by PoppyBlossom** [comment]
I replicated it. It looks like it started happening right after #2690 was merged.
Got error messages as well `"ERROR: No interaction with this conditions.  platonic decrease high"`

**Comment by PoppyBlossom** [comment]
After some debugging, I found out that #2690 modified the only platonic high interaction with no restraint to a medium one, so the game is complaining.

I will create additional interactions and downgrade the error message to a warning, as this issue does not significantly impact the game.
