### ISSUE TITLE
[BUG] Text invisible when changing Cat Name

### ISSUE THREAD

**Issue by Sumwatt0** [ClanGenOfficial/clangen#2716]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
"Highlight a name. then start typing. You can't see what you're typing when you do it this way, and the words show up only if you click away/press done. The words are THERE, you just can't see them." - **snapshotmanor on Discord**

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Highlight a cat's name.
2. Type whatever. Words won't show up unless you click away.

**Commit # or Game Version Number**: 
7e3fe50d

**Screenshots**

https://github.com/user-attachments/assets/3155e8f5-4501-4d16-ab7b-b04b0aca3ede

**Comment by j-gynn** [comment]
Known bug: pygame-gui is the culprit. I believe it's already known in their repo.

**Comment by Sumwatt0** [comment]
Yeah that's what I suspected, I guess we can't do anything about it yet so I'll close it.
