### ISSUE TITLE
[BUG] Leader Den Crash

### ISSUE THREAD

**Issue by PoppyBlossom** [ClanGenOfficial/clangen#2717]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
I ran a clan up to like 600 moons and checked if everything was working, but not surprising at all, the leader den crashed as soon as I clicked on it.

```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'not_working'
  File "REDACTED\clangen\scripts\screens\LeaderDenScreen.py", line 185, in screen_switches
    if game.clan.leader.not_working():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\clangen\main.py", line 384, in <module>
    game.all_screens[game.current_screen].screen_switches()
AttributeError: 'NoneType' object has no attribute 'not_working'
```

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. time skip 600 moons
2. check leader den

**Commit # or Game Version Number**: 
58ff286
**Additional context**
It is very likely that faded cats are haunting us again.
**Screenshots**
![image](https://github.com/user-attachments/assets/c8bf6f7c-1515-43bd-b3ee-30fbecf892ec)
Debug stuff
![image](https://github.com/user-attachments/assets/6a6233be-e008-4b2e-977e-468054e711d0)

**Comment by scribblecrumb** [comment]
Was this also fixed by #2954?

**Comment by j-gynn** [comment]
Needs testing to confirm. I didn't put it in as a fix since I wasn't certain (and this may be a faded cat thing).

**Comment by scribblecrumb** [comment]
Seems to be fixed, please reopen if it appear again to haunt us.
