### ISSUE TITLE
[BUG] Clan generator isn't  letting me get on, it just turns into a black screen.

### ISSUE THREAD

**Issue by NoraSofia** [ClanGenOfficial/clangen#2721]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- Sprite - an issue with the art in the game
- Code - general bugs related to how the game runs and responds to you. 
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here: https://github.com/ClanGenOfficial/clangen/issues/1818

**Describe the bug**
ex.: This bug implies that the cat is never...

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game
- Dire - Still playable, but a major feature is broken
- Important - The bug has a large effect on the gameplay but is not urgent
- Regular - A typical bug that should be seen too soon, but doesn’t necessarily break the game or inhibit the player
- Non-vital - This bug can easily be ignored and does not have a large impact on play
- Unimportant - This bug has little to no impact on play. 

**Reproduce**

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 

**Additional context**

**Screenshots**

**Comment by archanyhm** [comment]
Please re-read the issue template and fill it out; I'll be closing this due to the lack of information for now.
