### ISSUE TITLE
[BUG] Wrong Pronouns on Patrol

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2734]
**Type**: 
-Code(?)

**Describe the bug**
Cloverpaw is a girl, but in this patrol outcome it switches to him near the end instead of her

**Grade**: (only select one)
- Non-vital

**Reproduce**
1. Go on this patrol
2. Have this outcome happen

**Patrol ID + Outcome Print (if applicable)**:
PATROL ID: gen_train_berrybush4 | SUCCESS: False

**Commit # or Game Version Number**: 
7f10ca40aa4f50979d5d39007f9a9b3df7bcdae9

**Screenshots**
![2024-09-24](https://github.com/user-attachments/assets/a18efe18-cfaf-415d-9a57-0d3584724af7)

**Comment by j-gynn** [comment]
Hi! This should be reported in the typos and misspellings section.

**Comment by thunderingboom** [comment]
My bad!
