### ISSUE TITLE
[BUG] Will not pass loading screen, let alone start loading

### ISSUE THREAD

**Issue by Quackerss864** [ClanGenOfficial/clangen#2736]
- Code 

Will never pass the original download menu, and even after twenty minutes, the bar hasn't moved In the slightest

- Game-breaking - Can't begin to play the game at all, and just be able to see the blue loading screen.

**Comment by j-gynn** [comment]
Please attach a screenshot to illustrate what's going on.

**Comment by Quackerss864** [comment]
![Screenshot 2024-09-24 8 47 49 PM](https://github.com/user-attachments/assets/c0e3e101-4440-401f-aef1-970e1d2dda53)

**Comment by scribblecrumb** [comment]
Where are you downloading from?

**Comment by Quackerss864** [comment]
This website. Not sure if it's not working because of the website, or what.
![Screenshot 2024-09-24 9 01 16 PM](https://github.com/user-attachments/assets/db99e8ac-72bf-4bbe-9cfe-b1020552441b)

**Comment by archanyhm** [comment]
The web version is unmaintained at this point, so we cannot offer any help with it. There are plans to continue it eventually, but nothing concrete as of yet.

**Comment by Quackerss864** [comment]
Thank you anyways! I appreciate the help.
