### ISSUE TITLE
[BUG] lost cat returns twice in one moon

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2751]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
a lost cat can return twice in one moon if they return on their own AND the player seeks them out

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. have a lost cat
2. search for them
3. hope that they return on their own and are found by your clan on the same moon

**Commit # or Game Version Number**: 303e98652bfdea67cc74bd639ae0a87ae9170397

**Screenshots**
![image](https://github.com/user-attachments/assets/e897fd1d-3131-463a-884b-b90fc33d9b51)

**Comment by tobes03** [comment]
![image](https://github.com/user-attachments/assets/c5978909-ff61-4d15-895d-d5ec15d5a8df)
Similar problem
