### ISSUE TITLE
[BUG] History notes don't indent

### ISSUE THREAD

**Issue by RaptorWithAMarker** [ClanGenOfficial/clangen#2774]
**Type**:
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
The indent feature on 11.2 in the notes under history tab does not work. Cats from previous update and new cats alike are affected. When editing, the text shows as normal, but when finished, the text reverts to its original state without the 'enter' key being pressed. Only current solution is to manually space the notes to avoid large blocks of text. Indenting the text after editing does not work, but cats from previous saves retain the indent until edited.

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to History under any cat
2. Click on the check mark to edit notes
3. Type anything and add an indent afterwards and continue typing
4. Save the text by hitting the box for the check mark
5. See error

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 
Windows 10+ Zip, expanded version, 11.2, 50+ moons into the game

**Additional context**
While non vital, the manual spacing is annoying and tedious. Normally notes record how characters act around each other to create a cohesive thought process behind actions within the game. Has never occurred in previous versions played, and persists even after saving and closing game multiple times. No mods were added before this problem occurred, and a text file for more names has been edited, though did not impact the repeatability of the bug.

**Screenshots**
![clangen1](https://github.com/user-attachments/assets/1ae6a693-ce22-4321-8487-fd1797e10a2a)
![clangen2](https://github.com/user-attachments/assets/e4773052-f1cf-49a4-8fb8-f1f5fa3267e0)
![clangen3](https://github.com/user-attachments/assets/2a0ee0b9-07f3-4e93-a40e-af4160325245)

**Comment by PoppyBlossom** [comment]
Hmm, can't replicate it in 842d80d. Perhaps the problem has already been resolved?
