### ISSUE TITLE
[BUG] Can't open the game because of a missing? module

### ISSUE THREAD

**Issue by Ice1456** [ClanGenOfficial/clangen#2798]
I'm using Thonny to play the game normally, and i had almost no issues with it until now. [i have been playing this game from the start]
Since recently everytime i tried to open the new dev-version of the game has refused to start because there was no modzle named " pygame_gui.core.gui_type_hints", i tried many things to combat it but no good result so far, i even tried to reset my modules like i did with the "housekeeping" error, but this time it didn't work.
So you could call this Bug a game-breaking issue for me, i don't really know if i'm the only one with this issue. 
I don't know if this is a problem with thonny or with the new clangen code, because i don't know much about programming itself.
After i had this issue i went to my older files and they worked perfectly so i think this has maybe something to do with the new sounds added into the game, but as i said i don't really know. I have tried to wait till there have been any updates that fix this issue, but no luck so far.
Heres a screenshot of the error thonny displays :
![Screenshot (2194)](https://github.com/user-attachments/assets/43579101-6c98-4ad7-9121-898a0d623164)

**Comment by archanyhm** [comment]
Not a bug. Refer to the README for instructions on how to run the game from source.
