### ISSUE TITLE
suggestion: polymates

### ISSUE THREAD

**Issue by druidicmage** [ClanGenOfficial/clangen#281]
i don't know how easy it would be to code, but to have a setting you can turn on/off to allow polyamory would be really nice. it doesn't have to be fleshed out even, maybe working the same way but listing all 3 parents in kits' parents section, something like that. it would be nice

**Comment by ThriftFoot** [comment]
oooo yeah thisd be cool

**Comment by Ryos00** [comment]
Planned as a possibility for the future
