### ISSUE TITLE
[BUG] Mediation screen crash - Dev

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2816]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Whenever I try to open the mediation screen (no matter which cat I select), the game crashes.

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
Just select whichever mediator cat in the clan and try to go to the mediation screen with the button.

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: Dev. Version df923de7

**Additional context**
N/A

**Screenshots**
![Screenshot 2024-09-30 150834](https://github.com/user-attachments/assets/d0701150-a80c-47a3-a095-d55f88be53db)

**Comment by j-gynn** [comment]
(oops)

**Comment by mirandarts** [comment]
the mediation screen can be viewed again but it only shows one page of cats, with no arrows :/ 
![Screenshot 2024-09-30 194819](https://github.com/user-attachments/assets/2cbbc8da-ce0f-4211-9570-2a9aaf2a6ff0)
