### ISSUE TITLE
[BUG] Relationship tab not responsive

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2817]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
When clicking on the 'Relationship' tab on the Timeskip Moon page, the game freezes and the popup window of "Clangen.exe has stopped responding" comes up. If you hit "wait for program to respond", it does go back to normal gameplay, but it is inconvenient.

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent

**Reproduce**
1. Timeskip one moon (I haven't tried with a new clan yet/moon 0)
2. The issue should come up/the game should freeze immediately

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: Dev Version df923de7

**Additional context**
N/A

**Screenshots**
N/A

**Comment by j-gynn** [comment]
(uh-oh. again.)

**Comment by scribblecrumb** [comment]
Closing as it does not seem replicable.  Please reopen if this still occurs on the latest version.
