### ISSUE TITLE
[BUG] Patrol crashes / unplayable

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2822]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Whenever I try to send cats on any type of patrol, the game crashes. The first time I tried it, it was a mentor and apprentice, but I went back in and tried another patrol with 6 random cats and a random patrol type, and the game still crashed.

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
1. Select any number of cats to go on a random patrol

**Patrol ID + Outcome Print (if applicable)**: Not sure if this applies or where to find it

**Commit # or Game Version Number**: Dev Version efe76a1e

**Additional context**
N/A

**Screenshots**
1. The first patrol I tried, with a mentor and apprentice
![Screenshot 2024-09-30 200445](https://github.com/user-attachments/assets/13415df0-9e37-4fac-a6cc-e30dd8f2ee71)

2. Second patrol I tried with 6 random cats and random patrol type
![Screenshot 2024-09-30 200514](https://github.com/user-attachments/assets/ef0cdc5c-a6f9-446a-8a30-6e7e78e22db1)

**Comment by archanyhm** [comment]
Fixed in #2824
