### ISSUE TITLE
[BUG] Cats display in the wrong order when using next cat button

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2827]
**Type**: UI

**Describe the bug**
This bug was apparently fixed a while back, but it seems to have returned somehow? I've found sorting doesn't fix it. Using the "next cat" button shows the cats in the complete wrong order compared to the cat list.
(This also happens in the mediation screen.)

**Grade**: Regular

**Reproduce**
1. Go to cat list
2. Click on any cat
3. Click "next cat"
4. Next cat will not match up with the order in the cat list

**Commit # or Game Version Number**: 8cf5c717

**Screenshots**
Attached a video; I can always record more with different sorting options if needed.
https://github.com/user-attachments/assets/369b4706-f4f1-4597-94f7-f2703360788e

**Comment by PoppyBlossom** [comment]
The cats are always in the same order no matter what the sorting method is, okay I figured some stuff out, #2723 has a bug where you have to update the list first for the list to be properly sorted, demonstrated by the clip below,

https://github.com/user-attachments/assets/8e3981aa-ba75-46ad-9439-0bc78eab6c70
