### ISSUE TITLE
[BUG] Moonskip animation does not display anymore

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2828]
**Type**: Sprite

**Describe the bug**
The "moon loading" animation that normally displays when moonskipping does not appear anymore. I've moonskipped multiple times to make sure this wasn't a one time occurrence. Genuinely thought the game froze for a second until it finished loading.

**Grade**: Non-vital

**Reproduce**
1. Moonskip
2. ...that's it honestly.

**Commit # or Game Version Number**: 8cf5c717

**Screenshots**
Video showing the problem;
https://github.com/user-attachments/assets/c752ae31-519f-4e38-af85-ee3dcfdeeb5f

**Comment by PoppyBlossom** [comment]
~After some testing, I discovered that the loading ball was being rendered, but it was underneath the events panel for some unknown reason.~
Okay never mind the offsets coordinates are too large.

**Comment by Vickarooni** [comment]
@PoppyBlossom would also like to add that on the patrol menu, if the game takes a little while to load, the moonskip animation _will_ appear, but off in the corner for some reason
![image](https://github.com/user-attachments/assets/2848fbc3-ece2-4b07-8ef4-faaa42715dbd)

**Comment by PoppyBlossom** [comment]
> @PoppyBlossom would also like to add that on the patrol menu, if the game takes a little while to load, the moonskip animation _will_ appear, but off in the corner for some reason ![image](https://private-user-images.githubusercontent.com/172712347/374347804-2848fbc3-ece2-4b07-8ef4-faaa42715dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDIzMTQsIm5iZiI6MTcyODM0MjAxNCwicGF0aCI6Ii8xNzI3MTIzNDcvMzc0MzQ3ODA0LTI4NDhmYmMzLWVjZTItNGIwNy04ZWY0LWZhYWE0MjcxNWRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QyMzAwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjM2YjZkZWM0MmRjZjYyYjI5MGJmZGVjZjVhNDNjYzY5MmNmYmM1YTM1MWM2ZDI3OTA4MjQ4NTlmZWRjYzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FqSEC1xqAsC-Q3YL8_zWUawVIMzdyqJSsq_WQwNWhRY)

Thanks for the feedback!

**Comment by PoppyBlossom** [comment]
Okay, I fixed it!
