### ISSUE TITLE
[BUG] leader ceremony button hover over sized incorrectly

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2829]
**Type**: UI

**Describe the bug**
When hovering over the leader ceremony button, the UI popup has either too small of a font or the button is too long. There is a mismatch between sizing

**Grade**: Unimportant

**Reproduce**
Literally just hover your mouse over the ceremony button

**Comment by j-gynn** [comment]
Please add an image to show what the problem you're experiencing is.

**Comment by scribblecrumb** [comment]
Closing as stale
