### ISSUE TITLE
[BUG] mentor knows that she is a good choice of mentor for her own kit

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2831]
**Type**: Code

**Describe the bug**
Parent is watching her own kit be apprenticed to herself 

**Grade**: Regular

**Reproduce**
Have a parent be assigned their kit as their apprentice

**Screenshots**
![image](https://github.com/user-attachments/assets/c9701df4-4ef5-4c17-be99-d27d2338d839)

**Comment by PoppyBlossom** [comment]
I don't think this is an unexpected behavior, it is possible for a parent to be their kit's mentor in my opinion.

**Comment by scribblecrumb** [comment]
Perhaps the awkwardness could be mitigated with some smart pronoun usage?
