### ISSUE TITLE
[BUG] condition text cut off

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2834]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
"condition" is cut off in a condition tab

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. get a cat with yellowcough or another infectious disease
2. check their profile and conditions tab

**Commit # or Game Version Number**: 0f78d7b6954cfc24cd65425bb186db28bc953958

**Additional context**
![image](https://github.com/user-attachments/assets/7d28e856-cd29-4864-b5bd-d84e60881018)

**Comment by j-gynn** [comment]
Is this in full screen or windowed mode? If fullscreen, what resolution screen are you using, and do you have any of the settings toggles related to onscreen graphics enabled (atm just the "ignore scaling rules" checkbox I think...)? Thank you!
