### ISSUE TITLE
[BUG] injury events do not work on classic mode

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2840]
**Type**:
- Code

**Describe the bug**:
moon events for injuries that scar do not seem to be functioning correctly on classic mode. it seems that the cat just gets a scar instead like how it used to be. illnesses and non-scarring injuries such as "sore" appear to work just fine though, as does grief, and injuries from patrols seem to work as well.
moon events ive received so far that should injure and don't: 
gen_injury_clawwound_anymultiagestatustraitnotfighter1
gen_injury_cliffbreak1
gen_injury_beesting_multiany3

**Grade**:
- Important

**Reproduce**
1. create new clan on classic mode
2. skip moons until you see an injury event
3. check cat and see they aren't hurt

**Commit # or Game Version Number**: 
c7b54315c49c9f1702940ad04af982115eb1d736

**Comment by scribblecrumb** [comment]
@larkgz perhaps something for you to look at?
