### ISSUE TITLE
[BUG] crash when skipping moons

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2844]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i have 'save every 5 moons' setting on. upon getting to the 4th moon and moon skipping, game crashes

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. make a new clan
2. turn auto-save on
3. moon skip

**Commit # or Game Version Number**: e21871523586d97e06bd175613546a24ff5075fd

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 348, in <module>
    MANAGER.process_events(event)
  File "C:\Users\Leafy\AppData\Roaming\Python\Python310\site-packages\pygame_gui\ui_manager.py", line 240, in process_events
    consumed_event = ui_element.process_event(event)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\windows.py", line 1705, in process_event
    if event.ui_element == self.close_button:
AttributeError: 'SaveError' object has no attribute 'close_button'

**Comment by PoppyBlossom** [comment]
It looks like we needed the game to pause when saving.

**Comment by PoppyBlossom** [comment]
```
Traceback (most recent call last):
  File "clangen\scrip--ts\events.py", line 298, in one_moon
    game.save_cats()
  File "clangen\scrip--ts\game_structure\game_essentials.py", line 429, in save_cats
    for inter_cat in self.cat_class.all_cats.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by PoppyBlossom** [comment]
I tried pausing the game while it's saving but the save time was too painful to wait so we need to find some new ways to implement this, I am currently thinking about creating a deep copy of the stuff that needed to be saved and doing it on a different thread?

**Comment by j-gynn** [comment]
Cannot replicate in the most recent version of ClanGen, is this still an issue?

**Comment by selkirks** [comment]
maybe? ill check rq

**Comment by selkirks** [comment]
still occurs

> Cannot replicate in the most recent version of ClanGen, is this still an issue?

**Comment by j-gynn** [comment]
Possible duplicate of #2857, sorry I was linking everything here when I meant to link it there... but this one is more specific and kind of weird
