### ISSUE TITLE
[BUG] nonexistent mate is mentioned

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2845]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
swanhail is mentioned to have a mate, but does not have a mate.

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. have a cat with no mate have an affair with a cat with a mate

**Commit # or Game Version Number**: e21871523586d97e06bd175613546a24ff5075fd

**Screenshots**
![image](https://github.com/user-attachments/assets/a0c302d1-ad34-474b-ad8d-8e39b0555e36)
![image](https://github.com/user-attachments/assets/0e13045f-90f0-4210-a709-4f63915aea61)

**Comment by scribblecrumb** [comment]
@Lixxis might be a good one for you to check out?  This is an affair text and afaik affairs should only occur in mated cats

**Comment by scribblecrumb** [comment]
Upon reading closer, this seems to be less related to unmated cats having an affair and more related to the birthing cat having no mate while the other parent has a mate.  aka in very heteronormative terms: a married man had an affair with an unmarried lady.  So still a valid affair and not a bug in that respect.  Rather, I think we'll need to separate the affair birth events into two categories: events for mated affair cats and events for unmated affair cats.  Likely not super complex, thankfully, just a little annoying lol
