### ISSUE TITLE
[BUG] family tree sprites fail to stay inside ui

### ISSUE THREAD

**Issue by tomialshrike** [ClanGenOfficial/clangen#2853]
**Type**: (only select one)
UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off.

**Describe the bug**
When a cat has more than eight (8) cats in the respective branch of their tree, the sprites for each cat after fail to stay within the UI and do not create a second page.

**Grade**: (only select one)
Regular - A typical bug that should be seen too soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Timeskip ~100 moons
2. Check family tree for relations with over eight (8) cats

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 
Dev build: c7b54315

**Additional context**
I was planning on doing a save where you actually play at 100 moon; the only thing I did was timeskip to 100 moons.

**Screenshots**
![Screenshot 2024-10-05 110047](https://github.com/user-attachments/assets/628e6304-3fef-4973-8450-a0abe7f97e61) 
![image](https://github.com/user-attachments/assets/1b84c2e0-6a5a-4140-9e4a-10359b624339)
![image](https://github.com/user-attachments/assets/b5c29a72-f746-412e-a13e-b409a37b660e)

**Comment by j-gynn** [comment]
Fixed in #2874 - devs please mark as completed.
