### ISSUE TITLE
[BUG] Fullscreen Causes Tooltips To Offset In Info Screen

### ISSUE THREAD

**Issue by PoppyBlossom** [ClanGenOfficial/clangen#2855]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
ex.: This bug implies that the cat is never...

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Fullscreen the game
2. Got to setting->info
3. Check contributor tooltips.

**Commit # or Game Version Number**: 
c7b5431

**Screenshots**
![image](https://github.com/user-attachments/assets/e5213709-e35a-4df4-b79e-ee7cbea8965e)

**Comment by j-gynn** [comment]
ugh, I was hoping nobody would notice this haha... fixing it has been a real pain due to how it's implemented.
