### ISSUE TITLE
[BUG] Unexpected Behavior When Clicking Too fast - Event Screen

### ISSUE THREAD

**Issue by PoppyBlossom** [ClanGenOfficial/clangen#2857]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
I love debugging stuff with an auto-clicker, but the game presented some interesting behavior in the newest update.
 This bug doesn't occur only when using auto-click; just clicking fast can trigger the same bug. A normal person shouldn't be able to notice this, though.

**Grade**: (only select one)
- Regular - A typical bug that should be seen too soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Click extremely fast, 1 millisecond for the best result
2. See bug

**Commit # or Game Version Number**: 
c7b5431

**Screenshots**
Something is seriously wrong here...
![image](https://github.com/user-attachments/assets/7c5f1bdf-1f3e-4956-bd90-bc9a1472be93)

**Comment by Chinch-Bug** [comment]
For added context if it's any help:
In previous versions, before the dynamic text, etc. update, the game wouldn't allow you to skip moons again until the previous one was done. Now, however, it lets you initiate a new moonskip regardless and you can basically just run several moonskips at the same time

**Comment by PoppyBlossom** [comment]
@Chinch-Bug Great point, I think #2844 is caused by it too, with the `RuntimeError: dictionary changed size during iteration` error.

**Comment by selkirks** [comment]
"A normal person shouldn't be able to notice this, though."

u will not believe what happened to me 💔 
![image](https://github.com/user-attachments/assets/b4e8c86d-28f9-466a-81fd-519d36beceba)
