### ISSUE TITLE
hey um I can't access clangen on inch io and the terminal app is banned is [there anthro way I can do it?

### ISSUE THREAD

**Issue by ari935** [ClanGenOfficial/clangen#2861]
hey um I can't access clangen on inch io and the terminal app is banned is [there anthro way I can do it?

_Originally posted by @ari935 in https://github.com/ClanGenOfficial/clangen/issues/930#issuecomment-2390374978_

**Comment by PoppyBlossom** [comment]
I assume an organization or institution monitors you. If that is the case, I don't think there is any way around that. Plus, Clangen is in .exe format, which Chromebooks don't support. Anyway, have a great day, and thank you for being interested in Clangen!

**Comment by archanyhm** [comment]
GitHub Issues are also not for tech support. Refer to our Discord if you want help -- but the comment above by @PoppyBlossom is pretty accurate.
