### ISSUE TITLE
[BUG] 'raiding other clans' button missing

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2884]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
the confirmation on the 'raid other clans' focus has disappeared. still clickable tho

**Grade**: (only select one)
- Regular - A typical bug that should be seen too soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. open a clan
2. go to warrior's den
3. select 'raid other clans'

**Commit # or Game Version Number**: 514e67389154242c58221ad04d1eef06098ff8ff

**Screenshots**
![image](https://github.com/user-attachments/assets/77b0b267-4465-4db5-938d-1dfbb764494d)

**Comment by selkirks** [comment]
happens with 'helping other clans' and 'sabotaging other clans' too
![image](https://github.com/user-attachments/assets/06ed9a96-20e9-4d52-be01-e406e1b35577)

**Comment by rustykitty** [comment]
> happens with 'helping other clans' and 'sabotaging other clans' too

Hmmm, perhaps that's because they use the same popup?
