### ISSUE TITLE
[BUG] DROPLET symbol is a pixel off

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2886]
**Type**: (only select one)
- Sprite - an issue with the art in the game

**Describe the bug**
DROPLET clan symbol is missing a pixel compared to the other symbols

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. go to make a new clan
2. check droplet's clan symbol

**Commit # or Game Version Number**: 514e67389154242c58221ad04d1eef06098ff8ff

**Screenshots**
![image](https://github.com/user-attachments/assets/9991f493-a492-419f-a437-d06853691164)
![image](https://github.com/user-attachments/assets/7e651f79-4842-4d56-9f02-ba8519704d31)

**Comment by Clumxy** [comment]
Working on!
