### ISSUE TITLE
[BUG] game shuts down after a millisecond of me opening

### ISSUE THREAD

**Issue by Raiol1243** [ClanGenOfficial/clangen#2890]
I believe it is a code issue as I keep deleting the game and redownloadimg to see if that will fix
But it does not 

**Describe the bug**
As soon as I got the latest dev build I tried to re enter the game but as soon as I opened it it immediately shut down 

In order to reproduce it use the latest dev version as as soon as you open it it immediately shuts down

**Comment by PoppyBlossom** [comment]
@Raiol1243 Okay, I recreated the bug. It should be fixed soon hopefully.

**Comment by PoppyBlossom** [comment]
We found a fix for this, so hopefully we can fix it soon!
