### ISSUE TITLE
[BUG] events tab on full screen causes game to log out

### ISSUE THREAD

**Issue by Raiol1243** [ClanGenOfficial/clangen#2898]
Whenever I try to play with full screen whenever a tap the events tab I’m booted out of the game  I often change in and out of full screen in order to play as playing on windows on a laptop does not allow the full screen to be shown I wouldn’t  say this is game breaking as there’s a way to get around it though.

**Comment by scribblecrumb** [comment]
Closing due to lack of proper template use.  If you would like to resubmit, please do so using the given bug report template.
