### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Chiaxi** [ClanGenOfficial/clangen#290]
Hello! I've recently downloaded the new version, and running it on Thonny, I can only seem to get to the clan naming page, but no further? I also cannot choose between difficulties, and i'd like some help/suggestions on what i should do.

(I've restarted my pc, thonny, re-downloaded and extracted the zip files a few times)

It only says "Male tortie/calico!" when i try to move onto the next page

**Comment by Ryos00** [comment]
Assuming this issue has been resolved. If you need more tech support, please join the discord.
