### ISSUE TITLE
[BUG] game  kicks you out when you tap on the leaders den 

### ISSUE THREAD

**Issue by Raiol1243** [ClanGenOfficial/clangen#2911]
**Type**: (only select one) I'm not sure what this would fall under so because the button kicks me out I guess UI? -/clangen/issues/1818

**Describe the bug**
 sometimes when I click on. The leaders den I get kicked out 

**Grade**: (only select one)

- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Go to camp
2. Click on leaders den

*

On the most recent dev version

**Comment by archanyhm** [comment]
Please supply the commit hash you're on for documentation purposes. "the most recent dev version" might not stay accurate for long.

**Comment by scribblecrumb** [comment]
Not reproducible on current dev.  Either the crash is related to something else, or it's been fixed.  @Raiol1243 are you able to provide a crash report?  If not, there's not much luck of us discovering what caused this.

**Comment by LaurelWillow** [comment]
Leader's den crashes for me when I have just demoted a leader and don't have a new one yet. I'm on c6e1d639.

**Comment by scribblecrumb** [comment]
hmm alright @LaurelWillow, how about you make a separate bug report for your experience, so that we can have that info available in a more organized way.

**Comment by LaurelWillow** [comment]
Yeah, I could do that

**Comment by scribblecrumb** [comment]
Closing due to lack of info
