### ISSUE TITLE
[BUG] Forbidden Age Gap Romance

### ISSUE THREAD

**Issue by FangWasHere** [ClanGenOfficial/clangen#2912]
**Type**: Code 

**Describe the bug**
It's what it says on the tin: Forbidden age gap romance. 
Cats who are far apart in age are generating romantic events. From my own digging around in the code it seems to be the result of the age range game config only being applied to mate selection and not also romantic events. Usually the generation of the romantic events picks 2 cats within an acceptable age gap but there's nothing actually PREVENTING the selection of 2 cats with an unacceptable age gap. Random chance has not looked upon me favorably this week...
This forbidden age gap romance can also be randomly generated for the Clan Founders when you start out, but I haven't dug around enough in that section of code to understand why, because I only just discovered it when I started working on getting screenshots of the other forbidden age gap romance.

At least the cats can't become mates...? Still uncomfy though. ---> I don't know how to strikethrough but disregard that, they CAN apparently and I have the screenshot proof. 

**Grade**: Regular
It's just REALLY uncomfy once you spot it, and I am cursed by random chance to keep seeing it.

**Reproduce**
1. Create a new Clan
2. Start timeskipping
3. Check relationships for every cat to see if they have any romantic interest.
4. If there's romantic interest check their ages and relationship events
5. Nothing suspicious yet? Repeat steps 2 through 4 until you find the forbidden age gap.

**Commit # or Game Version Number**: I don't understand what this means exactly, so I'm going to guess what it means. I downloaded the dev version this morning so the most recent merge request to dev is 2908. 

**Screenshots**
Generated relationship at the start, real oof-
![NOO](https://github.com/user-attachments/assets/4a68c8dd-cf80-4d88-ac36-4f7a63121450)
That's a 41 moon difference, default game config acceptable age range is 40-
![ITSTHESAMECATTOO](https://github.com/user-attachments/assets/8e0b3751-43cf-4f10-ae3d-a5d24a1de8d3)
Gotcha! That's a 54 moon difference-
![Caughtin4k](https://github.com/user-attachments/assets/c973a163-7d75-4441-a563-b173fe78624e)
Forgot to show their romance bar-
![Oops](https://github.com/user-attachments/assets/12331557-72af-4452-9a50-3dfafd8cb938)
Another gotcha, with a 76 moon difference..-
![Pleasestop](https://github.com/user-attachments/assets/649b0940-61b4-4799-babc-f8a9de836a01)
And here's their romance events-
![Andherestheevents](https://github.com/user-attachments/assets/4ee3ba2c-cf67-4462-af47-71c4f9fa4096)

**Comment by Vickarooni** [comment]
can confirm this has happened to me, but more often w/ clan founders. and about that- i'm like 75% sure it's because of the "randomize relationship values when creating clan" setting and how it (maybe) also doesn't do those checks.. afaik it's been a problem in stable for a while because i've experienced it while creating custom saves

**Comment by FangWasHere** [comment]
Um, problem is still there. My fault for not making my words clearer.

Problematic age gap for first generated relationships for founder: This part of the age gap problem is now fixed!

Problematic age gap romantic events being generated on timeskip: Still here and present

**Comment by ZtheCorgi** [comment]
if you are still using the same save, i believe that cats with an age gap of more than 40 moons who are not in the same age group and who already have romantic feelings for one another will still be able to get romantic events. additionally, cats who are in the same age group ignore the 40+ moons age gap unless you have that setting marked as true in game_config. this really only applies to cats who are in the adult, senior adult, and senior age groups.

**Comment by ZtheCorgi** [comment]
i forgot to add, if you're sure the cats in question don't fall into any of the categories i mentioned above, it would be helpful if you could please provide screenshots of the events and the cats involved in them so that we can try to confirm what's going on ^^

**Comment by FangWasHere** [comment]
Was doing that now, here's one I just got:
Cats in question are a young adult and a senior
![Notallowed](https://github.com/user-attachments/assets/7964ef7a-b00f-4a1b-953c-a9881670b9d5)
![Eventinquestion](https://github.com/user-attachments/assets/12c9814b-fc69-40f6-9b78-7accd4019fe7)
![Flurry](https://github.com/user-attachments/assets/bbfe65e1-3b0a-4169-8f99-23aa8d8bec5f)
![Freeze](https://github.com/user-attachments/assets/ed40a886-953f-43cb-8aa6-817c996a890e)

**Comment by FangWasHere** [comment]
Oh my god I figured it out-
![Gotcha](https://github.com/user-attachments/assets/98a0ba7e-8055-4854-8e7c-a0242fda2a9b)

These romance events are in the platonic increase events and are not age locked, only status locked

- Making a PR
