### ISSUE TITLE
[BUG] "Tigger" patrol creates very old warriors who immediately retire

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2924]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
The patrol gen_bord_welcomingsparrowgift1 yields a cat that is very old, in this case 249 moons, but still a warrior instead of an elder. 

**Grade**: (only select one)
- Regular - A typical bug that should be seen too soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
Run border patrols with high outsider reputation until you get this patrol, then check the age and status of the cat. 

**Patrol ID + Outcome Print (if applicable)**:
Patrol Leader: Shrimpfruit
Random Cat: Canarydapple
Total Number of Possible Patrols | normal: 23, romantic: 0 

Finding stat cat. Outcome Type: Success = True, Antag = False
Can Have Stat: ['any']
POSSIBLE STAT CATS ['Shrimpfruit', 'Canarydapple', 'Blizzardfeather', 'Waterstep']
Found stat cat: Canarydapple

starting chance: 40 | EX_updated chance: 90
Shrimpfruit updated chance to 90 | Canarydapple updated chance to 100 | Blizzardfeather updated chance to 100 | Waterstep updated chance to 100 | 
PATROL ID: gen_bord_welcomingsparrowgift1 | SUCCESS: True

**Commit # or Game Version Number**: c6e1d639

**Additional context**
The cat will usually retire the next moon. 

**Screenshots**
old cat
<img width="610" alt="Screenshot 2024-10-21 at 3 10 03 PM" src="https://github.com/user-attachments/assets/5d231212-1e42-45ac-96d0-e553321c7100">

**Comment by scribblecrumb** [comment]
Could be fixed by adjusting the tagging.  The patrol does read as though the cat is old, so just specifying that their status must be elder would prevent this, as they already have age specified as senior.
