### ISSUE TITLE
[BUG] "LAVENDER" accessory is invisible

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2929]
**Type**: Sprite

**Describe the bug**
The "lavender" accessory suddenly just... vanished. It still appears on a cat's profile, but is not present anywhere on the sprite.

**Grade**: Regular

**Reproduce**
1. Get the "lavender" accessory on a cat (or, alternatively, save-file edit it in)
2. Check their profile

**Commit # or Game Version Number**: c6e1d639

**Screenshots**
![image](https://github.com/user-attachments/assets/8c27f606-4ea0-4bb1-b6fa-cd1e57902be8)
![image](https://github.com/user-attachments/assets/d514bf33-2b11-4919-98fe-df361a16756f)

**Comment by ZtheCorgi** [comment]
so, i assume other accessories still work? saving and reloading doesn't fix it? did it vanish on moonskip, or what? i notice both cats in your screenshots are seniors. can it be seen on younger cats?

**Comment by Vickarooni** [comment]
@ZtheCorgi nope! just saved and reloaded and they're still gone. this was being discussed in #players-helping-players. i have not moonskipped, i just updated the game and it disappeared. here are some screenshots (courtesy of inanimateinsanity on discord and @LaurelWillow) of younger cats who also have the invisible accessory. all other accessories from what i've seen work fine (with the exception of "raspberry" which was removed but if a cat had it previously, attempting to view their profile crashes the game)

![image](https://github.com/user-attachments/assets/13112453-e9b6-498e-bb89-0400f38ce677)
![image](https://github.com/user-attachments/assets/f516d05e-974f-41ff-be30-1ba43b6254ea)
