### ISSUE TITLE
[BUG] Apprentice in DF still Obtains Full Name

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2936]
**Type**: (only select one)
- Code

**Describe the bug**
I had a med apprentice who murdered a warrior via death berries. They were exiled and eventually killed via the 'hunt down' button in the leader's den. The apprentice was 9 moons old when they died and went to the DF, but after reaching 12 moons (I'm assuming) they obtained their full name. This does not happen in SC.

**Grade**: (only select one)
- Non-vital 

**Reproduce**
1. Exile an apprentice (not sure if this is med-app specific)
2. Murder apprentice via 'hunt down'
3. Exile to DF
4. Watch for name change

**Commit # or Game Version Number**: 
c6e1d639fd551fe54ee9c7f232fda5a0afd29958

**Screenshots**

![2024-10-22](https://github.com/user-attachments/assets/59ddea68-3a73-456d-833b-a9db1c16fcb8)
![2024-10-22 (1)](https://github.com/user-attachments/assets/f0ec37bb-e90d-481a-82c9-f7ea6fe4c872)

**Comment by arisaema12** [comment]
Spent a while trying to replicate the issue, and I think I've figured it out. When any apprentice is exiled, they keep their apprentice name, but if you save and exit the game then the apprentice has their full name upon reloading. I'm guessing this is because the 'exiled' status replaces the 'apprentice' status in the code, so the cat is no longer given the apprentice suffix.

**Comment by PoppyBlossom** [comment]
Okay, I think I figured something out, in the `Name` class the `status` is warrior by default, so I'm wondering if that's why the cats get their full name apon reload.

**Comment by PoppyBlossom** [comment]
I did some further research, and it turns out the showing of the full name is controlled by a boolean in the `Names` class called `specsuffix_hidden`, and I spend hours trying to find where in the code it gets set to True and I cannot find a single line of code that does that. :(

**Comment by PoppyBlossom** [comment]
I am going to fix this by just not overwriting the current status at all.
