### ISSUE TITLE
[BUG] "torn pelt" related event crashes game on moonskip

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2938]
**Type**: Code

**Describe the bug**
I moonskipped and the game just... crashed. Looking at the crash log (and with some help from @selkirks, thank you immensely) I think what's going on is that either a) the game is trying to generate an event that will give the "torn pelt" injury to a cat that already has it, or b) it's trying to give a cat a permanent condition off the torn pelt, and because such a condition doesn't exist, the game crashes. Either way, "torn pelt" is the problem because that's what the crash log is pointing to as the source.

**Grade**: Important

**Reproduce**
Honestly, no clue. It was a random crash - Sel and I just moonskipped until the game crashed. I'm guessing you need to have a cat with the "torn pelt" injury for it to happen though.

**Commit # or Game Version Number**: e65b5a53

**Screenshots**
Attaching the stderr;
[stderr_20241022_195132.log](https://github.com/user-attachments/files/17483980/stderr_20241022_195132.log)

**Comment by j-gynn** [comment]
Not a bug *exactly*. The game is trying to pull a string for giving a permanent condition as a result of torn pelt but there aren't any. Technically a writing issue, but I'll add a catch.
