### ISSUE TITLE
[BUG] Faded cats on "parents' siblings" tab in family trees have parents displayed twice

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2939]
**Type**: UI

**Describe the bug**
For some reason, faded cats that are _specifically_ listed under "parents' siblings" in a cat's family tree have their parents shown twice? It doesn't happen with any other tab.

**Grade**: Unimportant

**Reproduce**
1. Find a cat with aunts/uncles/other that are faded
2. View their family tree
3. Click the "parents' siblings" tab
4. Hover over a faded cat

**Commit # or Game Version Number**: e65b5a53

**Screenshots**
![image](https://github.com/user-attachments/assets/af5365df-bd62-468d-a15a-0df1fb141ffc)
![image](https://github.com/user-attachments/assets/b42f38b7-0923-4cff-b0f4-801f790c63dd)
![image](https://github.com/user-attachments/assets/5a669315-0e0b-4082-9906-8f246bd720f0)
![image](https://github.com/user-attachments/assets/2ecfc54e-9fa0-47bb-bafa-c206c6184c91)

**Comment by j-gynn** [comment]
No longer happening as of latest version, it seems:
![image](https://github.com/user-attachments/assets/e0fdbd0b-7b32-4ac2-92ad-bada158488b7)
...never mind
![image](https://github.com/user-attachments/assets/34742d00-22a3-443c-9c07-639f1284144a)
