### ISSUE TITLE
[BUG] Crash when demoting a leader and opening the leader's den

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#2940]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
If you demote or retire your leader, then click the leader's den, the game crashes with this error. 
<img width="519" alt="Screenshot 2024-10-23 at 2 51 39 AM" src="https://github.com/user-attachments/assets/19546f4c-94fe-4f79-8b89-b1bdd492bb34">

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
1. Demote your leader
2. Click the leader's den button

**Commit # or Game Version Number**: 16336b38

**Additional context**
This was reported and supposed to have been fixed back in August- specifically in issue #2607 and PR #2616. However it seems to be persisting.

**Comment by j-gynn** [comment]
good news i broke another thing :D

**Comment by PoppyBlossom** [comment]
> This was reported and supposed to have been fixed back in August- specifically in issue https://github.com/ClanGenOfficial/clangen/issues/2607 and PR https://github.com/ClanGenOfficial/clangen/pull/2616. However it seems to be persisting.

It worked when I tested it, I swear... 😰
