### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MegatronIsAwkward** [ClanGenOfficial/clangen#2943]
The game wont load and its just a black screen? But if I enter inspect you can see the game under the black screen.

![Screenshot 2024-10-23 123901](https://github.com/user-attachments/assets/0181ec08-502a-4958-b339-45b0e1588bf2)

It was working a while ago and then it stopped?

**Comment by Vickarooni** [comment]
the web version is unmaintained and github isn't really the place for asking about it ^^" the black screen issue can be solved by clearing your cache but this will also erase your save data
