### ISSUE TITLE
[BUG] cats in one clan can patrol in a different clan

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2949]
**Type**: (only select one)

- Code - general bugs related to how the game runs and responds to you. 
**Describe the bug**
a cat from clan1 is able to go on patrol in clan2. view video below

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. make a clan
2. select a cat in the patrol screen and save the game
3. close the clan and make a completely new clan
4. open the patrol screen for the new clan

**Commit # or Game Version Number**: d06f804d7f86d4d90c0a0675861938f8d24a2b09

**Screenshots**

https://drive.google.com/file/d/1qCM8VsZ370ZbxJZ0E61_zfl2kZswFzjw/view?usp=sharing

**Comment by j-gynn** [comment]
~~oops, I did it again~~

To fix, take a look at the code that saves patrol states when you exit the screen mid-patrol. I forget exactly how I implemented this, but look at the moonskip code and how it resets it to get an idea of how to unbork this for new clans. Oversight!
