### ISSUE TITLE
[BUG] app3 used by patrol but not supported

### ISSUE THREAD

**Issue by larkgz** [ClanGenOfficial/clangen#2952]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
`mtn_med_cobwebapps2` uses `app3` in outcomes, but `app3` is only supported for pronouns. As a result, the outcome is not correctly formatted, so no relationship change occurs. 

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Patrol ID + Outcome Print (if applicable)**:
`mtn_med_cobwebapps2`
```
PATROL START ---------------------------------------------------
Patrol Leader: Shrubpaw
Random Cat: Drizzlepaw
No normal patrols possible. Repeating filter with used patrols cleared.
used patrols cleared []
All patrol filters regarding location, session, etc. have been removed.
debug_ensure_patrol_id: "mtn_med_cobwebapps2" is a possible herb_gathering patrol, and was set as the only herb_gathering patrol option
Total Number of Possible Patrols | normal: 1, romantic: 1 
attempted romance between: Shrubpaw Drizzlepaw
final romance chance: 26
libpng warning: iCCP: known incorrect sRGB profile
starting chance: 30 | EX_updated chance: 42
Shrubpaw updated chance to 42 | Drizzlepaw updated chance to 42 | Sunpaw updated chance to 42 | 
PATROL ID: mtn_med_cobwebapps2 | SUCCESS: True
Relationship block incorrectly formatted: {'cats_to': ['app3'], 'cats_from': ['app1'], 'mutual': True, 'values': ['romantic', 'platonic', 'respect'], 'amount': 10}
Relationship block incorrectly formatted: {'cats_to': ['app3'], 'cats_from': ['app2'], 'mutual': True, 'values': ['dislike'], 'amount': -10}
PATROL END -----------------------------------------------------
```
**Commit # or Game Version Number**: 1a8954eb4b7eacf872679efaaab4e29542be48b5

**Additional context**
To fix the bug, either the outcomes should be changed, or `app3` should also be supported in `gather_cat_objects()`.

**Comment by scribblecrumb** [comment]
Fixing this is likely just a matter of adjusting `gather_cat_objects()` to support app3.  It would be best to future proof by adjusting to support all the way up to app6, though.
