### ISSUE TITLE
[BUG] Patrol Button Breaking

### ISSUE THREAD

**Issue by zeldagirl113** [ClanGenOfficial/clangen#2958]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
When trying to run a patrol, the game takes you back to the main Camp screen. Clicking on the Patrol button just resets the Camp screen so that the cats are in different locations. Need to restart the game to fix.

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Go to the Patrol screen
2. Try to go on patrol

**Commit # or Game Version Number**: e6a8cebaba4278cc28c3463c410f0fff7ca52d84

**Screenshots**
Before clicking on Patrol
![image](https://github.com/user-attachments/assets/579b99ad-d09f-4693-b891-8de4b08989b8)

After clicking on Patrol
![image](https://github.com/user-attachments/assets/54de1dde-bd27-4d49-a0e2-71740fff8dbc)

**Comment by scribblecrumb** [comment]
Is anyone able to replicate?  I can't seem to

**Comment by rustykitty** [comment]
@zeldagirl113 Can you elaborate more on what happened leading up to the bug?

**Comment by zeldagirl113** [comment]
Idk, I just tried to send a patrol out and the bug happened. My mouse has been broken so I’m wondering if it somehow clicked twice on the “Go On Patrol” button and that’s what caused it

**Comment by j-gynn** [comment]
Replicated. Your theory is correct - your magical cursed mouse is clicking the button multiple times. We don't have any checks in place to stop it from running the thread multiple times, which causes... Some issues. I'll hopefully have a fix up. May also fix the duplicating kitties glitch but I'm not certain.
