### ISSUE TITLE
[BUG] Cat Sprites Blurry on Fullscreen

### ISSUE THREAD

**Issue by Hamburrgergirl** [ClanGenOfficial/clangen#2967]
**Type**: (only select one)
- Sprite - an issue with the art in the game

**Describe the bug**
When in fullscreen mode, the cat sprites are very blurry. I don't know if it's just a me issue, but looking at the sprites is causing eyestrain and I can't do it for too long. 

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent

**Reproduce**
Enter fullscreen mode while on a windows computer.

**Additional context**
I am marking it as important because it is unfortunately causing real, physical pain to look at.

**Screenshots**
![Screenshot 2024-10-30 200524](https://github.com/user-attachments/assets/d21afc4d-0bcb-48a9-8bf1-c822141bd8c9)
![Screenshot 2024-10-30 200535](https://github.com/user-attachments/assets/51374c70-e923-420e-938d-a5c2fbf27679)

**Comment by scribblecrumb** [comment]
Hmm, maybe it's a matter of opinion, but they don't look oddly blurry to me.  I know the slight anti-aliasing was added to reduce the fullscreen "crunch" that causes the pixel art to look wonky at small sizes.  But this does feel like an accessibility issue so I wonder if @j-gynn could look into adding a toggle to turn it off?  I'm so sorry jgynn i have no idea what sort of workload that would entail.

**Comment by Hamburrgergirl** [comment]
These photos aren’t showing it as well as I’d hoped sadly. It to me looks like what happens when you unfocus your eyes, but the rest of the background looks totally normal; this is for some reason causing a lot of strain. I can’t look at it for long. 

I hope it doesn’t create too much of a problem to fix it - if so, and I’m the only one with the issue, I can definitely play without full-screen toggled.

**Comment by j-gynn** [comment]
Hopefully this fixes things, but you'll just have to live with some things looking ugly now. Judging by your resolution, it may just be that it gets softened a little too hard. I could fix that but then I'd have real concerns about optimisation 😬 - it'd be doable, I think, but probably more of an enhancement than a bug fix.

**Comment by Hamburrgergirl** [comment]
@j-gynn 

Hey! Sorry for the delayed response, but I just wanted you to know that the toggle works perfectly!! Thank you so much :)
