### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MonoDragon** [ClanGenOfficial/clangen#2970]
**Type**:
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be of.

**Describe the bug**
 when trying to start a new clan, the generated cats don’t load in the beginning, so you can’t select any cat...

**Grade**:
- Game-breaking - a bug that makes it impossible to play the game

**Comment by rustykitty** [comment]
@MonoDragon What led up to the bug and what version/commit did the bug occur on?

**Comment by Vickarooni** [comment]
on latest dev (f763e741) & i can't seem to replicate this. the cats show up fine?
![image](https://github.com/user-attachments/assets/36ffa8e0-b4ef-4037-9484-a7839989e2a0)

**Comment by MonoDragon** [comment]
Here’s the game link + a screenshot, I couldn’t find a version number sorry:
https://clangen-web.github.io/
![IMG_4855](https://github.com/user-attachments/assets/7ef37a2a-d501-4bcc-aa8f-a1b1b38b5d62)

**Comment by Vickarooni** [comment]
oh that's the web version lmfao. github issues are for the downloadable, dev version.
the web version is very old and outdated, support for it is not given here ^^" @MonoDragon

**Comment by MonoDragon** [comment]
Oop, sorry. That’s for letting me know though :)
