### ISSUE TITLE
[BUG] Grey Marbled Paralyzed Short Hair Sprite is Shifted

### ISSUE THREAD

**Issue by wrensandwolves** [ClanGenOfficial/clangen#2976]
**Type:**
Sprite

**Describe the bug**
The sprite for the grey marbled paralyzed short/medium hair sprite is shifted to the left by a pixel.

**Grade**:
Non-vital

**Screenshots**
Current Appearance:
<img width="413" alt="image" src="https://github.com/user-attachments/assets/05818d1d-e416-4180-8c02-809533dc1c29">

Intended Appearance:
<img width="413" alt="image" src="https://github.com/user-attachments/assets/a78955a3-3f80-4270-a134-f43edd3eba56">

**Comment by scribblecrumb** [comment]
What commit hash or version number are you playing on?

**Comment by wrensandwolves** [comment]
Apologies for leaving that out, I was somewhat unsure what it meant. Checking back, the commit hash was e4ccd76.
