### ISSUE TITLE
[BUG] Clicking +1 cat too fast on patrols crashes game sometimes

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#2977]
**Type**: Code

**Describe the bug**
Pretty random one. I'm spamming two cat border patrols trying to recreate another bug, and after I tried to add the second cat (must note I was clicking rather fast) the game crashed. It's only happened once so far, but this is. Weird.

**Grade**: Important (not marking as Dire because it's not _every_ time a patrol is started)

**Reproduce**
1. Go to patrol menu
2. Spam click +1 cat(?)
3. Repeat until game crashes(?)
(Very unsure of these steps because this was an EXTREMELY random crash)

**Patrol ID + Outcome Print (if applicable)**: n/a, the patrol didn't get a chance to begin

**Commit # or Game Version Number**: f763e741

**Additional context**
Clicking too fast seems to be an issue right now but so far I haven't seen anything about game crashes, so thought it was worth reporting. Noting I am not using an autoclicker so this has a higher chance to be encountered normally, I presume.

**Screenshots**
Attaching stderr.
[stderr_20241102_174059.log](https://github.com/user-attachments/files/17608605/stderr_20241102_174059.log)

**Comment by j-gynn** [comment]
Can no longer replicate (used an autoclicker with a 5ms interval, absurdly fast). I think this may have been fixed in #2969 ?

**Comment by j-gynn** [comment]
May also be closed by #3018 if not already resolved.
