### ISSUE TITLE
[BUG] Ambience Still Plays After Muting Sound

### ISSUE THREAD

**Issue by wrensandwolves** [ClanGenOfficial/clangen#2999]
**Type**:
Audio

**Describe the bug**
Whenever you mute sound on the front menu, you can still hear ambience upon entering your save.

**Grade**:
Unimportant 

**Reproduce**
1. Open ClanGen and have a save premade
2. Click the audio button
3. Press continue
4. --> Audio will still run, but button sounds will be off

**Commit # or Game Version Number**: 
55d635c

**Additional context**
It will turn off if you turn sound back on then turn it off again.
Button sound is not on, only ambience.

**Comment by PoppyBlossom** [comment]
I think #2995 fixes this, but I can't recreate this bug.
