### ISSUE TITLE
Patrol Events Don't Affect Relationships

### ISSUE THREAD

**Issue by sunstartle** [ClanGenOfficial/clangen#300]
Sorry if this is an improper way to report an issue. Basically, all relationship events I have on my patrols (nonromantic and romantic) don't impact the cats' relationship scores at all. I'm playing on this version, expanded mode (?), and haven't used any mods/custom content.

**Comment by scribblecrumb** [comment]
Known issue! It'll be addressed in an upcoming big update to patrols

**Comment by sunstartle** [comment]
sick tysm !! <3
