### ISSUE TITLE
[BUG] Wrong leader finishes naming ceremony

### ISSUE THREAD

**Issue by deadpaan7391** [ClanGenOfficial/clangen#3015]
**Type**: Code (I think)

**Describe the bug**
When reading the naming ceremony for a new leader, the preceding leader was not the one to finish the ceremony. In my screenshots, you'll see that Elkstar was the leader before Flashstar, but Elkstar was the one to give Firestar their final life.

**Grade**: (only select one)
Unimportant

**Reproduce**
Promote a new leader while having multiple previous leaders (I have 9 dead leaders preceding Firestar, idk if the large number has an affect)

**Commit # or Game Version Number**: 0.11.2

**Additional context**

**Screenshots**
![Screenshot 2024-11-16 223548](https://github.com/user-attachments/assets/95138c81-c5c0-46e8-81ab-ec4c23c996e9)
![Screenshot 2024-11-16 223842](https://github.com/user-attachments/assets/bbdf3e07-5dcd-4e8d-b6e6-94f46227b3d7)

**Comment by rustykitty** [comment]
Who began the naming ceremony? You only provided a screenshot of the end.

**Comment by scribblecrumb** [comment]
This is not a bug.  The last life can be given by any of the following:
- A leader that the new leader has existing positive relationship values with
- The oldest dead leader
- The leader preceding the new leader

I would presume that in this case, Firestar had known Elkstar when they were alive.

**Comment by deadpaan7391** [comment]
Sorry it took me so long to get back. Elkstar died before Firestar was born, they did not know each other and have no existing relationship. Elkstar is also not the oldest existing dead leader. I don't know if this changes anything, but I've provided more screenshots just in case, including the full naming ceremony.

![image](https://github.com/user-attachments/assets/ac7a13cd-7213-40d4-a5a4-1cda6842e20e)
![image](https://github.com/user-attachments/assets/00fef34b-f758-4431-a099-d96af16539c0)
![image](https://github.com/user-attachments/assets/a9eea172-2efa-47da-9ded-bb16a59628f7)
![image](https://github.com/user-attachments/assets/07ffdd88-2233-4a97-9fc5-4c1a62edbad5)
![image](https://github.com/user-attachments/assets/6c2c69bf-9772-4cb6-b243-3e5af75c35cd)
![image](https://github.com/user-attachments/assets/18de9d7a-49dc-47e8-b66c-6c7ad1b8106a)

**Comment by scribblecrumb** [comment]
Hm alright, yeah it looks like something must be wrong then

**Comment by j-gynn** [comment]
It's quite hard to confirm whether this will fix this bug since I can't recreate it, but I have suspicions that it's because somehow the `starclan_cats` list has ended up out of order relative to moons since death. I'll push that as a PR and hopefully that'll fix it, but unless I can have the save file or somehow recreate it, it's going to be tricky to confirm.
