### ISSUE TITLE
[BUG] Game crashing when checking dead cat's history

### ISSUE THREAD

**Issue by tictictoby** [ClanGenOfficial/clangen#3100]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

As the title mentions, the game crashes any time I try to check a specific dead cat's history tab. No other cat seems to be affected by this, it's only the one cat. Even opening another cat's history, then using the next/previous cat to see the affected cat, causes a crash.

### Grade

Important - The bug has a large effect on the gameplay but is not urgent

### Steps to reproduce the behavior

Go to cat's profile, click on history tab.

https://github.com/user-attachments/assets/84a450f0-8aa3-420c-91e8-a5542bbb8939

### Commit # or Game Version Number

v0.12.1

### Screenshots

![image_2024-12-02_152444287](https://github.com/user-attachments/assets/0138ebd5-c7e6-4479-9a1b-79e7b7a2ebb2)

**Comment by j-gynn** [comment]
Could you please include your save? This will be both the folder named after the Clan and the JSON file.

**Comment by tictictoby** [comment]
Sure, here they are!

[Shattered.zip](https://github.com/user-attachments/files/17986959/Shattered.zip)
[Shatteredclan.json](https://github.com/user-attachments/files/17986961/Shatteredclan.json)
