### ISSUE TITLE
[BUG] It told me to report this.

### ISSUE THREAD

**Issue by Thorstomp** [ClanGenOfficial/clangen#3106]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

I'm not sure how or why, but it said that: my cat's torn pelt healed, but they now have a weak leg, and that if I saw this event, to report it. So I'm reporting it.

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

I don't know what caused this, it just happened while I was playing normally.

### Commit # or Game Version Number

0.12.1

### Screenshots

![Screenshot 2024-12-02 204155](https://github.com/user-attachments/assets/2f33f9d3-e3ce-4e99-843b-f531a6abb6f7)

**Comment by j-gynn** [comment]
Related: #2938 and #2956 I think, possibly others. Writers: please write some stuff for torn pelts becoming weak legs! Even though... I'm pretty sure the code says this should be impossible to keep triggering...

**Comment by withercats** [comment]
![image](https://github.com/user-attachments/assets/66433c99-c320-4de4-9020-d9c7b345240d)

Twinsies! (was told to add it to the thread in the discord)

**Comment by blitzen-alltheway** [comment]
This happened to me too! On my paralyzed cat.
![Screenshot 2024-12-02 205458](https://github.com/user-attachments/assets/b9d841f0-192c-469a-8a09-9773b0d0ec56)

**Comment by scribblecrumb** [comment]
Have any of you experienced the cat gaining a scar at the same time as the weak leg?  If so, what scar?

**Comment by withercats** [comment]
> Have any of you experienced the cat gaining a scar at the same time as the weak leg? If so, what scar?

Dovepond got a scar on her leg, the torn pelt was from the rats that seemed to spawn endlessly from my clan's fresh kill pile

**Comment by scribblecrumb** [comment]
> Dovepond got a scar on her leg, the torn pelt was from the rats that seemed to spawn endlessly from my clan's fresh kill pile

Perf, then I know what the problem is. Thanks for the info!

**Comment by Thorstomp** [comment]
> Have any of you experienced the cat gaining a scar at the same time as the weak leg? If so, what scar?
Mine also got a scar! 
![Screenshot 2024-12-03 003011](https://github.com/user-attachments/assets/c92a544f-f695-44f0-9f9e-0732b0740624)
