### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#3113]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

Game crashes after moonskip, from what I understand it's a problem with the backstory of a new cat joining the clan.

### Grade

Game-breaking - a bug that makes it impossible to play the game

### Steps to reproduce the behavior

1. Moonskip until the game crashes.

### Commit # or Game Version Number

439525507

### Screenshots

![image](https://github.com/user-attachments/assets/6f1b5430-6671-4896-855d-78f09e563419)

**Comment by scribblecrumb** [comment]
Already fixed
