### ISSUE TITLE
[BUG] Apprentices (and kits) can choose mate

### ISSUE THREAD

**Issue by MathKangaroo** [ClanGenOfficial/clangen#3115]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

when you go to the choose mate screen then click next cat or previous cat, the choose mate screen shows apprentices(but only with other apprentices)

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

1. click choose mate on an adult cat 
2. click next cat until you are on an apprentice/kit

### Commit # or Game Version Number

12.0

### Additional context

When a cat ages up it still lists the other cat as a mate despite age gap. They can also get mate-only relationship interactions during age gap phase.

### Screenshots

![image](https://github.com/user-attachments/assets/0f28cea3-ace8-4bb4-8caf-44e669f2ec50)
![image](https://github.com/user-attachments/assets/f52d0337-8b8b-4e14-8cc8-c00ee7e7d957)

**Comment by rustykitty** [comment]
@scribblecrumb can this be closed? the PR didn't link correctly for some reason
