### ISSUE TITLE
[BUG] Clan stats says there are more outsiders than there are

### ISSUE THREAD

**Issue by deadpaan7391** [ClanGenOfficial/clangen#3140]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

In the "Clan Stats" tab it says I have 9 unknown residence cats, but there are only 3 cats in the "cats outside the clan" tab.

### Grade

Unimportant - This bug has little to no impact on play.

### Steps to reproduce the behavior

I have no idea.

### Commit # or Game Version Number

0.12.0

### Additional context

I updated the game earlier today, that may have affected it.

### Screenshots

![image](https://github.com/user-attachments/assets/b4a36488-c988-4a84-ae07-fda02b813d32)
![image](https://github.com/user-attachments/assets/fc4f619d-a079-4bd1-90d7-92a4c6233906)

**Comment by KiraDragoness** [comment]
The Unknown Residence cats are not counting the living outsiders, but the death cats outside of the Clans (neither in StarClan nor Dark Forest)

**Comment by deadpaan7391** [comment]
Ooooh my bad. Thanks for clarifying!
