### ISSUE TITLE
[BUG] Crash When Inviting New Cat

### ISSUE THREAD

**Issue by tobes03** [ClanGenOfficial/clangen#3142]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

Not sure exactly what happened. Seems like there was a problem creating a new cat? 

### Grade

Dire - Still playable, but a major feature is broken

### Steps to reproduce the behavior

Again, I don't know quite what happened. My Clan has a hostile relationship with Outsiders and has the focus set on "Threatening Outsiders," which is the only setting I can think of that relates to the crash.

### Commit # or Game Version Number

0.12.0

### Screenshots

![image](https://github.com/user-attachments/assets/bb4464de-0f08-42f4-abe6-0e565163332b)

**Comment by scribblecrumb** [comment]
Looks like the same bug that #3093 fixed?

**Comment by tobes03** [comment]
Oh, looks like it! Should've picked through the PRs a little more closely lol. Thanks Scribble

**Comment by scribblecrumb** [comment]
Np! it's a little confusing rn with the closed issues but unreleased patch ^^;
