### ISSUE TITLE
[BUG] Game refuses to open after trying to choose a mate for a 12 moon apprentice

### ISSUE THREAD

**Issue by TinyWinny** [ClanGenOfficial/clangen#3147]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

After trying to choose a mate for a 12 moon (legal by clangen laws) apprentice, the game gives me an error message, closes the game and now refuses to re load like its mad at me or something

### Grade

Game-breaking - a bug that makes it impossible to play the game

### Steps to reproduce the behavior

1. Have a 12 moon apprentice
2. Try to get into the Choose Mate screen
3. Error Message and closes the game
4. Game refuses to open again

### Commit # or Game Version Number

0.12.2

### Screenshots

![image](https://github.com/user-attachments/assets/16f9f644-6fb6-4770-bcc2-f6cedfa69056)
![image](https://github.com/user-attachments/assets/a65239a5-d90f-4051-841b-17d38a35709f)

**Comment by rustykitty** [comment]
Reproduced the crash, but the error message you shared on reopening doesn't seem to be related to this crash (could be wrong, I'm on macOS, so...)

**Comment by rustykitty** [comment]
The error message on reopening might be related to #3156.
