### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by RedArrow12** [ClanGenOfficial/clangen#316]
Hello! I got the newest update and the game does not even load, it says for me "ModuleNotFoundError: No module named 'pygame_gui'
cp_back.py, line 263"
And it also says many things such as "start_screen" is not defined as well as Name "game" not defined. I don't know if it's happening to anyone else with the new update but this is what I get everytime I try to open the game.
(I'm using Thonny to load the script)

**Comment by sweetstyx** [comment]
did you install pygame gui on thonny? in order for the new update to work it needs that. hope this helps at all!

**Comment by RedArrow12** [comment]
Okay so I fixed that problem by actually installing the pygame gui lmao- but now when I load in it says like "There was an error loading the game and something like "There was an error loading the 1_DECREASE_LOW -"

**Comment by RedArrow12** [comment]
Did not mean to close it, my bad-

**Comment by ThriftFoot** [comment]
Im having this issue too, ive downloaded pygame gui aswell but thonny is still saying that no pygame gui module exists etc

**Comment by RedArrow12** [comment]
I've fixed it, make sure you've installed the right versions of py.gui and py.game, don't update them to 5.6 or whatever, keep them as like 5.5
