### ISSUE TITLE
[BUG] Can't update the game

### ISSUE THREAD

**Issue by Silent-artist-with-cats** [ClanGenOfficial/clangen#3169]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

Somehow I can't update my game to the newest version, it stops at 100% of veryfiyng update and does nothing else, I left it for over an hour to see if something happens and nothing. I hope it can be fixed.

### Grade

Dire - Still playable, but a major feature is broken

### Steps to reproduce the behavior

Trying to update the game

### Commit # or Game Version Number

v0.11.2

### Screenshots

![Zrzut ekranu 2024-12-13 190116](https://github.com/user-attachments/assets/3662aa5c-823c-4b71-97f9-c845ca8bcc9a)

**Comment by rustykitty** [comment]
Known issue, see https://github.com/ClanGenOfficial/clangen/issues/3118#issuecomment-2518393134
