### ISSUE TITLE
[CODE] Multiple accessories on individual cats

### ISSUE THREAD

**Issue by scribblecrumb** [ClanGenOfficial/clangen#3175]
**Description**
We've discussed the possibility of allowing cats to wear more than one accessory at a time before.  Main concerns are:
- Preventing cats from getting overloaded with accs; some sort of increasing chance would be good so that cats ending up with multiple accs is fairly rare. Possibly a max of 2 or 3 accs.
- Preventing accs from clashing with each other. This could be mitigated by implementing some sort of system to tag each acc as covering a certain part of the cat. i.e. head accs vs. tail accs vs. body accs.  We'd probably need the ability to give accs multiple body tags, since some span a larger area of the body than others.  Another idea could be some sort of layering system to specify how accs should layer in relation to each other (i.e. laurel should be on top of collars, so that it "hangs" in front of a collar rather than appearing to tuck *behind* the collar.  Not sure what is more feasible to utilize here.

**Comment by j-gynn** [comment]
Related: #2320
This gives more detail than the original though
