### ISSUE TITLE
Poetry could not find a pyproject.toml file in /Users/(my user) or its parents

### ISSUE THREAD

**Issue by Uh-huh117** [ClanGenOfficial/clangen#3187]
Hello! If this isn't an issue that isn't dealt with here, feel free to tell me to get lost. I'm extremely new to the coding and I have been very confused, but so far I have python installed, poetry and the files from here (obviously). When I run the run.sh I encounter this error?
![image](https://github.com/user-attachments/assets/c70ce55c-e408-4ea2-979c-0faa46024afd)
Any ideas as to what I'm doing wrong?
What I'm running if it helps:
Intel Core i5 
Sonoma 14.6.1

**Comment by j-gynn** [comment]
Hi there! I've just updated your issue to hide your username as you missed one of them /info

We don't tend to offer installation support for development, but there is a chance someone may be familiar with this particular issue and drop in.

**Comment by Uh-huh117** [comment]
Thanks a bunch!

**Comment by rustykitty** [comment]
and by the way @j-gynn, they're running the v0.11 branch from source; that's not necessarily the same as development, right?

**Comment by rustykitty** [comment]
Also, which branch should I PR to in this case?
