### ISSUE TITLE
[BUG] kitty.personality.trait in fail_outcome.stat_trait increase success chance?

### ISSUE THREAD

**Issue by filvas2** [ClanGenOfficial/clangen#3223]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

I was familliarizing myself with the code base and saw the following inside patrol.py calculate_success()
![image](https://github.com/user-attachments/assets/978b2857-3819-455a-932f-76b6406fcde9)

Shouldn't a trait inside fail_outcome.stat_trait lower success?

### Grade

Non-vital - This bug can easily be ignored and does not have a large impact on play

### Steps to reproduce the behavior

Code is in scripts\events_module\patrol\patrol.py in function calculate_success()
![image](https://github.com/user-attachments/assets/9a4957d0-b204-4ccd-bd22-f00e6416cd2b)

### Commit # or Game Version Number

Development de2bd1bbf975f24ae5cde53e420c751c6daab126

**Comment by j-gynn** [comment]
`fail_stat_cat_modifier` is a negative number.
![image](https://github.com/user-attachments/assets/c06b07c3-2279-4a4e-bc55-6c9862218927)
This allows the user to modify the success rates themselves, without us implying it must be positive.
