### ISSUE TITLE
Abrupt shutdown after moon 11

### ISSUE THREAD

**Issue by silliestlittleguy** [ClanGenOfficial/clangen#328]
Hi! As usual, the gameplay was going well until I time skipped after moon 11 and it very abruptly shut down with the error message "TypeError: can't multiply sequence by non-int of type 'float'". I tried going back and trying to time skip to moon 12 multiple times, but it seems to crash every single time after specifically moon 11. Any ideas on what's causing this? Thanks!

**Comment by Ryos00** [comment]
I believe this bug has been fixed
