### ISSUE TITLE
[BUG] Injury text does not display correctly

### ISSUE THREAD

**Issue by Vickarooni** [ClanGenOfficial/clangen#3294]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

This does not happen with illnesses to my knowledge, but in cat profiles or in the medicine cat den, injuries always have "injuries." at the beginning (localization error?) so for example, a mangled tail looks like "injuries.mangled tail".

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

1. Find a cat that is recovering from birth
2. Check their profile
or, alternatively -
3. Check medicine cat den
4. Hover over an injured cat

### Commit # or Game Version Number

8e1979e8

### Additional context

I believe the injury text is only broken in profiles when it's specifically "recovering from birth" - I did not see it happening with any other injury.

### Screenshots

There are... a LOT more.
![image](https://github.com/user-attachments/assets/43866de8-e7d1-4822-b714-93cba74133fa)
![image](https://github.com/user-attachments/assets/3eb03053-1b8c-4b7b-9e9d-e758ddc20c37)
![image](https://github.com/user-attachments/assets/8869ef55-74a9-4f1d-ab52-58159775f188)
![image](https://github.com/user-attachments/assets/5a8f8f85-4634-48b9-996a-4efe68c2b2a0)
![image](https://github.com/user-attachments/assets/1e27401c-69ae-4797-8f75-e878bf526a0f)
![image](https://github.com/user-attachments/assets/7297af65-ecc7-4ecc-a173-15d18ff500d1)

**Comment by j-gynn** [comment]
Argh. I know why this is happening. Let me just code the freaking solution (like I should've done in the first place...)

**Comment by j-gynn** [comment]
oh, the fix is simpler than I thought it was. never mind. i can delay the complicated implementation another day!
