### ISSUE TITLE
[BUG] improper lost cat text on patrol

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#3310]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

patrol.lost_cats should be replaced by the name of the cat who got lost

### Grade

Please choose an option...

### Steps to reproduce the behavior

1. make a clan
2. either debug ensure or border patrol till one of your cats gets lost
3. check out the outcome at the bottom of the patrol

### Commit # or Game Version Number

187eae88d7dc2ddc1587a94022c9bb45ad6a7800

### Screenshots

![image](https://github.com/user-attachments/assets/7a977e3c-eaaf-4b7a-b304-4b59091f2a13)

**Comment by j-gynn** [comment]
hjsdfhalsjdj *another one*. Hopefully a quick fix so I should be able to take care of it rn
