### ISSUE TITLE
Disappearing cats and mating with kits

### ISSUE THREAD

**Issue by RedArrow12** [ClanGenOfficial/clangen#362]
Okay so this was something that happened to my friend who plays the game. This is their situation, "Badgerpuddle and Bushshine had kits. A kit named Drakekit. But the strange thing is Badgerpuddle had disappeared entirely. Then- the next moon another cat had kits Drakekit was gone. And Bushshine was mates with one of the kits that was just born. And one of the kits was also mates with their parent. Causing the game to say they were the parent of Themself and all their siblings." This happened to them yesterday (12/26/2022)
No clue if this was fixed in the version I have that was updated an hour ago (date is 12/27/2022) but we both wanted this problem reported.

**Comment by keyraven** [comment]
Yes, this issue is fixed in the current version.
