### ISSUE TITLE
Pygame_gui

### ISSUE THREAD

**Issue by ThriftFoot** [ClanGenOfficial/clangen#395]
Whenever i try to play the developement ver an error code pops up and say 'no module named pygame_gui' or something like that?

**Comment by ThriftFoot** [comment]
The assistant in thonny said its on line 263 i think but idk how to fix it as i have pygame_gui installed

**Comment by sade98** [comment]
yup pygame_guis a requirement now

**Comment by Maplewhisper11** [comment]
> yup pygame_guis a requirement now

how do i even find this?

**Comment by sade98** [comment]
> > yup pygame_guis a requirement now
> 
> how do i even find this?

if you use thonny you can download it in tools

**Comment by ThriftFoot** [comment]
This is still happenening, even on the newest version- i even uninstalled and reinstalled pygame_gui and it still isnt working

**Comment by ThriftFoot** [comment]
> 

do you know how to fix it?

**Comment by sade98** [comment]
> This is still happenening, even on the newest version- i even uninstalled and reinstalled pygame_gui and it still isnt working

did you get yours from manage packages? if not that might be the problem

**Comment by ThriftFoot** [comment]
> > This is still happenening, even on the newest version- i even uninstalled and reinstalled pygame_gui and it still isnt working
> 
> did you get yours from manage packages? if not that might be the problem

ill check that, i can download from itch.io and it works fine, its just from here

**Comment by sade98** [comment]
> > > This is still happenening, even on the newest version- i even uninstalled and reinstalled pygame_gui and it still isnt working
> > 
> > 
> > did you get yours from manage packages? if not that might be the problem
> 
> ill check that, i can download from itch.io and it works fine, its just from here

if that doesnt help id suggest joining the games discord and asking there because im not very tec savy

**Comment by Ryos00** [comment]
If you download a current source code version, pygame_gui is in the requirements.txt and there are instructions on how to install the requirements in the README. To get better tech support, join the discord and there are plenty of folks that are happy to help
