### ISSUE TITLE
un-unzippable

### ISSUE THREAD

**Issue by dusk0220** [ClanGenOfficial/clangen#506]
source code ZIP is not able to be un-ZIPped.

**Comment by sade98** [comment]
extract files?

**Comment by Dpeta** [comment]
https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc
![image](https://user-images.githubusercontent.com/69427753/213917616-039815bc-af0b-4916-be47-1ab42a85e52d.png)
