### ISSUE TITLE
Ages acting up

### ISSUE THREAD

**Issue by Holllyy** [ClanGenOfficial/clangen#614]
Some of my cats are not aging correctly, progressing the moon will make some of their ages go up by 2 and some siblings who were in the same litter will randomly now have different ages? 2 are 9 moons while one is somehow 10 moons? while they're all supposed to be 9 moons. I really hope this gets fixed soon!

**Comment by scribblecrumb** [comment]
We're aware! It's bein worked on

**Comment by Ryos00** [comment]
Fixed in current dev!
