### ISSUE TITLE
Herb Patrol automatically skipped

### ISSUE THREAD

**Issue by RedArrow12** [ClanGenOfficial/clangen#636]
Everytime I try to do an herb patrol, it automatically skips over it and I can't see what happened.

**Comment by VexTheWanderer01** [comment]
I can confirm it happens with 2 or more medcats or 1 mentor and 1 apprentice but not just 1 medcat.

**Comment by Ryos00** [comment]
Yes, this currently happens due to some reorganizing of the patrol files. We made it so that it skips instead of crashing because it can't find a patrol
