### ISSUE TITLE
Tiny text and frezing

### ISSUE THREAD

**Issue by Wolfyonthefolf** [ClanGenOfficial/clangen#813]
All the text in the game is shrank down, making it hard to read.

also my game freezes, it has made me have too reset so much and it infuriating.

**Comment by lillithrosepup** [comment]
Is this for https://clangen-web.github.io? It is currently being worked on. Also, please post bug reports in https://discord.gg/clangen

**Comment by Wolfyonthefolf** [comment]
sorry i didn't know. but yes

**Comment by lillithrosepup** [comment]
ahh okay. in the discord, there is a tech-support-web channel, but we are already aware of the issue and are working on a fix

**Comment by Wolfyonthefolf** [comment]
okay thank you. Have a nice day!

**Comment by lillithrosepup** [comment]
you too !!!
