### ISSUE TITLE
Apprentice Ages+Names= Crash?

### ISSUE THREAD

**Issue by Charl-00tte** [ClanGenOfficial/clangen#918]
My apprentices would age up to 12 moons(on the newest dev version), not get their name, and then each timeskip crashed the game but still skipped time correctly. I would reload, apprentices would be 12+ moons, still classified as apprentices with no new names, and then the timeskip crash would happen again. Rinse and repeat.

**Comment by RedArrow12** [comment]
Same here, only my game would not crash. My apprentices would reach 12 moves, have the adult sprite but still have the name and apprentice status

**Comment by Charl-00tte** [comment]
^^ I forgot to mention the adult sprite

**Comment by Sum1Hehehe** [comment]
same here! its all my apprentices

**Comment by Maplewhisper11** [comment]
This happened to me to!

**Comment by scribblecrumb** [comment]
This is part of the new EXP system, apps now graduate based on EXP rather than age.  As for the crash, I haven't heard any recent bug reports on this, have you experienced this on the newest version?

**Comment by Charl-00tte** [comment]
Yes, I did. I even tried re-installing and it was still causing me to crash. I think I'm going to try and re-install Thonny too next.

**Comment by scribblecrumb** [comment]
Can you provide a screenshot of the traceback?

**Comment by Charl-00tte** [comment]
redownloaded Thonny, crashing hasn't happened since and the new exp system seems to be working.

**Comment by Sum1Hehehe** [comment]
does anyone know why this was closed and marked as completed? my apprentices are still in the adult sprites but with apprentice names and stuff

**Comment by Maplewhisper11** [comment]
> does anyone know why this was closed and marked as completed? my apprentices are still in the adult sprites but with apprentice names and stuff

They have to gain more experience first just keep sending them on patrols until their experience level says prepared, then they get their names.
