### ISSUE TITLE
qr code?????

### ISSUE THREAD

**Issue by SamixxHueYT** [ClanGenOfficial/clangen#931]
Hiya, So; im not sure if this is an 'issue', But i need help.

So, i was emailed and told some steps in order to get clangen on my chromebook On linux. i followed the steps and it gave me a QR code file. i dont know what to do with it, and i have another clangen file but it doesnt open or anything. 

My main questiion here is, Please, tell me what to do with this QR Code-

**Comment by lillithrosepup** [comment]
Hey! While yes, clangen can be run on chromebook, qr codes are not apart of this process at all. Can you please send us a screenshot of the email so we can investigate this? If you would like the guide to download clangen on chromebooks, join our discord [Here](https://discord.gg/clangen)! Remember, do not open qr codes from strangers. They _could_ lead to something dangerous. Thanks in advance!
