### ISSUE TITLE
bug with the apprentices

### ISSUE THREAD

**Issue by Sum1Hehehe** [ClanGenOfficial/clangen#953]
Hi so I don't know why but all my apprentices in all the clans have the adult sprite but have apprentice names and tasks and everything, I have no clue why this happened. This issue was already submitted by someone else but it was marked as "closed" for some reason even though it hasn't been fixed. A screenshot is attached.
![Screenshot 2023-03-11 9 47 36 PM](https://user-images.githubusercontent.com/127535064/224523160-93b7140d-0836-44a5-9f1d-0b8b87ef159c.png)

**Comment by lulIaby** [comment]
The cats sprites are determined by their ages, and an apprentice can graduate between 9 and 25 moons. An apprentice will have an adult sprite when they reach 12 moons. This is not an actual issue...
