### ISSUE TITLE
Why does it say the zip is empty or invalid??

### ISSUE THREAD

**Issue by omniversequirk** [ClanGenOfficial/clangen#954]
I've tried this at least three times, and every single time it has told me that the zip file is either containing nothing or is invalid. I don't know if this is an issue with github or an issue on my end.

**Comment by lillithrosepup** [comment]
This is an issue with your computer :( we dont know what causes this sadly

**Comment by DasBlackfur** [comment]
If you want to *play* clangen, I recommend you stick with the itch.io releases. If you want to help developing consider learning the basics of the `git` command. That will bring you further here.
