### ISSUE TITLE
Rescued kit, received completely different cat

### ISSUE THREAD

**Issue by BashfulWolf** [ClanGenOfficial/clangen#955]
Had a patrol encounter where one of my cats rescued a kit, however instead of a kit it was instead a full grown cat. Took the first pic to show my friend the pixel art and the encounter for it, which was immediately followed with the other two pics.
![error1](https://user-images.githubusercontent.com/127643628/224523661-8d930bdf-4962-44e5-be24-7aad8151df21.png)
![error2](https://user-images.githubusercontent.com/127643628/224523665-0d950eab-c395-4a8b-9e09-df6746def07a.png)
![error3](https://user-images.githubusercontent.com/127643628/224523670-a2fd6bfc-1537-4239-8b25-5da08e4c1da3.png)

Quick edit, just happened to my friend. Wondering if kit and backstory cats got somehow swapped?? (Another edit, it's def the case as it happened to them again right after).
![error4](https://user-images.githubusercontent.com/127643628/224523943-16904c6d-24ff-402b-9dae-36b470bd617d.png)
![error5](https://user-images.githubusercontent.com/127643628/224523953-d95f3040-f655-446f-bd66-f2606649dd5c.png)

**Comment by scribblecrumb** [comment]
Are you able to replicate this in the newest version? There's been a lot of big changes to the code that handles those new cats, and a lot of bugfixes made.

**Comment by scribblecrumb** [comment]
This has been fixed!
